### ISSUE TITLE
Improve registration and reporting pages

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#10]
## Tickets
- [x] fecgov/fec-cms#407
- [x] fecgov/fec-cms#299
- [x] fecgov/fec-cms#244
- [x] fecgov/fec-cms#165
