### ISSUE TITLE
Build out site map

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#104]
**What we’re after:** We need to build out the rest of the structure of the new site to complete the realization of the site map. This includes: completing the “About” and “Latest Updates” work, the legal resources section, the compliance section, and more.

**Why we’re after it:** The new site needs to provide entry points to all information, whether it lives on the legacy site or new site. This work needs to be completed as soon as possible in order to give internal users an understanding of the new structure and the reassurance of knowing what pages will be where.

## Tickets
- [x] fecgov/fec-cms#5945
- [x] fecgov/fec-cms#5829
- [x] fecgov/fec-cms#5775
- [x] fecgov/fec-cms#5965
- [x] fecgov/fec-cms#5959
- [x] fecgov/fec-cms#5842
- [x] fecgov/fec-cms#5970
- [x] fecgov/fec-cms#5918
- [x] fecgov/fec-cms#5905
- [x] fecgov/fec-cms#5828
- [x] fecgov/fec-cms#5770
- [x] fecgov/fec-cms#5782
- [x] fecgov/fec-cms#846
- [x] fecgov/fec-cms#882
- [x] fecgov/fec-cms#815
- [x] fecgov/fec-cms#980
- [x] fecgov/fec-cms#1016
- [x] fecgov/fec-cms#1045
- [x] fecgov/fec-cms#985
- [x] fecgov/fec-cms#977
- [x] fecgov/fec-cms#933
- [x] fecgov/fec-cms#1017
- [x] fecgov/fec-cms#1018
- [x] fecgov/fec-cms#782
- [x] fecgov/fec-cms#1014
- [x] fecgov/fec-cms#744
- [x] fecgov/fec-cms#961
- [x] fecgov/fec-cms#923
- [x] fecgov/fec-cms#919
- [x] fecgov/fec-cms#896
- [x] fecgov/fec-cms#1003
- [x] fecgov/fec-cms#976
- [x] fecgov/fec-cms#935
- [x] fecgov/fec-cms#880
- [x] fecgov/fec-cms#940
- [x] fecgov/fec-cms#851
- [x] fecgov/fec-cms#893
- [x] fecgov/fec-cms#704
- [x] fecgov/fec-cms#932
- [x] fecgov/fec-cms#860
- [x] fecgov/fec-cms#776
- [x] fecgov/fec-cms#934
- [x] fecgov/fec-cms#916
- [x] fecgov/fec-cms#813
- [x] fecgov/fec-cms#924
- [x] fecgov/fec-cms#925
- [x] fecgov/fec-cms#926
- [x] fecgov/fec-cms#870
- [x] fecgov/fec-cms#827
- [x] fecgov/fec-cms#931
- [x] fecgov/fec-cms#877
- [x] fecgov/fec-cms#875
- [x] fecgov/fec-cms#843
- [x] fecgov/fec-cms#855
- [x] fecgov/fec-cms#874
- [x] fecgov/fec-cms#852
- [x] fecgov/fec-cms#847
- [x] fecgov/fec-cms#873
- [x] fecgov/fec-cms#828
- [x] fecgov/fec-cms#824
- [x] fecgov/fec-cms#883
- [x] fecgov/fec-cms#876
- [x] fecgov/fec-cms#844
- [x] fecgov/fec-cms#754
- [x] fecgov/fec-cms#848
- [x] fecgov/fec-cms#783
- [x] fecgov/fec-cms#833
- [x] fecgov/fec-cms#845
- [x] fecgov/fec-cms#785
- [x] fecgov/fec-cms#778
- [x] fecgov/fec-cms#819
- [x] fecgov/fec-cms#842
- [x] fecgov/fec-cms#729
- [x] fecgov/fec-cms#816
- [x] fecgov/fec-cms#779
- [x] fecgov/openFEC-web-app#1838
- [x] fecgov/openFEC-web-app#1851
- [x] fecgov/openFEC-web-app#1877
- [x] fecgov/openFEC-web-app#1900
- [x] fecgov/openFEC-web-app#1901
