### ISSUE TITLE
Prepare for a unified site experience

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#105]
**What we’re after**: We need to prepare the new site and the legacy site to play well together after the switch. This will include some modifications to the current fec.gov and tweaks to aspects of the current beta site. It could entail redirects, messages on the legacy and new sites, updates to navigation, and more.

**Why we’re after it**: The two site experiences are drastically different, yet will continue to live alongside each other for some time. Users need to see the new site as the main FEC.gov, be able to navigate between the two, understand where they are and how to get back to where they came from, and need to know when the information they’re seeing is up-to-date or deprecated.

## Tickets
- [x] fecgov/fec-cms#974
- [x] fecgov/fec-cms#984
- [x] fecgov/fec-cms#966
- [x] fecgov/fec-cms#978
- [x] fecgov/fec-cms#930
- [x] fecgov/fec-cms#928
- [x] fecgov/fec-cms#872
- [x] fecgov/fec-cms#878
- [x] fecgov/fec-cms#840
- [x] fecgov/fec-cms#929
- [x] fecgov/fec-cms#881
- [x] fecgov/fec-cms#837
- [x] fecgov/fec-cms#835
- [x] fecgov/fec-cms#871
- [x] fecgov/fec-cms#484
- [x] fecgov/fec-cms#836
- [x] fecgov/fec-cms#850
- [x] fecgov/fec-cms#879
- [x] fecgov/openFEC-web-app#1772
- [x] fecgov/openFEC-web-app#1887
- [x] fecgov/openFEC-web-app#1888
- [x] fecgov/openFEC-web-app#1908
