### ISSUE TITLE
QA campaign finance data

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#106]
**What we’re after**: Internal users have been (and will continue to) QA the finance data displayed on the site and we need to address all remaining issues in order to have the data be as trustworthy as possible. 

**Why we’re after it**: Users need to trust the data they see on the site and the data needs to be accurate and complete.

## Tickets
- [x] fecgov/openFEC#2324
- [x] fecgov/openFEC#2309
- [x] fecgov/openFEC#2354
- [x] fecgov/openFEC#2255
- [x] fecgov/openFEC#2375
- [x] fecgov/openFEC#2364
- [x] fecgov/openFEC#2367
- [x] fecgov/openFEC#2248
- [x] fecgov/openFEC#2320
- [x] fecgov/openFEC#2321
- [x] fecgov/openFEC#2292
- [x] fecgov/openFEC#2319
- [x] fecgov/openFEC#2300
- [x] fecgov/openFEC#2119
- [x] fecgov/openFEC#2322
- [x] fecgov/openFEC#2225
- [x] fecgov/openFEC#2331
- [x] fecgov/openFEC#2243
- [x] fecgov/openFEC#2117
- [x] fecgov/openFEC#2197
- [x] fecgov/openFEC#2251
- [x] fecgov/openFEC#2267
- [x] fecgov/openFEC#2210
- [x] fecgov/openFEC#2249
- [x] fecgov/openFEC#2268
- [x] fecgov/openFEC#2216
- [x] fecgov/openFEC-web-app#1644
- [x] fecgov/openFEC-web-app#1753
- [x] fecgov/openFEC-web-app#1841
- [x] fecgov/openFEC-web-app#1845
- [x] fecgov/openFEC-web-app#1850
- [x] fecgov/openFEC-web-app#1852
- [x] fecgov/openFEC-web-app#1854
- [x] fecgov/openFEC-web-app#1863
- [x] fecgov/openFEC-web-app#1864
- [x] fecgov/openFEC-web-app#1894
- [x] fecgov/openFEC-web-app#1929
- [x] fecgov/openFEC-web-app#1962
- [x] fecgov/openFEC-web-app#1976
- [x] fecgov/openFEC-web-app#1985

**Comment by noahmanger** [comment]
Consolidating remaining open issues under #110
