### ISSUE TITLE
AO and legal infrastructure (pre-flip)

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#107]
**What we’re after**: First, we need to finish our implementation of the AOs, including adding citation filters and showing citations on the canonical pages. We also need to get an automatic refresh of the data going and get ElasticSearch production ready.

**Why we’re after it**: As the most mature set of legal data available, we need to get it as good as possible in order to provide a viable tool for users on the new site. Users need to trust the data they’re getting and in order to trust it, they need to be able to perform similar searches that they do in the old system. Having the most current data in the system at all times is also important for building trust in the new system.

## Tickets
- [x] fecgov/openFEC#2339
- [x] fecgov/fec-eregs#344
- [x] fecgov/openFEC#2242
- [x] fecgov/openFEC#2189
- [x] fecgov/openFEC#2307
- [x] fecgov/openFEC#2240
- [x] fecgov/fec-eregs#306
- [x] fecgov/openFEC#2222
- [x] fecgov/openFEC#2269
- [x] fecgov/openFEC#2241
- [x] fecgov/openFEC#2164
- [x] fecgov/openFEC#2232
- [x] fecgov/openFEC#2188
- [x] fecgov/openFEC#2220
- [x] fecgov/openFEC#2221
- [x] fecgov/openFEC#2219
- [x] fecgov/openFEC#2186
- [x] fecgov/fec-eregs#324
- [x] fecgov/openFEC-web-app#1762
- [x] fecgov/openFEC-web-app#1794
- [x] fecgov/openFEC-web-app#1810
- [x] fecgov/openFEC-web-app#1856
- [x] fecgov/openFEC-web-app#1857
- [x] fecgov/openFEC-web-app#1880
- [x] fecgov/openFEC-web-app#1881
- [x] fecgov/openFEC-web-app#1882
- [x] fecgov/openFEC-web-app#1905
- [x] fecgov/openFEC-web-app#1944
- [x] fecgov/openFEC-web-app#1975
- [x] fecgov/openFEC-web-app#1977
- [x] fecgov/openFEC-web-app#1978
- [x] fecgov/openFEC-web-app#2005

**Comment by noahmanger** [comment]
We did this!
