### ISSUE TITLE
FEC team takes ownership

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#108]
**What we’re after**: The priority for April through June is for the FEC team to take ownership of site operations. To do this, a small team of a senior FEC developers and a few 18F developers will spin up parallel to a small 18F team. They will work on their own epics while learning the technology of the site. This also includes training additional members of the FEC.

**Why we’re after it**: FEC senior developers need to understand the technology of the new site and building features alongside 18F is the best way to learn it.

## Tickets
- [x] fecgov/fec-cms#624
- [x] fecgov/fec-transition#54
- [x] fecgov/fec-transition#55
- [x] fecgov/fec-transition#58
