### ISSUE TITLE
Election summary data presentation

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#109]
**What we’re after:** Interactive graphic overviews that provide high-level election summary information around contributions and spending that address some of the needs previously served by the maps on the classic site.

**Why we’re after it:** Users have a need to compare the total raised and spent in races (both overall and broken out by party) in order to look for interesting contests and to find broad trends. There’s no way to do this on the new site currently, but this is one of the needs that the classic disclosure maps seek to address. This could also be a more useful way to allow users to get to individual election pages.

## Tickets
- [x] fecgov/openFEC#2557
- [x] fecgov/openFEC#2518
- [x] fecgov/openFEC-web-app#1655
- [x] fecgov/openFEC-web-app#2070
- [x] fecgov/openFEC-web-app#2099
- [x] fecgov/openFEC-web-app#2100
- [x] fecgov/openFEC-web-app#2101
- [x] fecgov/openFEC-web-app#2116
- [x] fecgov/openFEC-web-app#2161
- [x] fecgov/openFEC-web-app#2163
- [x] fecgov/openFEC-web-app#2164
- [x] fecgov/openFEC-web-app#2165
- [x] fecgov/openFEC-web-app#2166
- [x] fecgov/openFEC-web-app#2167
- [x] fecgov/openFEC-web-app#2178
- [x] fecgov/openFEC-web-app#2197
- [x] fecgov/openFEC-web-app#2198
- [x] fecgov/openFEC-web-app#2200
- [x] fecgov/openFEC-web-app#2232
- [x] fecgov/openFEC-web-app#2247
- [x] fecgov/openFEC-web-app#2267
- [x] fecgov/openFEC-web-app#2268
- [x] fecgov/openFEC-web-app#2269
- [x] fecgov/openFEC-web-app#2270

**Comment by noahmanger** [comment]
Summary of where we left things after the initial design and research: https://github.com/18F/openFEC-web-app/issues/2167
