### ISSUE TITLE
Data overview charts

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#11]
## Tickets
- [x] fecgov/openFEC#1991
- [x] fecgov/openFEC#1680
- [x] fecgov/openFEC#1953
- [x] fecgov/openFEC-web-app#1353
- [x] fecgov/openFEC-web-app#1354
- [x] fecgov/openFEC-web-app#1603
- [x] fecgov/openFEC-web-app#1643
- [x] fecgov/openFEC-web-app#1685
