### ISSUE TITLE
Finance data browsing improvements

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#110]
**What we’re after**:  This includes looking into ways to expand the scope of the current itemized receipts and disbursement searches to include a wider range of time, adding additional columns, sorting options and filters for the data.

**Why we’re after it**: While all the data is currently available on the new site, we know there’s various areas that need improvement in the way users browse it. Users have expressed a strong need to be able to run searches across a wider range of time in order to have a more complete and trustworthy set of results.

## Tickets
- [x] fecgov/openFEC#2324
- [x] fecgov/openFEC#2309
- [x] fecgov/openFEC#2183
- [x] fecgov/openFEC#2332
- [x] fecgov/openFEC#2423
- [x] fecgov/openFEC#2431
- [x] fecgov/openFEC#2378
- [x] fecgov/openFEC#2373
- [x] fecgov/openFEC#2476
- [x] fecgov/openFEC#2368
- [x] fecgov/openFEC#2226
- [x] fecgov/openFEC#2228
- [x] fecgov/openFEC#2475
- [x] fecgov/openFEC#2438
- [x] fecgov/openFEC#2318
- [x] fecgov/openFEC#2408
- [x] fecgov/openFEC#2442
- [x] fecgov/openFEC#2227
- [x] fecgov/openFEC-web-app#1614
- [x] fecgov/openFEC-web-app#1685
- [x] fecgov/openFEC-web-app#1816
- [x] fecgov/openFEC-web-app#1841
- [x] fecgov/openFEC-web-app#1854
- [x] fecgov/openFEC-web-app#1902
- [x] fecgov/openFEC-web-app#1960
- [x] fecgov/openFEC-web-app#2016
- [x] fecgov/openFEC-web-app#2018
- [x] fecgov/openFEC-web-app#2038
- [x] fecgov/openFEC-web-app#2041
- [x] fecgov/openFEC-web-app#2054
- [x] fecgov/openFEC-web-app#2055
- [x] fecgov/openFEC-web-app#2074
- [x] fecgov/openFEC-web-app#2076
- [x] fecgov/openFEC-web-app#2077
- [x] fecgov/openFEC-web-app#2094
- [x] fecgov/openFEC-web-app#2103
- [x] fecgov/openFEC-web-app#2115
- [x] fecgov/openFEC-web-app#2122
- [x] fecgov/openFEC-web-app#2124
- [x] fecgov/openFEC-web-app#2125
- [x] fecgov/openFEC-web-app#2133
