### ISSUE TITLE
Search and improved navigation

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#111]
**What we’re after**: This includes building out and making improvements to the site navigation as well as improvements to searching. In terms of searching, we can include unifying candidate and committee searches within the data section, and also implementing a site-wide search.

**Why we’re after it**: Users have expressed various challenges around finding what they’re looking for both in general and specific terms. People have asked for site-wide searches, a unified candidate and committee search and changes to the mega menu system.

## Tickets
- [x] fecgov/fec-cms#1102
- [x] fecgov/fec-cms#1033
- [x] fecgov/fec-cms#1043
- [x] fecgov/openFEC-web-app#2061
