### ISSUE TITLE
Legal resource enhancements (post-flip)

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#112]
**What we’re after:** The goal is that by the end of June, AOs are fully complete. This includes adding the plain language summaries to canonical pages, adding any remaining filters, implementing the enhanced search results and filter interactions, and making changes that may come up from usability testing or FEC internal review. 

**Why we’re after it**: By the time 18F has finished, the AO search should be at the level of being a full replacement for the existing AO lookup.

## Tickets
- [x] fecgov/fec-eregs#329
- [x] fecgov/openFEC#2125
- [x] fecgov/openFEC#2150
- [x] fecgov/openFEC#2153
- [x] fecgov/openFEC#2445
- [x] fecgov/openFEC#2444
- [x] fecgov/openFEC#2478
- [x] fecgov/openFEC#2460
- [x] fecgov/openFEC#2341
- [x] fecgov/openFEC#2415
- [x] fecgov/openFEC#2337
- [x] fecgov/openFEC-web-app#1747
- [x] fecgov/openFEC-web-app#1807
- [x] fecgov/openFEC-web-app#1883
- [x] fecgov/openFEC-web-app#1965
- [x] fecgov/openFEC-web-app#2007
- [x] fecgov/openFEC-web-app#2069
- [x] fecgov/openFEC-web-app#2086
