### ISSUE TITLE
Epic: Miscellaneous tasks, chores and bugs

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#113]
This is an epic for capturing all the miscellaneous tasks around the site flip.

---

Update (5/24): Generalizing this to miscellaneous tasks and chores that are happening post-flip.

## Tickets
- [x] fecgov/fec-cms#1254
- [x] fecgov/fec-cms#3060
- [x] fecgov/fec-cms#3081
- [x] fecgov/openFEC#3987
- [x] fecgov/fec-cms#3029
- [x] fecgov/openFEC#3906
- [x] fecgov/openFEC#3905
- [x] fecgov/fec-cms#2972
- [x] fecgov/fec-cms#2993
- [x] fecgov/openFEC#3904
- [x] fecgov/openFEC#3866
- [x] fecgov/fec-cms#3087
- [x] fecgov/fec-cms#3047
- [x] fecgov/openFEC#3852
- [x] fecgov/fec-cms#1697
- [x] fecgov/fec-cms#3061
- [x] fecgov/openFEC#3833
- [x] fecgov/fec-cms#3040
- [x] fecgov/openFEC#3836
- [x] fecgov/fec-cms#3057
- [x] fecgov/fec-cms#3056
- [x] fecgov/fec-cms#3055
- [x] fecgov/openFEC#3787
- [x] fecgov/openFEC#3843
- [x] fecgov/openFEC#3844
- [x] fecgov/fec-cms#2870
- [x] fecgov/fec-cms#2958
- [x] fecgov/fec-cms#2901
- [x] fecgov/fec-cms#2792
- [x] fecgov/openFEC#3826
- [x] fecgov/fec-cms#2700
- [x] fecgov/fec-cms#2822
- [x] fecgov/openFEC#3774
- [x] fecgov/fec-pattern-library#135
- [x] fecgov/fec-cms#2823
- [x] fecgov/openFEC#3773
- [x] fecgov/openFEC#3642
- [x] fecgov/fec-eregs#435
- [x] fecgov/fec-cms#2859
- [x] fecgov/fec-cms#2851
- [x] fecgov/fec-cms#2826
- [x] fecgov/fec-cms#2762
- [x] fecgov/fec-cms#2777
- [x] fecgov/fec-cms#2746
- [x] fecgov/fec-cms#2742
- [x] fecgov/fec-cms#2718
- [x] fecgov/fec-cms#2765
- [x] fecgov/fec-cms#2537
- [x] fecgov/fec-cms#2497
- [x] fecgov/openFEC#2574
- [x] fecgov/fec-cms#2494
- [x] fecgov/fec-cms#2536
- [x] fecgov/fec-cms#2423
- [x] fecgov/fec-cms#2362
- [x] fecgov/fec-cms#2350
- [x] fecgov/fec-cms#1903
- [x] fecgov/fec-cms#2486
- [x] fecgov/openFEC#3353
- [x] fecgov/openFEC#3104
- [x] fecgov/fec-cms#2427
- [x] fecgov/openFEC#3389
- [x] fecgov/fec-cms#2377
- [x] fecgov/openFEC#3096
- [x] fecgov/openFEC#3280
- [x] fecgov/fec-pattern-library#127
- [x] fecgov/fec-pattern-library#117
- [x] fecgov/openFEC#3105
- [x] fecgov/openFEC#3344
- [x] fecgov/fec-cms#2294
- [x] fecgov/fec-cms#2056
- [x] fecgov/fec-cms#2303
- [x] fecgov/fec-cms#2280
- [x] fecgov/openFEC#3345
- [x] fecgov/openFEC#2490
- [x] fecgov/fec-cms#1598
- [x] fecgov/fec-cms#1503
- [x] fecgov/fec-cms#1507
- [x] fecgov/fec-cms#2026
- [x] fecgov/fec-cms#1988
- [x] fecgov/fec-cms#1510
- [x] fecgov/fec-cms#1737
- [x] fecgov/fec-cms#1538
- [x] fecgov/fec-eregs#364
- [x] fecgov/fec-cms#1900
- [x] fecgov/openFEC#2803
- [x] fecgov/fec-cms#1521
- [x] fecgov/fec-cms#1614
- [x] fecgov/fec-cms#1847
- [x] fecgov/fec-cms#1744
- [x] fecgov/openFEC#3009
- [x] fecgov/openFEC#2710
- [x] fecgov/fec-cms#1870
- [x] fecgov/openFEC#2962
- [x] fecgov/fec-cms#1809
- [x] fecgov/fec-cms#1759
- [x] fecgov/fec-cms#1848
- [x] fecgov/fec-cms#1723
- [x] fecgov/fec-eregs#380
- [x] fecgov/fec-cms#1522
- [x] fecgov/openFEC#2934
- [x] fecgov/fec-cms#1821
- [x] fecgov/fec-cms#1773
- [x] fecgov/openFEC#2773
- [x] fecgov/openFEC#2723
- [x] fecgov/fec-cms#1720
- [x] fecgov/openFEC#2923
- [x] fecgov/fec-cms#1757
- [x] fecgov/fec-cms#1781
- [x] fecgov/openFEC#2922
- [x] fecgov/fec-cms#1758
- [x] fecgov/openFEC#2791
- [x] fecgov/fec-cms#1733
- [x] fecgov/fec-cms#1203
- [x] fecgov/fec-cms#1376
- [x] fecgov/fec-cms#1731
- [x] fecgov/openFEC#2628
- [x] fecgov/openFEC#2634
- [x] fecgov/openFEC#2784
- [x] fecgov/fec-cms#1640
- [x] fecgov/fec-cms#1500
- [x] fecgov/fec-eregs#361
- [x] fecgov/fec-cms#1693
- [x] fecgov/fec-eregs#365
- [x] fecgov/fec-cms#1508
- [x] fecgov/fec-cms#1651
- [x] fecgov/fec-cms#1602
- [x] fecgov/fec-cms#1444
- [x] fecgov/fec-cms#1686
- [x] fecgov/openFEC#2532
- [x] fecgov/fec-pattern-library#9
- [x] fecgov/fec-cms#1523
- [x] fecgov/fec-cms#1615
- [x] fecgov/openFEC#2829
- [x] fecgov/openFEC#2777
- [x] fecgov/openFEC#2690
- [x] fecgov/fec-cms#1604
- [x] fecgov/fec-cms#1632
- [x] fecgov/fec-cms#1600
- [x] fecgov/fec-cms#1629
- [x] fecgov/openFEC#2779
- [x] fecgov/openFEC#2776
- [x] fecgov/fec-cms#1511
- [x] fecgov/fec-cms#1639
- [x] fecgov/openFEC#2748
- [x] fecgov/fec-cms#1467
- [x] fecgov/openFEC#2770
- [x] fecgov/openFEC#2765
- [x] fecgov/openFEC#2794
- [x] fecgov/fec-cms#1623
- [x] fecgov/fec-cms#1616
- [x] fecgov/fec-cms#1526
- [x] fecgov/fec-eregs#362
- [x] fecgov/openFEC#2771
- [x] fecgov/fec-cms#1461
- [x] fecgov/fec-cms#1317
- [x] fecgov/fec-cms#1417
- [x] fecgov/fec-cms#1318
- [x] fecgov/openFEC#2747
- [x] fecgov/fec-cms#1491
- [x] fecgov/openFEC#2756
- [x] fecgov/openFEC#2764
- [x] fecgov/fec-cms#1490
- [x] fecgov/fec-cms#1274
- [x] fecgov/openFEC#2706
- [x] fecgov/fec-cms#1425
- [x] fecgov/fec-cms#1384
- [x] fecgov/fec-cms#1385
- [x] fecgov/fec-cms#1306
- [x] fecgov/openFEC#2696
- [x] fecgov/fec-cms#1305
- [x] fecgov/openFEC#2621
- [x] fecgov/fec-cms#1447
- [x] fecgov/fec-cms#1361
- [x] fecgov/fec-cms#1415
- [x] fecgov/fec-cms#1414
- [x] fecgov/fec-cms#1372
- [x] fecgov/fec-cms#1373
- [x] fecgov/fec-cms#1429
- [x] fecgov/fec-cms#1438
- [x] fecgov/fec-cms#1430
- [x] fecgov/fec-cms#1375
- [x] fecgov/fec-cms#1251
- [x] fecgov/fec-cms#1342
- [x] fecgov/fec-cms#1416
- [x] fecgov/fec-cms#1259
- [x] fecgov/openFEC#2674
- [x] fecgov/fec-cms#1239
- [x] fecgov/openFEC#2541
- [x] fecgov/openFEC#2672
- [x] fecgov/fec-cms#1310
- [x] fecgov/fec-cms#1294
- [x] fecgov/openFEC#2633
- [x] fecgov/fec-cms#1262
- [x] fecgov/fec-cms#1321
- [x] fecgov/openFEC#2671
- [x] fecgov/openFEC#2642
- [x] fecgov/openFEC#2627
- [x] fecgov/fec-cms#1244
- [x] fecgov/fec-cms#1186
- [x] fecgov/openFEC#2455
- [x] fecgov/openFEC#2580
- [x] fecgov/openFEC#2556
- [x] fecgov/openFEC#2617
- [x] fecgov/openFEC#2261
- [x] fecgov/fec-cms#1125
- [x] fecgov/openFEC#2569
- [x] fecgov/openFEC#2652
- [x] fecgov/openFEC#2598
- [x] fecgov/openFEC#2600
- [x] fecgov/fec-cms#1163
- [x] fecgov/fec-cms#1190
- [x] fecgov/openFEC#2590
- [x] fecgov/openFEC#2579
- [x] fecgov/openFEC#2601
- [x] fecgov/openFEC#2578
- [x] fecgov/fec-cms#1189
- [x] fecgov/openFEC#2572
- [x] fecgov/fec-cms#1087
- [x] fecgov/openFEC#2549
- [x] fecgov/openFEC#2597
- [x] fecgov/openFEC#2474
- [x] fecgov/openFEC#2444
- [x] fecgov/openFEC#2459
- [x] fecgov/fec-cms#822
- [x] fecgov/fec-cms#1067
- [x] fecgov/openFEC#2468
- [x] fecgov/openFEC#2388
- [x] fecgov/openFEC#2399
- [x] fecgov/openFEC#2473
- [x] fecgov/openFEC#2467
- [x] fecgov/openFEC#2466
- [x] fecgov/openFEC#2386
- [x] fecgov/openFEC#2385
- [x] fecgov/openFEC#2384
- [x] fecgov/openFEC#2420
- [x] fecgov/fec-cms#1081
- [x] fecgov/fec-cms#927
- [x] fecgov/openFEC#2383
- [x] fecgov/openFEC#2340
- [x] fecgov/fec-cms#1025
- [x] fecgov/fec-cms#817
- [x] fecgov/openFEC#2338
- [x] fecgov/openFEC#2369
- [x] fecgov/fec-cms#1046
- [x] fecgov/openFEC#2359
- [x] fecgov/openFEC#2370
- [x] fecgov/openFEC#2371
- [x] fecgov/fec-cms#998
- [x] fecgov/openFEC#2377
- [x] fecgov/fec-cms#1047
- [x] fecgov/fec-cms#1034
- [x] fecgov/fec-cms#982
- [x] fecgov/fec-cms#1015
- [x] fecgov/openFEC#2346
- [x] fecgov/fec-cms#1011
- [x] fecgov/fec-cms#989
- [x] fecgov/openFEC#2336
- [x] fecgov/fec-cms#981
- [x] fecgov/openFEC#2274
- [x] fecgov/fec-cms#971
- [x] fecgov/fec-transition#107
- [x] fecgov/fec-transition#163
- [x] fecgov/fec-transition#164
- [x] fecgov/fec-transition#166
- [x] fecgov/fec-transition#175
- [x] fecgov/openFEC-web-app#1773
- [x] fecgov/openFEC-web-app#1774
- [x] fecgov/openFEC-web-app#1907
- [x] fecgov/openFEC-web-app#1935
- [x] fecgov/openFEC-web-app#1936
- [x] fecgov/openFEC-web-app#1954
- [x] fecgov/openFEC-web-app#1994
- [x] fecgov/openFEC-web-app#2012
- [x] fecgov/openFEC-web-app#2023
- [x] fecgov/openFEC-web-app#2036
- [x] fecgov/openFEC-web-app#2050
- [x] fecgov/openFEC-web-app#2068
- [x] fecgov/openFEC-web-app#2173
- [x] fecgov/openFEC-web-app#2179
- [x] fecgov/openFEC-web-app#2204
- [x] fecgov/openFEC-web-app#2210
- [x] fecgov/openFEC-web-app#2237
- [x] fecgov/openFEC-web-app#2244
- [x] fecgov/openFEC-web-app#2245
- [x] fecgov/openFEC-web-app#2254
- [x] fecgov/openFEC-web-app#2256
- [x] fecgov/openFEC-web-app#2274
- [x] fecgov/openFEC-web-app#2280
- [x] fecgov/openFEC-web-app#2302
- [x] fecgov/openFEC-web-app#2311
- [x] fecgov/openFEC-web-app#2313
- [x] fecgov/openFEC-web-app#2339
- [x] fecgov/openFEC-web-app#2340
- [x] fecgov/openFEC-web-app#2341
- [x] fecgov/openFEC-web-app#2343

**Comment by PaulClark2** [comment]
Closing in favor of smaller more specific epics
