### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#114]
## Tickets
- [x] fecgov/openFEC#2446
- [x] fecgov/openFEC#2394
- [x] fecgov/openFEC#2457
- [x] fecgov/openFEC-web-app#1775
- [x] fecgov/openFEC-web-app#2020
- [x] fecgov/openFEC-web-app#2039
