### ISSUE TITLE
Enhanced candidate and committee filter options

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#116]
**What we’re after:** Add remaining filter options and data columns to candidate and committee data sets so that common research tasks that are possible with classic are possible on the new site.

**Why we’re after it:** While the new site contains all the data, there are many views into this data that would be useful to improve the workflow for researchers and would allow datasets currently served on Waltham to shut down.

## Tickets
- [x] fecgov/openFEC#2631
- [x] fecgov/openFEC#1946
- [x] fecgov/openFEC#2428
- [x] fecgov/openFEC#2378
- [x] fecgov/openFEC#2559
- [x] fecgov/openFEC#2533
- [x] fecgov/openFEC-web-app#2125
- [x] fecgov/openFEC-web-app#2171
- [x] fecgov/openFEC-web-app#2191
- [x] fecgov/openFEC-web-app#2211
- [x] fecgov/openFEC-web-app#2222
- [x] fecgov/openFEC-web-app#2227
- [x] fecgov/openFEC-web-app#2228
- [x] fecgov/openFEC-web-app#2265
- [x] fecgov/openFEC-web-app#2271
- [x] fecgov/openFEC-web-app#2272
- [x] fecgov/openFEC-web-app#2273
- [x] fecgov/openFEC-web-app#2281
- [x] fecgov/openFEC-web-app#2282

**Comment by noahmanger** [comment]
For future reference, the doc we put together outlining the new data pages necessary  is here: [document](https://docs.google.com/document/d/1J2wJiD5e-YCxcuGV-SBVItAX8Qk4NWAAaFxGxVKgYh4/edit#) :lock:
