### ISSUE TITLE
FEC data management

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#117]
**What we’re after**: Improve the workflow around data and content management for people at the FEC by enhancing Wagtail workflows and addressing issues around data loading and latency.

**Why we’re after it**: In order to provide better, more reliable, and more usable data and content, and in order to have a happier staff with less frustration.

## Tickets
- [x] fecgov/openFEC#2427
- [x] fecgov/fec-cms#1180
- [x] fecgov/fec-cms#1208
- [x] fecgov/fec-cms#1179
- [x] fecgov/fec-cms#1181
- [x] fecgov/fec-transition#118
- [x] fecgov/openFEC-web-app#2248
- [x] fecgov/openFEC-web-app#2275
