### ISSUE TITLE
Enhanced receipt and disbursement searches

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-epics#118]
**What we’re after**: Expand the schedule A and B searches to include broader time periods and larger downloads.

**Why we’re after it**: People need to be able to find data across history and download large datasets for more complex research tasks.

## Tickets
- [x] fecgov/fec-cms#1613
- [x] fecgov/openFEC#2630
- [x] fecgov/openFEC#2685
- [x] fecgov/fec-cms#1685
- [x] fecgov/fec-cms#1391
- [x] fecgov/fec-cms#1470
- [x] fecgov/openFEC#2845
- [x] fecgov/fec-cms#1663
- [x] fecgov/fec-cms#1644
- [x] fecgov/openFEC#2844
- [x] fecgov/openFEC#2761
- [x] fecgov/fec-cms#1605
- [x] fecgov/fec-cms#1505
- [x] fecgov/openFEC#2692
- [x] fecgov/fec-cms#1434
- [x] fecgov/fec-cms#1439
- [x] fecgov/fec-cms#1339
- [x] fecgov/fec-cms#1329
- [x] fecgov/openFEC#2531
- [x] fecgov/openFEC#2684
- [x] fecgov/openFEC#2342
- [x] fecgov/openFEC#2521
- [x] fecgov/openFEC#2519
- [x] fecgov/fec-transition#92
- [x] fecgov/fec-transition#93
- [x] fecgov/fec-transition#94
- [x] fecgov/openFEC-web-app#2172
- [x] fecgov/openFEC-web-app#2177
- [x] fecgov/openFEC-web-app#2295
- [x] fecgov/openFEC-web-app#2301
- [x] fecgov/openFEC-web-app#2306
- [x] fecgov/openFEC-web-app#2307
