### ISSUE TITLE
Refine homepage and site navigation

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#119]
**What we’re after**: Solutions to some of the major navigation problems people have been having since the site flip, specifically around finding meeting agendas and other latest updates, and in general refine the home page based on what we’ve learned.

**Why we’re after it**: We have data that people are having difficulty finding latest updates and meeting agendas, as well as other pages. 

## Tickets
- [x] fecgov/fec-cms#1291
- [x] fecgov/fec-cms#1290
- [x] fecgov/fec-cms#1312
- [x] fecgov/fec-cms#1138
- [x] fecgov/fec-cms#1137
- [x] fecgov/fec-cms#1139
- [x] fecgov/fec-cms#1101
- [x] fecgov/openFEC-web-app#2132
- [x] fecgov/openFEC-web-app#2157
- [x] fecgov/openFEC-web-app#2158
- [x] fecgov/openFEC-web-app#2159
- [x] fecgov/openFEC-web-app#2176
- [x] fecgov/openFEC-web-app#2185
- [x] fecgov/openFEC-web-app#2201
