### ISSUE TITLE
Internal infrastructure, tooling and process improvements

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#12]
This is a broad epic for capturing all work related to our infrastructure, tooling and team process work. This includes work like upgrading infrastructure, adding things to the style guide, work that will help with transition hand-off, and more.

Including things here isn't meant as a demotion, but just clearly identify thigns that don't fall under a user-facing epic.

I'm open to breaking this out into smaller issues too.

## Tickets
- [x] fecgov/fec-cms#743
- [x] fecgov/fec-cms#609
- [x] fecgov/fec-cms#493
- [x] fecgov/fec-cms#223
- [x] fecgov/fec-cms#237
- [x] fecgov/openFEC#2170
- [x] fecgov/openFEC#2121
- [x] fecgov/openFEC#2004
- [x] fecgov/openFEC#1822
- [x] fecgov/openFEC#1646
- [x] fecgov/openFEC#1660
- [x] fecgov/openFEC#1621
- [x] fecgov/openFEC#1532
- [x] fecgov/openFEC#2610
- [x] fecgov/fec-cms#120
- [x] fecgov/openFEC#2611
- [x] fecgov/openFEC#2613
- [x] fecgov/openFEC#2585
- [x] fecgov/openFEC#2599
- [x] fecgov/openFEC#2522
- [x] fecgov/openFEC#2489
- [x] fecgov/fec-cms#403
- [x] fecgov/openFEC#2266
- [x] fecgov/openFEC#2058
- [x] fecgov/openFEC#2026
- [x] fecgov/fec-cms#714
- [x] fecgov/openFEC#2133
- [x] fecgov/openFEC#2136
- [x] fecgov/fec-cms#608
- [x] fecgov/fec-cms#607
- [x] fecgov/openFEC#2086
- [x] fecgov/fec-cms#541
- [x] fecgov/openFEC#1415
- [x] fecgov/openFEC#1785
- [x] fecgov/openFEC#1794
- [x] fecgov/openFEC#1926
- [x] fecgov/openFEC#1897
- [x] fecgov/openFEC-web-app#389
- [x] fecgov/openFEC-web-app#501
- [x] fecgov/openFEC-web-app#506
- [x] fecgov/openFEC-web-app#643
- [x] fecgov/openFEC-web-app#865
- [x] fecgov/openFEC-web-app#921
- [x] fecgov/openFEC-web-app#924
- [x] fecgov/openFEC-web-app#1352
- [x] fecgov/openFEC-web-app#1557
- [x] fecgov/openFEC-web-app#1585
- [x] fecgov/openFEC-web-app#1770
- [x] fecgov/openFEC-web-app#1898
