### ISSUE TITLE
Technology transition

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-epics#120]
**What we’re after**: Simplify codebase, build out pattern library, tech onboarding, optimizations, etc.

**Why we’re after it**: We want to make the system learnable, resilient and easy for a new team to own.

## Tickets
- [x] fecgov/openFEC#2520
- [x] fecgov/openFEC#2561
- [x] fecgov/openFEC#2564
- [x] fecgov/fec-cms#1169
- [x] fecgov/fec-cms#1168
- [x] fecgov/openFEC#2515
- [x] fecgov/fec-transition#53
- [x] fecgov/fec-transition#56
- [x] fecgov/fec-transition#57
- [x] fecgov/fec-transition#60
- [x] fecgov/fec-transition#64
- [x] fecgov/fec-transition#65
- [x] fecgov/fec-transition#66
- [x] fecgov/fec-transition#67
- [x] fecgov/fec-transition#68
- [x] fecgov/fec-transition#69
- [x] fecgov/fec-transition#70
- [x] fecgov/fec-transition#71
- [x] fecgov/fec-transition#72
- [x] fecgov/fec-transition#73
- [x] fecgov/fec-transition#74
- [x] fecgov/fec-transition#75
- [x] fecgov/fec-transition#76
- [x] fecgov/fec-transition#77
- [x] fecgov/fec-transition#79
- [x] fecgov/fec-transition#80
- [x] fecgov/fec-transition#81
- [x] fecgov/fec-transition#82
- [x] fecgov/fec-transition#83
- [x] fecgov/fec-transition#84
- [x] fecgov/fec-transition#85
- [x] fecgov/fec-transition#86
- [x] fecgov/fec-transition#87
- [x] fecgov/fec-transition#90
- [x] fecgov/fec-transition#91
- [x] fecgov/fec-transition#96
- [x] fecgov/fec-transition#98
- [x] fecgov/fec-transition#99
- [x] fecgov/fec-transition#101
- [x] fecgov/fec-transition#102
- [x] fecgov/fec-transition#103
- [x] fecgov/fec-transition#104
- [x] fecgov/fec-transition#105
- [x] fecgov/fec-transition#106
- [x] fecgov/fec-transition#108
- [x] fecgov/fec-transition#109
- [x] fecgov/fec-transition#111
- [x] fecgov/fec-transition#112
- [x] fecgov/fec-transition#113
- [x] fecgov/fec-transition#114
- [x] fecgov/fec-transition#116
- [x] fecgov/fec-transition#117
- [x] fecgov/fec-transition#121
- [x] fecgov/fec-transition#124
- [x] fecgov/fec-transition#126
- [x] fecgov/fec-transition#135
- [x] fecgov/fec-transition#136
- [x] fecgov/openFEC-web-app#2196
- [x] fecgov/openFEC-web-app#2207
- [x] fecgov/openFEC-web-app#2208
- [x] fecgov/openFEC-web-app#2234
- [x] fecgov/openFEC-web-app#2249
- [x] fecgov/openFEC-web-app#2250
- [x] fecgov/openFEC-web-app#2251
- [x] fecgov/openFEC-web-app#2266
