### ISSUE TITLE
Long-form content and components

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#121]
**What we’re after**: Add the reporting examples and citizens info content to the site, which will require design and development solutions to some of the new problems arising from the structure of this content.

**Why we’re after**: Users looking for this content need to find it in a readable, usable way. 

## Tickets
- [x] fecgov/fec-cms#1177
- [x] fecgov/fec-cms#1182
- [x] fecgov/fec-cms#1170
- [x] fecgov/fec-cms#1155
- [x] fecgov/fec-cms#1213
- [x] fecgov/fec-cms#1212
- [x] fecgov/fec-cms#1093
- [x] fecgov/fec-cms#1160
- [x] fecgov/fec-cms#1164
- [x] fecgov/fec-cms#1154
- [x] fecgov/fec-cms#1130
- [x] fecgov/fec-cms#1123
- [x] fecgov/fec-cms#1147
- [x] fecgov/fec-cms#1132
- [x] fecgov/fec-cms#1131
- [x] fecgov/fec-cms#1124
- [x] fecgov/fec-cms#1122
- [x] fecgov/openFEC-web-app#1160
