### ISSUE TITLE
Audit search

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-epics#122]
**What we’re after**: A replacement for the classic audit search, which has ~1,000 records. People need to be able to find audit reports searching by various criteria. This can follow the pattern of our other data interfaces. This does not need to include any fulltext searches of OCR’d text.

**Why we’re after it**: Users need to access audits and providing a way to filter them makes it possible. This feature is not currently working consistently on the classic site, so it’s also new added value.

## Tickets
- [x] fecgov/fec-cms#1304
- [x] fecgov/fec-cms#1512
- [x] fecgov/fec-cms#1497
- [x] fecgov/fec-cms#1368
- [x] fecgov/fec-cms#1347
- [x] fecgov/openFEC#2677
- [x] fecgov/fec-cms#1311
- [x] fecgov/openFEC#2675
- [x] fecgov/openFEC#2678
- [x] fecgov/openFEC#2676
- [x] fecgov/openFEC#2608
- [x] fecgov/openFEC#2542
- [x] fecgov/openFEC-web-app#2168
- [x] fecgov/openFEC-web-app#2261
- [x] fecgov/openFEC-web-app#2262
- [x] fecgov/openFEC-web-app#2289
- [x] fecgov/openFEC-web-app#2312
- [x] fecgov/openFEC-web-app#2317
- [x] fecgov/openFEC-web-app#2324
- [x] fecgov/openFEC-web-app#2329
- [x] fecgov/openFEC-web-app#2338
