### ISSUE TITLE
AO enhancements

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#125]
**What we’re after**: Add remaining features to the AO search to be an effective replacement for SAOS. This requires completing the boolean search fields and following through on any changes we want to make around making it easier to browse documents (e.g. the split view).

**Why we’re after it**: Users need to be able to construct complex queries using boolean logic to weed through results, and expect this functionality based on other tools they use. They also need to be able to quickly skim through multiple documents in a case.

## Tickets
- [x] fecgov/openFEC#2235
- [x] fecgov/openFEC-web-app#2085
- [x] fecgov/openFEC-web-app#2162
- [x] fecgov/openFEC-web-app#2170
- [x] fecgov/openFEC-web-app#2174
- [x] fecgov/openFEC-web-app#2214
- [x] fecgov/openFEC-web-app#2235
- [x] fecgov/openFEC-web-app#2291
