### ISSUE TITLE
Data catalog and election summary

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#127]
What we’re after: Completing our work in progress to improve users’ experience. Add remaining filter options and data columns to candidate and committee data sets so that common research tasks that are possible on classic are possible on the new site and finish wireframe/designs for election summaries. Does not include implementation of election summary mockups.

Why we’re after it: While the new site contains all the data, there are many views into this data that would be useful to improve the workflow for researchers and would allow datasets currently served on Waltham to shut down. 

## Tickets
- [x] fecgov/fec-cms#1400
- [x] fecgov/fec-cms#1406
- [x] fecgov/fec-cms#1309
- [x] fecgov/fec-cms#1396
- [x] fecgov/fec-cms#1402
- [x] fecgov/fec-cms#1401
- [x] fecgov/fec-cms#1399
- [x] fecgov/fec-cms#1674
- [x] fecgov/fec-cms#1532
- [x] fecgov/fec-cms#1531
- [x] fecgov/fec-cms#1486
- [x] fecgov/openFEC#2679
- [x] fecgov/fec-cms#1458
- [x] fecgov/fec-cms#1405
- [x] fecgov/fec-cms#1280
- [x] fecgov/openFEC-web-app#2199
- [x] fecgov/openFEC-web-app#2318
- [x] fecgov/openFEC-web-app#2321
- [x] fecgov/openFEC-web-app#2330
