### ISSUE TITLE
Enhance legal resources section

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#128]
What we’re after:  Completing our work in progress to improve users’ experience in this section

Why we’re after it: Users need to be able to understand the legal resources we provide on the website, easily find the resources they seek, and feel confident that they’ve found everything they were looking for. To help accomplish this goal we will:
- [ ] Implement the new legal resources landing page designs
- [ ] Take steps to surface the MUR number search filter we added last PI
- [ ] Take steps to allow users to search MURs by time frame, for example by creating a date opened/date closed filter.

## Tickets
- [x] fecgov/fec-cms#1333
- [x] fecgov/fec-eregs#369
- [x] fecgov/openFEC#2810
- [x] fecgov/openFEC#2847
- [x] fecgov/openFEC#2762
- [x] fecgov/fec-eregs#359
- [x] fecgov/fec-cms#1601
- [x] fecgov/fec-cms#1425
- [x] fecgov/fec-cms#1390
- [x] fecgov/fec-cms#1435
- [x] fecgov/openFEC#2705
- [x] fecgov/openFEC#2511
- [x] fecgov/openFEC#2683
- [x] fecgov/fec-cms#1365
- [x] fecgov/openFEC#2512
- [x] fecgov/openFEC-web-app#1883
- [x] fecgov/openFEC-web-app#2288
- [x] fecgov/openFEC-web-app#2290
- [x] fecgov/openFEC-web-app#2303
- [x] fecgov/openFEC-web-app#2304
- [x] fecgov/openFEC-web-app#2305
- [x] fecgov/openFEC-web-app#2314
- [x] fecgov/openFEC-web-app#2322
- [x] fecgov/openFEC-web-app#2323
- [x] fecgov/openFEC-web-app#2331
