### ISSUE TITLE
18F-FEC transition

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#129]
What we’re after: FEC takes full ownership of the development and maintenance of the website.

Why we’re after it: As the FEC’s partnership with 18F draws to a close, the FEC will need to have full ownership of all aspects of the site as well as the skills and expertise to continue user-focused, agile product delivery. 

Ownership includes taking over the ATO, GitHub repos and other services and accounts. 

We’ll also focus on staff training and coaching to fill skill gaps and ensure FEC staff are proficient in the website’s technology stack.

## Tickets
- [x] fecgov/openFEC#2995
- [x] fecgov/fec-cms#1833
- [x] fecgov/fec-cms#1834
- [x] fecgov/fec-cms#1896
- [x] fecgov/fec-cms#1805
- [x] fecgov/fec-cms#1807
- [x] fecgov/fec-pattern-library#81
- [x] fecgov/openFEC#2943
- [x] fecgov/openFEC#2944
- [x] fecgov/fec-pattern-library#68
- [x] fecgov/fec-cms#1836
- [x] fecgov/fec-pattern-library#51
- [x] fecgov/fec-eregs#379
- [x] fecgov/fec-pattern-library#48
- [x] fecgov/fec-cms#1808
- [x] fecgov/fec-pattern-library#47
- [x] fecgov/fec-cms#1779
- [x] fecgov/fec-pattern-library#46
- [x] fecgov/fec-cms#1806
- [x] fecgov/openFEC#2951
- [x] fecgov/fec-cms#1617
- [x] fecgov/fec-cms#1119
- [x] fecgov/openFEC#2722
- [x] fecgov/fec-cms#1489
- [x] fecgov/fec-pattern-library#28
- [x] fecgov/fec-pattern-library#27
- [x] fecgov/fec-cms#1297
- [x] fecgov/fec-cms#1332
- [x] fecgov/fec-cms#1303
- [x] fecgov/openFEC#2488
- [x] fecgov/openFEC#2680
- [x] fecgov/openFEC-web-app#2246
- [x] fecgov/openFEC-web-app#2319
- [x] fecgov/openFEC-web-app#2320
- [x] fecgov/openFEC-web-app#2325
- [x] fecgov/openFEC-web-app#2326
