### ISSUE TITLE
New home page

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#13]
**What we’re after:** When the new site becomes the main site, it will need to have a new home page that serves the role of an actual home page. This page will introduce users to the FEC, show them what’s happening with the agency, and get them to the parts of the site they need in order to complete their tasks. This feature is currently in the middle of design. 

**Why we’re after it:** The FEC has a tremendous amount of information on its website, and we need to help people find what they’re looking for. Because not many people know what the FEC is, we also need to communicate what the FEC is and what they do. And last, with so much happening all the time with the FEC, people need to be able to find what’s new, what’s upcoming or what just happened at the agency.

## Tickets
- [x] fecgov/fec-cms#689
- [x] fecgov/fec-cms#605
- [x] fecgov/fec-cms#776
- [x] fecgov/fec-cms#684
- [x] fecgov/openFEC#2122
- [x] fecgov/fec-cms#646
- [x] fecgov/fec-cms#694
- [x] fecgov/fec-cms#637
- [x] fecgov/fec-cms#656
- [x] fecgov/fec-cms#617
- [x] fecgov/fec-cms#635
- [x] fecgov/fec-cms#636
- [x] fecgov/fec-cms#638
- [x] fecgov/fec-cms#639
- [x] fecgov/fec-cms#634
- [x] fecgov/fec-cms#644
- [x] fecgov/fec-eregs#32
- [x] fecgov/fec-cms#604
- [x] fecgov/fec-cms#603
- [x] fecgov/fec-cms#606
- [x] fecgov/fec-cms#554
- [x] fecgov/fec-cms#518
- [x] fecgov/fec-cms#517
- [x] fecgov/fec-cms#464
- [x] fecgov/fec-cms#463
