### ISSUE TITLE
Reduce technical debt

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#130]
What we’re after: Improve production resilience and stability, simplify codebase, build out pattern library, tech onboarding, optimizations, production maintenance, etc.

Why we’re after it: We want to make the system learnable, resilient and easy for a new team to own. 

## Tickets
- [x] fecgov/openFEC#2884
- [x] fecgov/openFEC#2749
- [x] fecgov/fec-cms#1358
- [x] fecgov/openFEC#2752
- [x] fecgov/openFEC#2797
- [x] fecgov/openFEC#2681
- [x] fecgov/openFEC#2802
- [x] fecgov/openFEC#2724
- [x] fecgov/fec-cms#1417
- [x] fecgov/openFEC#2751
- [x] fecgov/fec-cms#1307
- [x] fecgov/fec-cms#1308
- [x] fecgov/fec-cms#1336
- [x] fecgov/openFEC#2745
- [x] fecgov/openFEC#2746
- [x] fecgov/openFEC#2686
- [x] fecgov/openFEC#2733
- [x] fecgov/openFEC#2734
- [x] fecgov/openFEC#2732
- [x] fecgov/openFEC#2682
