### ISSUE TITLE
UX/content optimization

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#134]
**What we’re after**: We want to make important information easier to find and make overall site navigation more intuitive to both new users and power users of the site.

**Why we’re after it**: Over the last quarter, we’ve learned more about internal and external user needs and pain points regarding:

Finding Audit Reports
* Moving between candidate data pages and committee pages
* Using the boolean search
* Using the mega menu and burger menu
* Finding and using the “find your analyst” form
* Navigating between CMS and transition pages

We’ll make improvements to these features, and migrate additional content off of transition, to help users have a better experience.

## Tickets
- [ ] fecgov/fec-cms#5912
- [x] fecgov/fec-pattern-library#79
- [x] fecgov/fec-cms#1828
- [x] fecgov/fec-cms#1995
- [x] fecgov/fec-cms#1982
- [x] fecgov/fec-cms#1214
- [x] fecgov/fec-cms#1865
- [x] fecgov/fec-cms#1879
- [x] fecgov/fec-cms#1864
- [x] fecgov/fec-cms#1929
- [x] fecgov/fec-cms#1895
- [x] fecgov/fec-cms#1866
- [x] fecgov/fec-cms#1772
- [x] fecgov/fec-cms#1736
- [x] fecgov/fec-cms#1778
- [x] fecgov/fec-cms#1750
- [x] fecgov/fec-pattern-library#39
- [x] fecgov/fec-cms#1904
- [x] fecgov/fec-cms#1829
- [x] fecgov/fec-cms#1756
- [x] fecgov/fec-cms#1753
- [x] fecgov/fec-cms#1752
- [x] fecgov/fec-cms#1754
- [x] fecgov/fec-cms#1728
