### ISSUE TITLE
Epic: Stability and reliability

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#137]
**What we’re after**: Improved stability and reliability of all applications and processes that comprise the website.

**Why we’re after it**: For fec.gov to serve as the public’s authoritative source of campaign finance information, it must provide consistent, timely and accurate information and remain dependably accessible to the public. To achieve this, we’ll continue our work to make the website more performant and reduce downtime, including implementing metrics to measure our progress and success. We’ll also focus on particular pain points identified during the past quarter:

Optimizing the loading of legal resources, ensuring quick updates, etc.

- Continue to fix bugs
- Site reliability and stability including patching and security
- New Relic monitoring

## Epics
- [ ] fecgov/fec-epics#163
- [ ] fecgov/fec-epics#158
- [ ] fecgov/fec-epics#164
- [ ] fecgov/fec-epics#159
- [x] fecgov/fec-epics#166
- [x] fecgov/fec-epics#160
- [x] fecgov/fec-epics#165

## Tickets
- [ ] fecgov/openFEC#4573
- [x] fecgov/fec-cms#3872
- [ ] fecgov/fec-cms#3211
- [ ] fecgov/fec-cms#4167
- [ ] fecgov/openFEC#4700
- [ ] fecgov/fec-cms#4127
- [ ] fecgov/openFEC#4624
- [ ] fecgov/openFEC#4593
- [ ] fecgov/openFEC#4471
- [ ] fecgov/fec-cms#3726
- [x] fecgov/fec-cms#5680
- [ ] fecgov/fec-cms#3225
- [ ] fecgov/openFEC#3629
- [ ] fecgov/openFEC#3857
- [ ] fecgov/openFEC#3858
- [ ] fecgov/openFEC#3758
- [ ] fecgov/fec-cms#3465
- [x] fecgov/fec-cms#5713
- [x] fecgov/fec-cms#6083
- [x] fecgov/openFEC#5718
- [x] fecgov/fec-cms#6101
- [x] fecgov/openFEC#5717
- [x] fecgov/fec-cms#6082
- [x] fecgov/openFEC#5637
- [x] fecgov/openFEC#5636
- [x] fecgov/openFEC#5654
- [x] fecgov/fec-cms#5952
- [x] fecgov/openFEC#5653
- [x] fecgov/fec-cms#5981
- [x] fecgov/openFEC#5633
- [x] fecgov/openFEC#5652
- [x] fecgov/openFEC#5602
- [x] fecgov/openFEC#5629
- [x] fecgov/fec-cms#5946
- [x] fecgov/openFEC#5628
- [x] fecgov/fec-cms#5977
- [x] fecgov/openFEC#5596
- [x] fecgov/openFEC#5612
- [x] fecgov/openFEC#5523
- [x] fecgov/openFEC#5570
- [x] fecgov/openFEC#5536
- [x] fecgov/fec-cms#5896
- [x] fecgov/openFEC#5576
- [x] fecgov/fec-eregs#792
- [x] fecgov/fec-cms#5878
- [x] fecgov/openFEC#5524
- [x] fecgov/fec-eregs#789
- [x] fecgov/fec-eregs#777
- [x] fecgov/openFEC#5501
- [x] fecgov/openFEC#4173
- [x] fecgov/openFEC#5484
- [x] fecgov/openFEC#5440
- [x] fecgov/openFEC#5483
- [x] fecgov/fec-eregs#760
- [x] fecgov/fec-cms#5726
- [x] fecgov/openFEC#5461
- [x] fecgov/openFEC#5460
- [x] fecgov/fec-eregs#756
- [x] fecgov/openFEC#5439
- [x] fecgov/openFEC#5438
- [x] fecgov/fec-proxy#360
- [x] fecgov/openFEC#5443
- [x] fecgov/fec-cms#5727
- [x] fecgov/fec-eregs#761
- [x] fecgov/openFEC#5418
- [x] fecgov/openFEC#5417
- [x] fecgov/openFEC#5428
- [x] fecgov/openFEC#4364
- [x] fecgov/fec-cms#5394
- [x] fecgov/fec-cms#4988
- [x] fecgov/fec-eregs#735
- [x] fecgov/fec-eregs#722
- [x] fecgov/openFEC#5184
- [x] fecgov/fec-cms#5422
- [x] fecgov/fec-cms#5368
- [x] fecgov/fec-eregs#699
- [x] fecgov/openFEC#5182
- [x] fecgov/fec-eregs#703
- [x] fecgov/fec-cms#5362
- [x] fecgov/openFEC#5215
- [x] fecgov/openFEC#5214
- [x] fecgov/openFEC#5146
- [x] fecgov/openFEC#5132
- [x] fecgov/fec-eregs#685
- [x] fecgov/openFEC#5098
- [x] fecgov/fec-cms#5178
- [x] fecgov/openFEC#5125
- [x] fecgov/fec-cms#5193
- [x] fecgov/openFEC#5017
- [x] fecgov/fec-eregs#675
- [x] fecgov/openFEC#5058
- [x] fecgov/openFEC#5092
- [x] fecgov/openFEC#5067
- [x] fecgov/fec-cms#5030
- [x] fecgov/openFEC#5059
- [x] fecgov/openFEC#5066
- [x] fecgov/openFEC#5007
- [x] fecgov/fec-cms#5029
- [x] fecgov/fec-eregs#450
- [x] fecgov/fec-cms#4993
- [x] fecgov/fec-cms#4894
- [x] fecgov/fec-eregs#660
- [x] fecgov/fec-eregs#655
- [x] fecgov/openFEC#5004
- [x] fecgov/openFEC#5006
- [x] fecgov/fec-eregs#644
- [x] fecgov/fec-eregs#643
- [x] fecgov/fec-eregs#646
- [x] fecgov/fec-cms#5020
- [x] fecgov/fec-eregs#645
- [x] fecgov/openFEC#5021
- [x] fecgov/openFEC#4382
- [x] fecgov/fec-eregs#632
- [x] fecgov/fec-cms#3224
- [x] fecgov/openFEC#4792
- [x] fecgov/fec-cms#4384
- [x] fecgov/fec-cms#4538
- [x] fecgov/fec-cms#4026
- [x] fecgov/fec-cms#4494
- [x] fecgov/fec-cms#4362
- [x] fecgov/fec-cms#4040
- [x] fecgov/fec-cms#3070
- [x] fecgov/openFEC#4769
- [x] fecgov/fec-cms#4390
- [x] fecgov/openFEC#4766
- [x] fecgov/fec-eregs#568
- [x] fecgov/openFEC#4768
- [x] fecgov/fec-proxy#200
- [x] fecgov/fec-cms#4266
- [x] fecgov/openFEC#4393
- [x] fecgov/fec-cms#4281
- [x] fecgov/fec-cms#4105
- [x] fecgov/fec-eregs#558
- [x] fecgov/fec-eregs#541
- [x] fecgov/fec-eregs#556
- [x] fecgov/fec-eregs#555
- [x] fecgov/fec-cms#4043
- [x] fecgov/fec-eregs#552
- [x] fecgov/fec-eregs#554
- [x] fecgov/fec-eregs#553
- [x] fecgov/openFEC#4626
- [x] fecgov/fec-cms#4220
- [x] fecgov/openFEC#4698
- [x] fecgov/openFEC#4546
- [x] fecgov/fec-eregs#538
- [x] fecgov/fec-proxy#169
- [x] fecgov/openFEC#4697
- [x] fecgov/fec-cms#3836
- [x] fecgov/openFEC#4687
- [x] fecgov/openFEC#4686
- [x] fecgov/openFEC#4682
- [x] fecgov/openFEC#4681
- [x] fecgov/fec-cms#4126
- [x] fecgov/fec-cms#4106
- [x] fecgov/openFEC#4653
- [x] fecgov/fec-cms#4152
- [x] fecgov/openFEC#4524
- [x] fecgov/openFEC#4635
- [x] fecgov/openFEC#4492
- [x] fecgov/fec-cms#3978
- [x] fecgov/fec-cms#4065
- [x] fecgov/openFEC#4646
- [x] fecgov/openFEC#4588
- [x] fecgov/fec-eregs#522
- [x] fecgov/openFEC#4425
- [x] fecgov/fec-eregs#526
- [x] fecgov/fec-cms#4027
- [x] fecgov/fec-cms#3963
- [x] fecgov/openFEC#4611
- [x] fecgov/openFEC#4560
- [x] fecgov/openFEC#4318
- [x] fecgov/openFEC#4584
- [x] fecgov/openFEC#4597
- [x] fecgov/openFEC#4585
- [x] fecgov/openFEC#4502
- [x] fecgov/openFEC#4203
- [x] fecgov/fec-eregs#520
- [x] fecgov/openFEC#4538
- [x] fecgov/openFEC#4557
- [x] fecgov/openFEC#4545
- [x] fecgov/fec-eregs#518
- [x] fecgov/fec-eregs#519
- [x] fecgov/openFEC#4543
- [x] fecgov/openFEC#4525
- [x] fecgov/fec-cms#3718
- [x] fecgov/openFEC#4468
- [x] fecgov/fec-cms#3927
- [x] fecgov/fec-cms#3757
- [x] fecgov/fec-cms#3919
- [x] fecgov/openFEC#4381
- [x] fecgov/fec-cms#3116
- [x] fecgov/openFEC#4444
- [x] fecgov/fec-cms#3740
- [x] fecgov/openFEC#4337
- [x] fecgov/fec-cms#3838
- [x] fecgov/fec-cms#3791
- [x] fecgov/openFEC#3408
- [x] fecgov/fec-eregs#499
- [x] fecgov/openFEC#4411
- [x] fecgov/fec-cms#3226
- [x] fecgov/openFEC#4402
- [x] fecgov/openFEC#4332
- [x] fecgov/openFEC#4335
- [x] fecgov/fec-cms#3779
- [x] fecgov/fec-cms#3790
- [x] fecgov/fec-cms#3772
- [x] fecgov/fec-cms#3775
- [x] fecgov/fec-cms#3747
- [x] fecgov/openFEC#4326
- [x] fecgov/openFEC#4358
- [x] fecgov/fec-cms#3717
- [x] fecgov/fec-eregs#492
- [x] fecgov/fec-eregs#487
- [x] fecgov/openFEC#4327
- [x] fecgov/openFEC#4295
- [x] fecgov/fec-cms#3739
- [x] fecgov/openFEC#4361
- [x] fecgov/fec-cms#3698
- [x] fecgov/fec-cms#3742
- [x] fecgov/openFEC#4302
- [x] fecgov/openFEC#4343
- [x] fecgov/fec-cms#3694
- [x] fecgov/fec-cms#3729
- [x] fecgov/fec-eregs#485
- [x] fecgov/openFEC#4282
- [x] fecgov/openFEC#4314
- [x] fecgov/fec-cms#3703
- [x] fecgov/fec-cms#3699
- [x] fecgov/openFEC#4293
- [x] fecgov/openFEC#4264
- [x] fecgov/openFEC#4210
- [x] fecgov/openFEC#4252
- [x] fecgov/openFEC#4251
- [x] fecgov/openFEC#4250
- [x] fecgov/openFEC#4230
- [x] fecgov/openFEC#4229
- [x] fecgov/fec-cms#3422
- [x] fecgov/fec-cms#3396
- [x] fecgov/fec-cms#3478
- [x] fecgov/fec-cms#3482
- [x] fecgov/openFEC#4126
- [x] fecgov/openFEC#4137
- [x] fecgov/openFEC#4093
- [x] fecgov/openFEC#4045
- [x] fecgov/openFEC#4131
- [x] fecgov/fec-cms#3426
- [x] fecgov/openFEC#3979
- [x] fecgov/fec-cms#3198
- [x] fecgov/fec-cms#3366
- [x] fecgov/openFEC#4038
- [x] fecgov/openFEC#4059
- [x] fecgov/fec-eregs#458
- [x] fecgov/fec-cms#3228
- [x] fecgov/openFEC#4052
- [x] fecgov/openFEC#4051
- [x] fecgov/openFEC#3587
- [x] fecgov/openFEC#3981
- [x] fecgov/openFEC#3980
- [x] fecgov/openFEC#3982
- [x] fecgov/openFEC#3983
- [x] fecgov/fec-cms#2991
- [x] fecgov/openFEC#3952
- [x] fecgov/fec-cms#3191
- [x] fecgov/openFEC#3990
- [x] fecgov/fec-cms#3222
- [x] fecgov/openFEC#4007
- [x] fecgov/openFEC#3989
- [x] fecgov/fec-cms#3113
- [x] fecgov/fec-cms#3127
- [x] fecgov/openFEC#3776
- [x] fecgov/openFEC#3977
- [x] fecgov/fec-cms#3189
- [x] fecgov/fec-eregs#457
- [x] fecgov/openFEC#3940
- [x] fecgov/openFEC#3761
- [x] fecgov/openFEC#3924
- [x] fecgov/fec-cms#3045
- [x] fecgov/openFEC#3876
- [x] fecgov/fec-cms#3069
- [x] fecgov/openFEC#3903
- [x] fecgov/openFEC#3896
- [x] fecgov/fec-cms#2989
- [x] fecgov/fec-cms#3109
- [x] fecgov/openFEC#3897
- [x] fecgov/fec-cms#2944
- [x] fecgov/fec-cms#3023
- [x] fecgov/fec-cms#3022
- [x] fecgov/openFEC#3856
- [x] fecgov/fec-cms#3021
- [x] fecgov/openFEC#3855
- [x] fecgov/openFEC#3854
- [x] fecgov/fec-cms#3044
- [x] fecgov/openFEC#3840
- [x] fecgov/openFEC#3859
- [x] fecgov/openFEC#3839
- [x] fecgov/openFEC#3612
- [x] fecgov/openFEC#3838
- [x] fecgov/fec-cms#2821
- [x] fecgov/fec-cms#2901
- [x] fecgov/fec-cms#2792
- [x] fecgov/fec-cms#2984
- [x] fecgov/openFEC#3798
- [x] fecgov/fec-cms#2910
- [x] fecgov/openFEC#3806
- [x] fecgov/openFEC#3799
- [x] fecgov/openFEC#3396
- [x] fecgov/openFEC#3757
- [x] fecgov/fec-cms#2822
- [x] fecgov/openFEC#3769
- [x] fecgov/fec-cms#2823
- [x] fecgov/openFEC#3636
- [x] fecgov/openFEC#3642
- [x] fecgov/openFEC#3780
- [x] fecgov/fec-cms#2691
- [x] fecgov/fec-eregs#439
- [x] fecgov/openFEC#3618
- [x] fecgov/openFEC#3657
- [x] fecgov/openFEC#3651
- [x] fecgov/openFEC#3639
- [x] fecgov/openFEC#3614
- [x] fecgov/openFEC#3656
- [x] fecgov/openFEC#3664
- [x] fecgov/openFEC#3654
- [x] fecgov/openFEC#3608
- [x] fecgov/openFEC#3547
- [x] fecgov/openFEC#3050
- [x] fecgov/fec-cms#2743
- [x] fecgov/openFEC#3630
- [x] fecgov/fec-cms#2745
- [x] fecgov/openFEC#3586
- [x] fecgov/fec-cms#2735
- [x] fecgov/openFEC#3589
- [x] fecgov/openFEC#3607
- [x] fecgov/fec-cms#2682
- [x] fecgov/fec-cms#2681
- [x] fecgov/fec-cms#2654
- [x] fecgov/openFEC#3566
- [x] fecgov/fec-cms#2339
- [x] fecgov/fec-cms#2305
- [x] fecgov/openFEC#2942
- [x] fecgov/openFEC#3046
- [x] fecgov/openFEC#2939
- [x] fecgov/openFEC#2989
- [x] fecgov/openFEC#2986
- [x] fecgov/fec-cms#1759
- [x] fecgov/openFEC#2978
- [x] fecgov/openFEC#2987
- [x] fecgov/openFEC#2913
- [x] fecgov/fec-cms#1760
- [x] fecgov/fec-cms#1691
- [x] fecgov/openFEC#2897
- [x] fecgov/fec-cms#1761
- [x] fecgov/openFEC#2914
- [x] fecgov/openFEC#2940
- [x] fecgov/openFEC#2941
- [x] fecgov/openFEC#2749
- [x] fecgov/openFEC#2873
- [x] fecgov/fec-cms#1741
- [x] fecgov/fec-accounts#176
- [x] fecgov/fec-accounts#177
- [x] fecgov/fec-accounts#178
- [x] fecgov/fec-accounts#198
- [x] fecgov/fec-accounts#201
- [x] fecgov/fec-accounts#212
- [x] fecgov/fec-accounts#213
- [x] fecgov/fec-accounts#216
- [x] fecgov/fec-accounts#225
- [x] fecgov/fec-accounts#241
- [x] fecgov/fec-accounts#248
- [x] fecgov/fec-accounts#250
- [x] fecgov/fec-accounts#264
- [x] fecgov/fec-accounts#272
- [x] fecgov/fec-accounts#273
- [x] fecgov/fec-accounts#274
- [x] fecgov/fec-accounts#281
- [x] fecgov/fec-accounts#283
- [x] fecgov/fec-accounts#289
- [x] fecgov/fec-accounts#290
- [x] fecgov/fec-accounts#292
- [x] fecgov/fec-accounts#293
- [x] fecgov/fec-accounts#294
- [x] fecgov/fec-accounts#295
- [x] fecgov/fec-accounts#296
- [x] fecgov/fec-accounts#297
- [x] fecgov/fec-accounts#299
- [x] fecgov/fec-accounts#302
- [x] fecgov/fec-accounts#303
- [x] fecgov/fec-accounts#309
- [x] fecgov/fec-accounts#331
- [x] fecgov/fec-accounts#342
- [x] fecgov/fec-accounts#354
- [x] fecgov/fec-accounts#376
- [x] fecgov/fec-accounts#401
- [x] fecgov/fec-accounts#417
- [x] fecgov/fec-accounts#421
- [x] fecgov/fecnet#297
