### ISSUE TITLE
Epic: Content

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#138]
**What we’re after:** The Content team will focus on improving content for users by collaborating with other teams and keeping information current, accurate, and relevant, with a focus on: 

- Assisting in making the E&Js searchable  
- Updating site pages for routine work 
- Updates to reporting examples 

**Why we’re after it:** To better serve the public and ensure the information on the website is accurate and current.

## Epics 
- [ ] fecgov/fec-epics#189
- [ ] fecgov/fec-epics#186
- [ ] fecgov/fec-epics#201
- [x] fecgov/fec-epics#193
- [ ] fecgov/fec-epics#189
- [ ] fecgov/fec-epics#186
- [ ] fecgov/fec-epics#201
- [x] fecgov/fec-epics#193
- [x] fecgov/fec-epics#184

## Tickets
- [x] fecgov/fec-cms#4772
- [ ] fecgov/fec-cms#4162
- [x] fecgov/fec-cms#3842
- [ ] fecgov/fec-cms#4128
- [ ] fecgov/fec-cms#4367
- [ ] fecgov/fec-cms#4406
- [ ] fecgov/fec-cms#4408
- [ ] fecgov/fec-cms#4409
- [ ] fecgov/fec-cms#4506
- [ ] fecgov/fec-cms#4607
- [ ] fecgov/fec-cms#3885
- [ ] fecgov/fec-cms#5620
- [x] fecgov/fec-cms#6066
- [ ] fecgov/fec-cms#6060
- [ ] fecgov/fec-cms#6061
- [x] fecgov/fec-cms#5955
- [x] fecgov/fec-cms#5859
- [ ] fecgov/fec-cms#5046
- [x] fecgov/fec-cms#5783
- [ ] fecgov/fec-cms#4809
- [ ] fecgov/fec-cms#4842
- [x] fecgov/fec-cms#4481
- [x] fecgov/fec-cms#6129
- [ ] fecgov/fec-cms#6063
- [ ] fecgov/fec-cms#6062
- [ ] fecgov/fec-cms#6093
- [x] fecgov/fec-cms#6052
- [x] fecgov/fec-cms#6077
- [ ] fecgov/fec-cms#5047
- [ ] fecgov/fec-cms#3385
- [ ] fecgov/fec-cms#5538
- [ ] fecgov/fec-cms#4684
- [ ] fecgov/fec-cms#3713
- [ ] fecgov/fec-cms#3817
- [x] fecgov/fec-cms#4386
- [ ] fecgov/fec-cms#4407
- [x] fecgov/fec-cms#5199
- [ ] fecgov/fec-proxy#230
- [ ] fecgov/fec-cms#2753
- [ ] fecgov/fec-cms#3472
- [x] fecgov/fec-cms#3655
- [x] fecgov/fec-cms#3850
- [x] fecgov/fec-cms#3879
- [x] fecgov/fec-cms#3769
- [ ] fecgov/fec-cms#3866
- [x] fecgov/fec-cms#6086
- [x] fecgov/fec-cms#6065
- [x] fecgov/fec-cms#6106
- [x] fecgov/fec-cms#6069
- [x] fecgov/fec-cms#6047
- [x] fecgov/fec-cms#5942
- [x] fecgov/fec-cms#5940
- [x] fecgov/fec-cms#6022
- [x] fecgov/fec-cms#6039
- [x] fecgov/fec-cms#5776
- [x] fecgov/fec-cms#5777
- [x] fecgov/fec-cms#6040
- [x] fecgov/fec-cms#6028
- [x] fecgov/fec-cms#6038
- [x] fecgov/fec-cms#5997
- [x] fecgov/fec-cms#5998
- [x] fecgov/fec-cms#5751
- [x] fecgov/fec-cms#6004
- [x] fecgov/fec-cms#6009
- [x] fecgov/fec-cms#5991
- [x] fecgov/fec-cms#5965
- [x] fecgov/fec-cms#5976
- [x] fecgov/fec-cms#5973
- [x] fecgov/fec-cms#5941
- [x] fecgov/fec-cms#5968
- [x] fecgov/fec-cms#5939
- [x] fecgov/fec-cms#5911
- [x] fecgov/fec-eregs#784
- [x] fecgov/fec-cms#4151
- [x] fecgov/fec-cms#5926
- [x] fecgov/fec-cms#5899
- [x] fecgov/fec-cms#5846
- [x] fecgov/fec-cms#5916
- [x] fecgov/fec-cms#5915
- [x] fecgov/fec-cms#5793
- [x] fecgov/fec-proxy#365
- [x] fecgov/fec-cms#5856
- [x] fecgov/fec-cms#5898
- [x] fecgov/fec-cms#5840
- [x] fecgov/fec-cms#5803
- [x] fecgov/fec-cms#5831
- [x] fecgov/fec-cms#5830
- [x] fecgov/fec-cms#5795
- [x] fecgov/fec-cms#5799
- [x] fecgov/fec-cms#5771
- [x] fecgov/fec-cms#5731
- [x] fecgov/fec-cms#3280
- [x] fecgov/fec-cms#5730
- [x] fecgov/fec-cms#5743
- [x] fecgov/fec-cms#5729
- [x] fecgov/fec-cms#5712
- [x] fecgov/fec-cms#5686
- [x] fecgov/fec-cms#5640
- [x] fecgov/fec-cms#5696
- [x] fecgov/fec-cms#5678
- [x] fecgov/fec-cms#5624
- [x] fecgov/fec-cms#5114
- [x] fecgov/fec-cms#5638
- [x] fecgov/fec-cms#5553
- [x] fecgov/fec-cms#5630
- [x] fecgov/fec-cms#5565
- [x] fecgov/fec-cms#5618
- [x] fecgov/fec-cms#5552
- [x] fecgov/fec-proxy#315
- [x] fecgov/fec-cms#4893
- [x] fecgov/fec-cms#5526
- [x] fecgov/fec-cms#5551
- [x] fecgov/fec-cms#5546
- [x] fecgov/fec-cms#5372
- [x] fecgov/fec-cms#5527
- [x] fecgov/fec-cms#5529
- [x] fecgov/fec-proxy#337
- [x] fecgov/fec-cms#5518
- [x] fecgov/fec-cms#5464
- [x] fecgov/fec-cms#5312
- [x] fecgov/fec-cms#5524
- [x] fecgov/fec-cms#5479
- [x] fecgov/fec-cms#5510
- [x] fecgov/fec-cms#5223
- [x] fecgov/fec-cms#5311
- [x] fecgov/fec-cms#5505
- [x] fecgov/fec-cms#5393
- [x] fecgov/fec-cms#5461
- [x] fecgov/fec-cms#5392
- [x] fecgov/fec-cms#3924
- [x] fecgov/fec-cms#5315
- [x] fecgov/fec-cms#5424
- [x] fecgov/fec-cms#5427
- [x] fecgov/fec-cms#5428
- [x] fecgov/fec-cms#5405
- [x] fecgov/fec-cms#5389
- [x] fecgov/fec-cms#5425
- [x] fecgov/fec-cms#5406
- [x] fecgov/fec-cms#5365
- [x] fecgov/fec-cms#5322
- [x] fecgov/fec-cms#5171
- [x] fecgov/fec-cms#5306
- [x] fecgov/fec-cms#5273
- [x] fecgov/fec-cms#5298
- [x] fecgov/fec-cms#4924
- [x] fecgov/fec-cms#5242
- [x] fecgov/fec-cms#5275
- [x] fecgov/fec-cms#5212
- [x] fecgov/fec-cms#5267
- [x] fecgov/fec-cms#5195
- [x] fecgov/fec-cms#5230
- [x] fecgov/fec-cms#5241
- [x] fecgov/fec-cms#5135
- [x] fecgov/fec-cms#5154
- [x] fecgov/fec-cms#5167
- [x] fecgov/fec-cms#5149
- [x] fecgov/fec-cms#4335
- [x] fecgov/fec-cms#5062
- [x] fecgov/fec-cms#5119
- [x] fecgov/fec-cms#5092
- [x] fecgov/fec-cms#5051
- [x] fecgov/fec-cms#5100
- [x] fecgov/fec-cms#5082
- [x] fecgov/fec-proxy#301
- [x] fecgov/fec-cms#4777
- [x] fecgov/fec-cms#5056
- [x] fecgov/fec-cms#5048
- [x] fecgov/fec-cms#4950
- [x] fecgov/fec-cms#5037
- [x] fecgov/fec-cms#5036
- [x] fecgov/fec-cms#5067
- [x] fecgov/fec-cms#5025
- [x] fecgov/fec-cms#5066
- [x] fecgov/fec-cms#5042
- [x] fecgov/fec-cms#4954
- [x] fecgov/fec-cms#5011
- [x] fecgov/fec-cms#5012
- [x] fecgov/fec-cms#5003
- [x] fecgov/fec-cms#4969
- [x] fecgov/fec-cms#4818
- [x] fecgov/fec-cms#5038
- [x] fecgov/fec-cms#4880
- [x] fecgov/fec-cms#5023
- [x] fecgov/fec-cms#4985
- [x] fecgov/fec-cms#4997
- [x] fecgov/fec-cms#4770
- [x] fecgov/fec-cms#4882
- [x] fecgov/fec-cms#4885
- [x] fecgov/fec-cms#4972
- [x] fecgov/fec-cms#4991
- [x] fecgov/fec-cms#4926
- [x] fecgov/fec-cms#4977
- [x] fecgov/fec-cms#4917
- [x] fecgov/fec-cms#4945
- [x] fecgov/fec-cms#4957
- [x] fecgov/fec-cms#4959
- [x] fecgov/fec-cms#4966
- [x] fecgov/fec-cms#4947
- [x] fecgov/fec-cms#4944
- [x] fecgov/fec-cms#4644
- [x] fecgov/fec-cms#4960
- [x] fecgov/fec-cms#4946
- [x] fecgov/fec-cms#4918
- [x] fecgov/fec-cms#4938
- [x] fecgov/fec-cms#4887
- [x] fecgov/fec-cms#4896
- [x] fecgov/fec-cms#4901
- [x] fecgov/fec-cms#4865
- [x] fecgov/fec-cms#4825
- [x] fecgov/fec-cms#4888
- [x] fecgov/fec-cms#4872
- [x] fecgov/fec-cms#4844
- [x] fecgov/fec-cms#4595
- [x] fecgov/fec-cms#4613
- [x] fecgov/fec-cms#4479
- [x] fecgov/fec-cms#3404
- [x] fecgov/fec-cms#4832
- [x] fecgov/fec-cms#4866
- [x] fecgov/fec-cms#4806
- [x] fecgov/fec-cms#4813
- [x] fecgov/fec-cms#4642
- [x] fecgov/fec-cms#4830
- [x] fecgov/fec-cms#4833
- [x] fecgov/fec-cms#4581
- [x] fecgov/fec-cms#4641
- [x] fecgov/fec-cms#4771
- [x] fecgov/fec-cms#4640
- [x] fecgov/fec-cms#4760
- [x] fecgov/fec-cms#4739
- [x] fecgov/fec-cms#4794
- [x] fecgov/fec-cms#4480
- [x] fecgov/fec-cms#4738
- [x] fecgov/fec-cms#3498
- [x] fecgov/fec-cms#4639
- [x] fecgov/fec-cms#4711
- [x] fecgov/fec-cms#4677
- [x] fecgov/fec-cms#4597
- [x] fecgov/openFEC#4848
- [x] fecgov/fec-cms#4312
- [x] fecgov/fec-cms#3934
- [x] fecgov/fec-cms#4596
- [x] fecgov/fec-cms#4712
- [x] fecgov/fec-cms#4025
- [x] fecgov/fec-cms#4628
- [x] fecgov/fec-cms#4347
- [x] fecgov/fec-cms#4678
- [x] fecgov/fec-cms#4624
- [x] fecgov/fec-cms#4541
- [x] fecgov/fec-cms#4346
- [x] fecgov/fec-cms#4588
- [x] fecgov/fec-cms#4345
- [x] fecgov/fec-cms#3350
- [x] fecgov/fec-cms#4565
- [x] fecgov/fec-cms#4503
- [x] fecgov/fec-cms#4484
- [x] fecgov/fec-cms#4344
- [x] fecgov/fec-cms#4492
- [x] fecgov/fec-cms#4343
- [x] fecgov/fec-cms#4469
- [x] fecgov/fec-cms#4331
- [x] fecgov/fec-cms#3773
- [x] fecgov/fec-cms#4349
- [x] fecgov/fec-cms#4342
- [x] fecgov/fec-cms#4471
- [x] fecgov/fec-cms#3755
- [x] fecgov/fec-cms#4447
- [x] fecgov/fec-cms#4385
- [x] fecgov/fec-cms#4468
- [x] fecgov/fec-cms#4364
- [x] fecgov/fec-cms#3936
- [x] fecgov/fec-cms#4423
- [x] fecgov/fec-cms#4223
- [x] fecgov/fec-cms#4341
- [x] fecgov/fec-cms#3837
- [x] fecgov/fec-cms#3798
- [x] fecgov/fec-cms#4300
- [x] fecgov/fec-cms#4298
- [x] fecgov/fec-cms#4020
- [x] fecgov/fec-cms#4237
- [x] fecgov/fec-cms#4274
- [x] fecgov/fec-cms#3841
- [x] fecgov/fec-cms#4301
- [x] fecgov/fec-cms#4051
- [x] fecgov/fec-cms#3923
- [x] fecgov/fec-cms#4047
- [x] fecgov/fec-cms#4218
- [x] fecgov/fec-cms#4295
- [x] fecgov/fec-cms#4294
- [x] fecgov/fec-cms#4050
- [x] fecgov/fec-cms#4276
- [x] fecgov/fec-cms#4268
- [x] fecgov/fec-cms#4271
- [x] fecgov/fec-cms#3937
- [x] fecgov/fec-cms#3938
- [x] fecgov/fec-cms#3849
- [x] fecgov/fec-cms#4155
- [x] fecgov/fec-cms#4130
- [x] fecgov/fec-cms#4109
- [x] fecgov/fec-cms#3818
- [x] fecgov/fec-cms#4080
- [x] fecgov/fec-cms#3884
- [x] fecgov/fec-cms#3118
- [x] fecgov/fec-cms#3770
- [x] fecgov/fec-cms#4017
- [x] fecgov/fec-cms#4009
- [x] fecgov/fec-cms#3794
- [x] fecgov/fec-cms#4007
- [x] fecgov/fec-cms#3541
- [x] fecgov/fec-cms#3894
- [x] fecgov/fec-cms#3746
- [x] fecgov/fec-cms#3901
- [x] fecgov/fec-cms#3660
- [x] fecgov/fec-cms#3822
- [x] fecgov/fec-cms#3876
- [x] fecgov/fec-cms#3913
- [x] fecgov/fec-cms#3916
- [x] fecgov/fec-cms#3935
- [x] fecgov/fec-cms#3767
- [x] fecgov/fec-cms#3860
- [x] fecgov/fec-cms#3379
- [x] fecgov/fec-cms#3912
- [x] fecgov/fec-cms#3659
- [x] fecgov/fec-cms#3893
- [x] fecgov/fec-cms#3861
- [x] fecgov/fec-cms#3877
- [x] fecgov/fec-cms#3801
- [x] fecgov/fec-cms#3756
- [x] fecgov/fec-cms#3868
- [x] fecgov/fec-cms#3785
- [x] fecgov/fec-cms#3840
- [x] fecgov/fec-cms#3854
- [x] fecgov/fec-cms#3843
- [x] fecgov/fec-cms#3827
- [x] fecgov/fec-cms#3821
- [x] fecgov/fec-cms#3279
- [x] fecgov/fec-cms#3749
- [x] fecgov/fec-cms#3753
- [x] fecgov/fec-cms#3715
- [x] fecgov/fec-cms#3609
- [x] fecgov/fec-cms#3451
- [x] fecgov/fec-cms#3736
- [x] fecgov/fec-cms#3665
- [x] fecgov/fec-cms#3748
- [x] fecgov/fec-cms#3731
- [x] fecgov/fec-cms#3727
- [x] fecgov/fec-cms#3724
- [x] fecgov/fec-cms#3677
- [x] fecgov/fec-cms#3667
- [x] fecgov/fec-cms#3249
- [x] fecgov/fec-cms#3608
- [x] fecgov/fec-cms#3661
- [x] fecgov/fec-cms#3676
- [x] fecgov/fec-cms#3345
- [x] fecgov/fec-cms#3550
- [x] fecgov/fec-cms#3603
- [x] fecgov/fec-cms#3546
- [x] fecgov/fec-cms#3553
- [x] fecgov/fec-cms#3359
- [x] fecgov/fec-cms#3571
- [x] fecgov/fec-cms#3342
- [x] fecgov/fec-cms#3340
- [x] fecgov/fec-cms#3341
- [x] fecgov/fec-cms#3420
- [x] fecgov/fec-cms#3539
- [x] fecgov/fec-cms#3376
- [x] fecgov/fec-cms#3450
- [x] fecgov/fec-cms#3425
- [x] fecgov/fec-cms#3403
- [x] fecgov/fec-cms#3383
- [x] fecgov/fec-cms#3352
- [x] fecgov/fec-cms#3406
- [x] fecgov/fec-cms#3357
- [x] fecgov/fec-cms#3433
- [x] fecgov/fec-cms#3443
- [x] fecgov/fec-cms#3221
- [x] fecgov/fec-cms#3381
- [x] fecgov/fec-cms#3418
- [x] fecgov/fec-cms#3387
- [x] fecgov/fec-cms#3419
- [x] fecgov/fec-cms#3205
- [x] fecgov/fec-cms#3416
- [x] fecgov/fec-cms#3295
- [x] fecgov/fec-cms#3391
- [x] fecgov/fec-cms#3399
- [x] fecgov/fec-cms#3374
- [x] fecgov/fec-cms#3398
- [x] fecgov/fec-cms#3397
- [x] fecgov/fec-cms#3400
- [x] fecgov/fec-cms#3384
- [x] fecgov/fec-cms#3243
- [x] fecgov/fec-cms#3316
- [x] fecgov/fec-cms#3283
- [x] fecgov/fec-cms#3251
- [x] fecgov/fec-cms#3240
- [x] fecgov/fec-cms#3242
- [x] fecgov/fec-cms#3241
- [x] fecgov/fec-cms#3244
- [x] fecgov/fec-cms#3291
- [x] fecgov/fec-cms#3179
- [x] fecgov/fec-cms#3358
- [x] fecgov/fec-cms#2974
- [x] fecgov/fec-cms#3209
- [x] fecgov/fec-cms#3219
- [x] fecgov/fec-cms#3212
- [x] fecgov/fec-cms#3317
- [x] fecgov/fec-cms#2856
- [x] fecgov/fec-cms#3301
- [x] fecgov/fec-cms#3149
- [x] fecgov/fec-cms#3274
- [x] fecgov/fec-cms#3263
- [x] fecgov/fec-cms#3230
- [x] fecgov/fec-cms#3117
- [x] fecgov/fec-cms#3173
- [x] fecgov/fec-cms#2991
- [x] fecgov/fec-cms#3185
- [x] fecgov/fec-cms#3072
- [x] fecgov/fec-cms#3017
- [x] fecgov/fec-cms#3252
- [x] fecgov/fec-cms#3046
- [x] fecgov/fec-cms#3038
- [x] fecgov/fec-cms#3175
- [x] fecgov/fec-cms#2482
- [x] fecgov/fec-cms#3016
- [x] fecgov/fec-cms#3178
- [x] fecgov/fec-cms#3169
- [x] fecgov/fec-cms#3148
- [x] fecgov/fec-cms#2883
- [x] fecgov/fec-cms#3176
- [x] fecgov/fec-cms#3071
- [x] fecgov/fec-cms#3122
- [x] fecgov/fec-cms#3129
- [x] fecgov/fec-cms#3090
- [x] fecgov/fec-cms#3065
- [x] fecgov/fec-cms#3005
- [x] fecgov/fec-cms#3137
- [x] fecgov/fec-cms#3128
- [x] fecgov/fec-cms#3103
- [x] fecgov/fec-cms#3097
- [x] fecgov/fec-cms#3066
- [x] fecgov/fec-cms#3064
- [x] fecgov/fec-cms#3089
- [x] fecgov/fec-cms#3032
- [x] fecgov/fec-cms#3077
- [x] fecgov/fec-cms#2996
- [x] fecgov/fec-cms#2997
- [x] fecgov/fec-cms#2827
- [x] fecgov/fec-cms#3063
- [x] fecgov/fec-cms#3033
- [x] fecgov/fec-cms#2877
- [x] fecgov/fec-cms#2825
- [x] fecgov/fec-cms#2824
- [x] fecgov/fec-cms#2882
- [x] fecgov/fec-cms#3034
- [x] fecgov/fec-cms#3035
- [x] fecgov/fec-cms#2881
- [x] fecgov/fec-cms#2922
- [x] fecgov/fec-cms#2896
- [x] fecgov/fec-cms#2860
- [x] fecgov/fec-cms#3000
- [x] fecgov/fec-cms#2920
- [x] fecgov/fec-cms#2999
- [x] fecgov/fec-cms#2994
- [x] fecgov/fec-cms#2995
- [x] fecgov/fec-cms#2949
- [x] fecgov/fec-cms#2785
- [x] fecgov/fec-cms#2921
- [x] fecgov/fec-cms#2880
- [x] fecgov/fec-cms#2879
- [x] fecgov/fec-cms#2945
- [x] fecgov/fec-cms#2946
- [x] fecgov/fec-cms#2889
- [x] fecgov/fec-cms#2891
- [x] fecgov/fec-cms#2878
- [x] fecgov/fec-cms#2893
- [x] fecgov/fec-cms#2890
- [x] fecgov/fec-cms#2876
- [x] fecgov/fec-cms#2837
- [x] fecgov/fec-cms#2747
- [x] fecgov/fec-cms#2774
- [x] fecgov/fec-cms#2807
- [x] fecgov/fec-cms#2806
- [x] fecgov/fec-cms#2861
- [x] fecgov/fec-cms#2666
- [x] fecgov/fec-cms#2800
- [x] fecgov/fec-cms#2776
- [x] fecgov/fec-cms#2786
- [x] fecgov/fec-cms#2769
- [x] fecgov/fec-cms#2796
- [x] fecgov/fec-cms#2712
- [x] fecgov/fec-cms#2813
- [x] fecgov/fec-cms#2770
- [x] fecgov/fec-cms#2771
- [x] fecgov/fec-cms#2740
- [x] fecgov/fec-cms#2689
- [x] fecgov/fec-cms#2697
- [x] fecgov/fec-cms#2738
- [x] fecgov/fec-cms#2676
- [x] fecgov/fec-cms#2699
- [x] fecgov/fec-cms#2698
- [x] fecgov/fec-cms#2722
- [x] fecgov/fec-cms#2617
- [x] fecgov/fec-cms#2600
- [x] fecgov/fec-cms#2512
- [x] fecgov/fec-cms#2670
- [x] fecgov/fec-cms#2638
- [x] fecgov/fec-cms#2597
- [x] fecgov/fec-cms#2598
- [x] fecgov/fec-cms#2222
- [x] fecgov/fec-cms#2248
- [x] fecgov/fec-cms#2568
- [x] fecgov/fec-cms#2572
- [x] fecgov/fec-cms#2301
- [x] fecgov/fec-cms#2534
- [x] fecgov/fec-cms#2536
- [x] fecgov/fec-cms#2225
- [x] fecgov/fec-cms#2425
- [x] fecgov/fec-cms#2394
- [x] fecgov/fec-cms#2350
- [x] fecgov/fec-cms#2426
- [x] fecgov/fec-cms#2360
- [x] fecgov/fec-cms#2407
- [x] fecgov/fec-cms#2486
- [x] fecgov/fec-cms#2453
- [x] fecgov/fec-cms#2241
- [x] fecgov/fec-cms#2428
- [x] fecgov/fec-cms#2396
- [x] fecgov/fec-cms#2402
- [x] fecgov/fec-cms#2400
- [x] fecgov/fec-cms#2149
- [x] fecgov/fec-cms#2186
- [x] fecgov/fec-cms#2319
- [x] fecgov/fec-cms#1787
- [x] fecgov/fec-cms#2305
- [x] fecgov/fec-cms#2293
- [x] fecgov/fec-cms#1785
