### ISSUE TITLE
Epic: Legal

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#139]
- Administrative fines (API)
- Alternative dispute resolution (API)
- Migrate Explanations and Justifications to fec.gov

## Epics
- [ ] fecgov/fec-epics#221
- [ ] fecgov/fec-epics#220
- [ ] fecgov/fec-epics#222
- [x] fecgov/fec-epics#181
- [x] fecgov/fec-epics#183

## Tickets
- [ ] fecgov/fec-cms#4539
- [ ] fecgov/fec-cms#3335
- [ ] fecgov/fec-cms#4045
- [ ] fecgov/fec-cms#4044
- [ ] fecgov/fec-cms#5340
- [ ] fecgov/fec-cms#5371
- [x] fecgov/fec-cms#5366
- [x] fecgov/fec-cms#6128
- [x] fecgov/fec-cms#3555
- [ ] fecgov/fec-eregs#446
- [ ] fecgov/fec-eregs#393
- [ ] fecgov/fec-eregs#397
- [x] fecgov/fec-cms#6125
- [x] fecgov/fec-cms#6096
- [x] fecgov/fec-proxy#392
- [x] fecgov/fec-cms#6037
- [x] fecgov/fec-cms#6036
- [x] fecgov/fec-cms#6042
- [x] fecgov/fec-cms#5951
- [x] fecgov/fec-cms#5985
- [x] fecgov/fec-cms#5861
- [x] fecgov/fec-eregs#790
- [x] fecgov/fec-cms#5891
- [x] fecgov/fec-cms#5882
- [x] fecgov/fec-cms#5803
- [x] fecgov/fec-cms#5853
- [x] fecgov/fec-cms#5818
- [x] fecgov/fec-cms#5752
- [x] fecgov/fec-cms#5595
- [x] fecgov/fec-cms#5748
- [x] fecgov/fec-cms#5724
- [x] fecgov/fec-cms#5639
- [x] fecgov/fec-cms#5709
- [x] fecgov/openFEC#4399
- [x] fecgov/fec-cms#5609
- [x] fecgov/fec-cms#5557
- [x] fecgov/fec-cms#5571
- [x] fecgov/fec-proxy#341
- [x] fecgov/fec-cms#5507
- [x] fecgov/fec-cms#5506
- [x] fecgov/fec-proxy#325
- [x] fecgov/fec-cms#5525
- [x] fecgov/fec-cms#5494
- [x] fecgov/fec-cms#5427
- [x] fecgov/fec-proxy#334
- [x] fecgov/fec-cms#5383
- [x] fecgov/fec-cms#5428
- [x] fecgov/openFEC#5238
- [x] fecgov/fec-cms#4834
- [x] fecgov/fec-eregs#704
- [x] fecgov/fec-eregs#714
- [x] fecgov/fec-cms#5402
- [x] fecgov/fec-cms#5373
- [x] fecgov/fec-cms#5187
- [x] fecgov/fec-cms#5186
- [x] fecgov/fec-cms#5185
- [x] fecgov/fec-cms#5085
- [x] fecgov/openFEC#4971
- [x] fecgov/openFEC#5013
- [x] fecgov/openFEC#4976
- [x] fecgov/fec-eregs#449
- [x] fecgov/fec-cms#4998
- [x] fecgov/fec-eregs#540
- [x] fecgov/fec-cms#4764
- [x] fecgov/fec-cms#4808
- [x] fecgov/fec-cms#4835
- [x] fecgov/fec-eregs#580
- [x] fecgov/fec-proxy#281
- [x] fecgov/fec-cms#4510
- [x] fecgov/fec-proxy#273
- [x] fecgov/fec-cms#4691
- [x] fecgov/fec-cms#4538
- [x] fecgov/fec-cms#4472
- [x] fecgov/fec-cms#4278
- [x] fecgov/fec-cms#3878
- [x] fecgov/fec-eregs#532
- [x] fecgov/openFEC#4592
- [x] fecgov/fec-cms#4058
- [x] fecgov/fec-cms#4028
- [x] fecgov/fec-cms#4053
- [x] fecgov/openFEC#4614
- [x] fecgov/fec-cms#3931
- [x] fecgov/fec-cms#3470
- [x] fecgov/fec-cms#3961
- [x] fecgov/fec-cms#3883
- [x] fecgov/fec-cms#3484
- [x] fecgov/fec-eregs#502
- [x] fecgov/fec-cms#3751
- [x] fecgov/fec-cms#2907
- [x] fecgov/fec-cms#3666
- [x] fecgov/openFEC#4333
- [x] fecgov/openFEC#4237
- [x] fecgov/fec-cms#3565
- [x] fecgov/fec-cms#3220
- [x] fecgov/fec-cms#3428
- [x] fecgov/fec-cms#1820
- [x] fecgov/fec-cms#3112
- [x] fecgov/fec-cms#3353
- [x] fecgov/openFEC#4028
- [x] fecgov/openFEC#3985
- [x] fecgov/fec-cms#2482
- [x] fecgov/fec-cms#3083
- [x] fecgov/openFEC#3302
- [x] fecgov/fec-cms#3111
- [x] fecgov/fec-cms#3049
- [x] fecgov/fec-cms#2969
- [x] fecgov/fec-cms#1533
- [x] fecgov/fec-cms#1569
- [x] fecgov/fec-eregs#443
- [x] fecgov/openFEC#3573
- [x] fecgov/fec-cms#2467
- [x] fecgov/fec-cms#2723
- [x] fecgov/fec-cms#2617
- [x] fecgov/fec-cms#2459
- [x] fecgov/fec-cms#2439
- [x] fecgov/fec-cms#2438
- [x] fecgov/fec-cms#2568
- [x] fecgov/fec-cms#2569
- [x] fecgov/fec-cms#2555
- [x] fecgov/fec-cms#2498
- [x] fecgov/fec-cms#2532
- [x] fecgov/fec-cms#2496
- [x] fecgov/fec-cms#1419
- [x] fecgov/openFEC#3143
- [x] fecgov/fec-cms#2477
- [x] fecgov/openFEC#3461
- [x] fecgov/fec-eregs#396
- [x] fecgov/fec-cms#2437
- [x] fecgov/fec-cms#2436
- [x] fecgov/fec-cms#2392
- [x] fecgov/fec-cms#2386
- [x] fecgov/fec-cms#2385
- [x] fecgov/fec-cms#2400
- [x] fecgov/openFEC#3393
- [x] fecgov/fec-cms#2134
- [x] fecgov/fec-cms#2325
- [x] fecgov/openFEC#3377
- [x] fecgov/fec-cms#2338
- [x] fecgov/openFEC#3374
- [x] fecgov/openFEC#3359
- [x] fecgov/openFEC#2835
- [x] fecgov/fec-cms#2307
- [x] fecgov/openFEC#3271
