### ISSUE TITLE
Information architecture and navigation

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#14]
## Tickets
- [x] fecgov/fec-cms#557
- [x] fecgov/fec-cms#556
- [x] fecgov/fec-cms#555
- [x] fecgov/fec-epics#43
- [x] fecgov/fec-epics#42
- [x] fecgov/fec-epics#41
- [x] fecgov/fec-cms#491
