### ISSUE TITLE
Epic: UX/design

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#140]
- Design/develop nationwide-election pages and data improvements
- FEC outreach pages
- Compliance dates reliability improvements
-  Improve Leadership PAC profile pages
- Testing

## Tickets
- [ ] fecgov/fec-cms#4913
- [ ] fecgov/fec-cms#5064
- [ ] fecgov/fec-pattern-library#181
- [ ] fecgov/fec-cms#3155
- [ ] fecgov/fec-cms#4553
- [ ] fecgov/fec-cms#3268
- [ ] fecgov/fec-cms#3324
- [ ] fecgov/fec-cms#3349
- [ ] fecgov/fec-cms#3365
- [ ] fecgov/fec-cms#3754
- [ ] fecgov/fec-cms#4089
- [ ] fecgov/fec-cms#4156
- [ ] fecgov/fec-cms#3652
- [ ] fecgov/fec-cms#3721
- [ ] fecgov/fec-cms#3464
- [ ] fecgov/fec-cms#4128
- [ ] fecgov/fec-cms#4108
- [ ] fecgov/fec-pattern-library#167
- [x] fecgov/fec-cms#3917
- [ ] fecgov/openFEC#4446
- [ ] fecgov/fec-cms#4259
- [ ] fecgov/fec-cms#4260
- [ ] fecgov/fec-cms#4339
- [ ] fecgov/fec-cms#4406
- [ ] fecgov/fec-cms#4408
- [ ] fecgov/fec-cms#4409
- [ ] fecgov/fec-cms#4441
- [ ] fecgov/fec-cms#5039
- [ ] fecgov/fec-cms#5065
- [x] fecgov/fec-cms#5397
- [x] fecgov/fec-proxy#398
- [ ] fecgov/fec-cms#4941
- [ ] fecgov/fec-cms#5496
- [x] fecgov/fec-cms#4942
- [ ] fecgov/fec-cms#5179
- [ ] fecgov/fec-cms#4554
- [ ] fecgov/fec-cms#4710
- [x] fecgov/fec-cms#4258
- [ ] fecgov/fec-cms#4996
- [x] fecgov/fec-cms#5857
- [ ] fecgov/fec-cms#5599
- [x] fecgov/fec-cms#5625
- [ ] fecgov/fec-cms#5349
- [ ] fecgov/fec-cms#4375
- [ ] fecgov/fec-cms#4789
- [ ] fecgov/fec-cms#4543
- [ ] fecgov/fec-cms#3114
- [ ] fecgov/fec-cms#2359
- [ ] fecgov/fec-cms#2858
- [ ] fecgov/fec-testing#114
- [ ] fecgov/fec-cms#2355
- [ ] fecgov/fec-cms#2315
- [x] fecgov/fec-cms#3834
- [x] fecgov/fec-cms#6080
- [x] fecgov/fec-cms#5994
- [x] fecgov/fec-cms#5243
- [x] fecgov/fec-cms#5844
- [x] fecgov/fec-cms#5838
- [x] fecgov/openFEC#5540
- [x] fecgov/openFEC#5208
- [x] fecgov/fec-cms#5431
- [x] fecgov/fec-cms#5581
- [x] fecgov/fec-cms#5421
- [x] fecgov/fec-cms#5400
- [x] fecgov/fec-cms#5398
- [x] fecgov/fec-cms#4662
- [x] fecgov/fec-cms#5355
- [x] fecgov/fec-cms#5352
- [x] fecgov/fec-cms#5367
- [x] fecgov/fec-cms#4661
- [x] fecgov/fec-cms#5041
- [x] fecgov/fec-cms#4377
- [x] fecgov/fec-cms#5227
- [x] fecgov/fec-cms#4980
- [x] fecgov/fec-cms#5211
- [x] fecgov/openFEC#5120
- [x] fecgov/fec-cms#5180
- [x] fecgov/fec-cms#4352
- [x] fecgov/openFEC#4997
- [x] fecgov/fec-cms#5073
- [x] fecgov/fec-cms#5009
- [x] fecgov/fec-cms#4987
- [x] fecgov/fec-cms#4986
- [x] fecgov/fec-cms#4877
- [x] fecgov/fec-cms#4975
- [x] fecgov/fec-cms#4937
- [x] fecgov/fec-cms#4874
- [x] fecgov/fec-cms#4923
- [x] fecgov/fec-cms#4354
- [x] fecgov/fec-cms#4557
- [x] fecgov/fec-cms#4927
- [x] fecgov/fec-cms#4850
- [x] fecgov/fec-cms#3737
- [x] fecgov/fec-cms#4766
- [x] fecgov/fec-cms#4570
- [x] fecgov/fec-cms#4111
- [x] fecgov/fec-cms#3979
- [x] fecgov/fec-cms#4577
- [x] fecgov/fec-cms#4542
- [x] fecgov/fec-cms#3386
- [x] fecgov/openFEC#4801
- [x] fecgov/fec-cms#4235
- [x] fecgov/fec-cms#4166
- [x] fecgov/fec-cms#3989
- [x] fecgov/fec-cms#3313
- [x] fecgov/fec-cms#3836
- [x] fecgov/fec-cms#4130
- [x] fecgov/fec-pattern-library#160
- [x] fecgov/fec-cms#3940
- [x] fecgov/fec-cms#4036
- [x] fecgov/fec-cms#3535
- [x] fecgov/fec-cms#3996
- [x] fecgov/fec-cms#3985
- [x] fecgov/fec-cms#3331
- [x] fecgov/fec-cms#3901
- [x] fecgov/fec-cms#3333
- [x] fecgov/fec-cms#3797
- [x] fecgov/fec-cms#3838
- [x] fecgov/fec-cms#3542
- [x] fecgov/fec-cms#3819
- [x] fecgov/fec-cms#3649
- [x] fecgov/fec-cms#3602
- [x] fecgov/fec-cms#3806
- [x] fecgov/fec-cms#3592
- [x] fecgov/fec-cms#3810
- [x] fecgov/fec-cms#3184
- [x] fecgov/fec-cms#3646
- [x] fecgov/fec-cms#3325
- [x] fecgov/fec-cms#3585
- [x] fecgov/fec-cms#3588
- [x] fecgov/fec-cms#3210
- [x] fecgov/fec-cms#3183
- [x] fecgov/fec-testing#129
- [x] fecgov/fec-cms#3460
- [x] fecgov/fec-cms#3344
- [x] fecgov/fec-cms#3192
- [x] fecgov/fec-testing#128
- [x] fecgov/fec-cms#3339
- [x] fecgov/fec-cms#3367
- [x] fecgov/fec-cms#3332
- [x] fecgov/fec-testing#126
- [x] fecgov/fec-cms#3330
- [x] fecgov/fec-cms#3328
- [x] fecgov/fec-cms#3259
- [x] fecgov/fec-cms#2739
- [x] fecgov/fec-cms#2935
- [x] fecgov/fec-cms#3236
- [x] fecgov/fec-testing#125
- [x] fecgov/fec-cms#3237
- [x] fecgov/fec-cms#3181
- [x] fecgov/fec-cms#1635
- [x] fecgov/fec-cms#3250
- [x] fecgov/fec-cms#3182
- [x] fecgov/fec-cms#3133
- [x] fecgov/fec-cms#2839
- [x] fecgov/fec-cms#2972
- [x] fecgov/fec-cms#2986
- [x] fecgov/fec-cms#2950
- [x] fecgov/fec-cms#2452
- [x] fecgov/fec-pattern-library#40
- [x] fecgov/fec-cms#1944
- [x] fecgov/fec-cms#1739
- [x] fecgov/fec-cms#2889
- [x] fecgov/fec-cms#2760
- [x] fecgov/fec-cms#2566
- [x] fecgov/fec-cms#2537
- [x] fecgov/fec-cms#2541
- [x] fecgov/fec-cms#2306
- [x] fecgov/fec-cms#2283
- [x] fecgov/fec-cms#2469
- [x] fecgov/fec-cms#2476
- [x] fecgov/fec-cms#2117
- [x] fecgov/fec-cms#2470
- [x] fecgov/fec-cms#2416
- [x] fecgov/fec-cms#2422
- [x] fecgov/fec-cms#2369
- [x] fecgov/fec-cms#2390
- [x] fecgov/fec-cms#2341
- [x] fecgov/fec-cms#2354
- [x] fecgov/fec-cms#2286
- [x] fecgov/fec-cms#2285
- [x] fecgov/fec-cms#2199
- [x] fecgov/fecnet#249
- [x] fecgov/fecnet#253
- [x] fecgov/fecnet#255
