### ISSUE TITLE
Election support

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#143]
- Election support including adding schedule filters
- Lift 2-year restrictions on schedules A & B

## Tickets
- [x] fecgov/fec-cms#2566
- [x] fecgov/fec-cms#2674
- [x] fecgov/fec-cms#2455
- [x] fecgov/fec-cms#2447
- [x] fecgov/openFEC#3417
- [x] fecgov/fec-cms#2463
- [x] fecgov/openFEC#3248
- [x] fecgov/fec-cms#2485
- [x] fecgov/fec-cms#2453
- [x] fecgov/openFEC#3274
- [x] fecgov/openFEC#3406
- [x] fecgov/fec-cms#1912
- [x] fecgov/fec-cms#2321
- [x] fecgov/fec-cms#1745
- [x] fecgov/openFEC#3230
- [x] fecgov/openFEC#3276
- [x] fecgov/openFEC#3370
- [x] fecgov/fec-cms#2154

**Comment by patphongs** [comment]
Closing this since we have a separate epic for 2020 election data improvements https://github.com/fecgov/fec-epics/issues/146
