### ISSUE TITLE
Nationwide raising map

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-epics#144]
Goal: 
- Step 1: Implement MVP of nationwide raising choropleth maps mocked up during PI 8: https://github.com/fecgov/fec-cms/issues/2542
- Step 2: Include per-party breakdown of this data (make a feature flag if front-end work is done first)

## Tickets
- [x] fecgov/fec-cms#2604
- [x] fecgov/openFEC#3543
- [x] fecgov/fec-cms#2563
- [x] fecgov/fec-cms#2611
- [x] fecgov/openFEC#3552
- [x] fecgov/openFEC#3548
- [x] fecgov/fec-cms#2628
- [x] fecgov/fec-cms#2610
- [x] fecgov/fec-cms#2609
- [x] fecgov/openFEC#3544
- [x] fecgov/fec-cms#2605
- [x] fecgov/fec-cms#2614
- [x] fecgov/fec-cms#2615
- [x] fecgov/fec-cms#2612
- [x] fecgov/fec-cms#2603
- [x] fecgov/openFEC#3551
- [x] fecgov/openFEC#3550
- [x] fecgov/fec-cms#2618
- [x] fecgov/fec-cms#2608
- [x] fecgov/fec-cms#2586

**Comment by patphongs** [comment]
This is no longer the path we are going towards for raising data. Closing this issue as it is now outdated.
