### ISSUE TITLE
Epic: Campaign finance data section improvements

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-epics#146]
Goal: Make 2020 data easier to find, and fix data issues that arise

## Tickets
- [ ] fecgov/fec-cms#3593
- [ ] fecgov/fec-cms#4296
- [ ] fecgov/fec-cms#4883
- [ ] fecgov/fec-cms#4884
- [ ] fecgov/fec-epics#167
- [ ] fecgov/fec-cms#4774
- [ ] fecgov/fec-cms#2204
- [ ] fecgov/openFEC#3261
- [x] fecgov/fec-epics#180
- [x] fecgov/fec-epics#168
- [x] fecgov/openFEC#3523
- [x] fecgov/fec-cms#4949
- [x] fecgov/openFEC#4053
- [x] fecgov/openFEC#4757
- [x] fecgov/fec-cms#4465
- [x] fecgov/openFEC#4800
- [x] fecgov/fec-cms#4293
- [x] fecgov/openFEC#4725
- [x] fecgov/openFEC#4685
- [x] fecgov/openFEC#4483
- [x] fecgov/fec-epics#155
- [x] fecgov/fec-epics#153
- [x] fecgov/openFEC#4292
- [x] fecgov/openFEC#4362
- [x] fecgov/fec-epics#179
- [x] fecgov/fec-cms#3363
- [x] fecgov/openFEC#4215
- [x] fecgov/fec-cms#3567
- [x] fecgov/fec-cms#3463
- [x] fecgov/fec-cms#2964
- [x] fecgov/fec-cms#3320
- [x] fecgov/openFEC#4066
- [x] fecgov/fec-cms#3041
- [x] fecgov/fec-cms#3314
- [x] fecgov/openFEC#3928
- [x] fecgov/openFEC#4005
- [x] fecgov/openFEC#3939
- [x] fecgov/openFEC#4015
- [x] fecgov/openFEC#3948
- [x] fecgov/openFEC#4004
- [x] fecgov/openFEC#3789
- [x] fecgov/openFEC#3946
- [x] fecgov/fec-cms#3086
- [x] fecgov/fec-cms#3078
- [x] fecgov/fec-cms#3079
- [x] fecgov/fec-cms#3119
- [x] fecgov/openFEC#3908
- [x] fecgov/openFEC#3455
- [x] fecgov/openFEC#3907
- [x] fecgov/fec-cms#3054
- [x] fecgov/fec-cms#3024
- [x] fecgov/openFEC#3841
- [x] fecgov/fec-cms#3019
- [x] fecgov/openFEC#3807
- [x] fecgov/fec-cms#3001
- [x] fecgov/fec-cms#2866
- [x] fecgov/openFEC#3802
- [x] fecgov/fec-cms#2927
- [x] fecgov/fec-cms#2135
- [x] fecgov/openFEC#3768
- [x] fecgov/fec-cms#2936
- [x] fecgov/fec-cms#2797
- [x] fecgov/fec-cms#2895
- [x] fecgov/openFEC#3701
- [x] fecgov/fec-cms#2640
- [x] fecgov/openFEC#3772
- [x] fecgov/fec-cms#2648
- [x] fecgov/openFEC#3627
- [x] fecgov/fec-cms#2594
- [x] fecgov/openFEC#3656
- [x] fecgov/fec-cms#2788
- [x] fecgov/fec-cms#2620
- [x] fecgov/openFEC#3659
- [x] fecgov/fec-cms#2565
- [x] fecgov/openFEC#3611
- [x] fecgov/fec-cms#2674
- [x] fecgov/openFEC#3562
- [x] fecgov/openFEC#3262
- [x] fecgov/fec-cms#2631
