### ISSUE TITLE
Epic: Visualizations

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#148]
**What we’re after**: We want to create easy to understand data visualizations that are in pictorial or graphical formats to enable users to see the data visually and allow them to better understand and decipher the complexity of our data. Allow users to more easily share and save our visualizations.

**Why we’re after it**: The public has always been interested in campaign finance data. Over half our fec.gov website visitors look at our data and adding the ability to display our data in an interesting and helpful way will make our product more engaging.

## Epics
- [x] fecgov/fec-epics#145
- [x] fecgov/fec-epics#156
- [x] fecgov/fec-epics#152
- [x] fecgov/fec-epics#151

## Tickets
- [ ] fecgov/openFEC#3598
- [ ] fecgov/fec-cms#2667
- [ ] fecgov/fec-cms#2909
- [ ] fecgov/fec-cms#3633
- [x] fecgov/fec-epics#149
- [x] fecgov/fec-cms#2929
- [x] fecgov/fec-cms#2965
- [x] fecgov/openFEC#3777
- [x] fecgov/fec-cms#2904
- [x] fecgov/fec-cms#2802
- [x] fecgov/fec-cms#2838
- [x] fecgov/openFEC#3549

**Comment by PaulClark2** [comment]
Close for now.
