### ISSUE TITLE
Latest Updates feed

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#15]
## Tickets
- [x] fecgov/fec-cms#790
- [x] fecgov/fec-cms#574
- [x] fecgov/fec-cms#486
- [x] fecgov/fec-cms#553
- [x] fecgov/fec-cms#789
- [x] fecgov/fec-cms#549
- [x] fecgov/fec-cms#550
- [x] fecgov/fec-cms#791
- [x] fecgov/fec-cms#788
- [x] fecgov/fec-cms#598
- [x] fecgov/fec-cms#524
- [x] fecgov/fec-cms#488
- [x] fecgov/fec-cms#496

**Comment by emileighoutlaw** [comment]
The `Latest updates` feed should surface content specifically created for users. Therefore the feed will be complete when it includes:

- [x] Press releases
- [x] Weekly Digests
- [ ] FEC Record articles
- [ ] Tips for Treasurers
- [ ] Sunshine notices (notices that a meeting is going to happen and generally what will be discussed at that meeting)
- [ ] Meeting agendas (published after Sunshine notices and including more detail)

If these are the documents to be included in `Latest updates` we'll need to:
- [ ] Decide if/how the filters are affected by these new documents
- [ ] How to port/implement remaining content types
    - Record articles
    - Tips
    - Sunshine notices
    - Meeting agendas
