### ISSUE TITLE
Feature: Improve data navigation

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#151]
Based on user research, making improvements to navigation in the data section. Focusing on user feedback provided in the feedback box/FEC repo. We can document multiple user stories here based on the review of the feedback box. 

User story: As a data user, I want a direct path to the data landing page to start my data search. 

## Tickets
- [ ] fecgov/fec-cms#3764
- [ ] fecgov/fec-cms#3765
- [ ] fecgov/fec-cms#3782
- [ ] fecgov/fec-cms#3741
- [x] fecgov/fec-cms#3766
- [x] fecgov/fec-cms#3186
- [x] fecgov/fec-cms#3763
- [x] fecgov/fec-cms#3689
- [x] fecgov/fec-cms#3675
- [x] fecgov/fec-cms#3210
- [x] fecgov/fec-cms#2548
