### ISSUE TITLE
Feature: Share and save widgets

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#152]
As a user, I want to be able to save and share interesting visualizations so that I can include them in relevant work.

## Tickets
- [ ] fecgov/fec-cms#2980
- [ ] fecgov/fec-cms#2727
- [ ] fecgov/fec-cms#2909
- [ ] fecgov/fec-cms#2793
- [x] fecgov/fec-cms#2981
- [x] fecgov/fec-cms#2803
