### ISSUE TITLE
Feature: Remove two-year restrictions for raising and spending data

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#153]
As a data user, I need to be able to view data more easily across multiple time periods so that I can see the full picture of transactions.

## Tickets
- [ ] fecgov/fec-cms#2816
- [ ] fecgov/fec-cms#2817
- [x] fecgov/fec-cms#2987
- [x] fecgov/fec-cms#2815
- [x] fecgov/fec-testing#120
- [x] fecgov/fec-cms#2988
- [x] fecgov/fec-cms#2983
- [x] fecgov/fec-cms#2811
- [x] fecgov/fec-cms#2903
- [x] fecgov/fec-cms#2606
- [x] fecgov/fec-cms#2905
- [x] fecgov/fec-cms#2871
- [x] fecgov/fec-cms#2812
- [x] fecgov/fec-cms#2867
- [x] fecgov/openFEC#3772
- [x] fecgov/fec-cms#2897
- [x] fecgov/fec-cms#2788
- [x] fecgov/openFEC#3595
