### ISSUE TITLE
Feature: Where contributions come from

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#156]
**What we're after:**
As a user, I want to be able to understand how much a candidate has raised in each individual state so that I can better track these candidates.

## Tickets
- [ ] fecgov/openFEC#4244
- [x] fecgov/fec-cms#3290
- [x] fecgov/fec-cms#3237
- [x] fecgov/fec-cms#3304
- [x] fecgov/fec-cms#3218
- [x] fecgov/fec-cms#3246
- [x] fecgov/fec-cms#3215
- [x] fecgov/openFEC#3986
- [x] fecgov/fec-cms#3146
- [x] fecgov/fec-cms#3232
- [x] fecgov/fec-cms#3216
- [x] fecgov/fec-cms#3204
- [x] fecgov/fec-cms#3203
- [x] fecgov/fec-cms#3195
- [x] fecgov/openFEC#3970
- [x] fecgov/fec-cms#2929
- [x] fecgov/fec-cms#3123
- [x] fecgov/openFEC#3819
- [x] fecgov/openFEC#3777
- [x] fecgov/fec-cms#2904
- [x] fecgov/fec-cms#2906
