### ISSUE TITLE
Sub-epic: Back-end bugs and tasks

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#158]
Miscellaneous back-end bugs, tasks and chores

## Tickets
- [ ] fecgov/openFEC#4703
- [ ] fecgov/openFEC#4850
- [ ] fecgov/openFEC#3885
- [ ] fecgov/openFEC#5394
- [ ] fecgov/fec-cms#3006
- [ ] fecgov/openFEC#3499
- [x] fecgov/openFEC#5577
- [x] fecgov/openFEC#4861
- [x] fecgov/openFEC#5478
- [x] fecgov/openFEC#5561
- [x] fecgov/openFEC#5560
- [x] fecgov/openFEC#5442
- [x] fecgov/openFEC#5441
- [x] fecgov/openFEC#5378
- [x] fecgov/fec-cms#5668
- [x] fecgov/openFEC#5232
- [x] fecgov/openFEC#5053
- [x] fecgov/fec-cms#4488
- [x] fecgov/openFEC#4462
- [x] fecgov/openFEC#4238
- [x] fecgov/openFEC#4086
- [x] fecgov/openFEC#4025
