### ISSUE TITLE
Sub-epic: Front-end bugs and tasks

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#159]
Miscellaneous front-end bugs, tasks and chores

## Tickets
- [x] fecgov/fec-cms#5225
- [ ] fecgov/openFEC#4000
- [ ] fecgov/fec-cms#3309
- [ ] fecgov/fec-cms#3485
- [ ] fecgov/fec-cms#3576
- [ ] fecgov/fec-cms#3997
- [ ] fecgov/fec-cms#4326
- [ ] fecgov/fec-cms#2985
- [ ] fecgov/fec-cms#4696
- [ ] fecgov/fec-cms#5685
- [ ] fecgov/fec-cms#5756
- [ ] fecgov/fec-cms#5577
- [ ] fecgov/fec-cms#5412
- [ ] fecgov/fec-cms#5665
- [ ] fecgov/fec-cms#5794
- [x] fecgov/fec-cms#6073
- [x] fecgov/fec-cms#6045
- [ ] fecgov/fec-cms#5866
- [x] fecgov/fec-cms#6118
- [ ] fecgov/fec-cms#4558
- [ ] fecgov/fec-cms#2540
- [ ] fecgov/fec-cms#2701
- [ ] fecgov/fec-cms#2721
- [ ] fecgov/fec-cms#3992
- [ ] fecgov/fec-cms#3641
- [x] fecgov/fec-cms#6079
- [x] fecgov/fec-cms#5964
- [x] fecgov/fec-cms#5913
- [x] fecgov/fec-cms#6002
- [x] fecgov/fec-cms#5999
- [x] fecgov/fec-cms#5959
- [x] fecgov/fec-cms#5910
- [x] fecgov/fec-cms#5956
- [x] fecgov/fec-cms#5944
- [x] fecgov/fec-cms#5224
- [x] fecgov/fec-cms#5843
- [x] fecgov/fec-cms#5317
- [x] fecgov/fec-cms#5720
- [x] fecgov/fec-cms#2218
- [x] fecgov/fec-cms#5698
- [x] fecgov/fec-cms#5624
- [x] fecgov/fec-cms#5608
- [x] fecgov/fec-cms#5532
- [x] fecgov/fec-cms#5453
- [x] fecgov/fec-cms#5248
- [x] fecgov/fec-cms#5316
- [x] fecgov/fec-cms#4857
- [x] fecgov/fec-cms#5208
- [x] fecgov/fec-cms#5209
- [x] fecgov/fec-cms#4807
