### ISSUE TITLE
Improve aggregate tables

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#16]
## Tickets
- [x] fecgov/openFEC#1947
- [x] fecgov/openFEC-web-app#1445
- [x] fecgov/openFEC-web-app#1447
- [x] fecgov/openFEC-web-app#1461
- [x] fecgov/openFEC-web-app#1471
- [x] fecgov/openFEC-web-app#1609
- [x] fecgov/openFEC-web-app#1658
