### ISSUE TITLE
Sub-epic: Back-end technical debt

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#163]
**What we're after:** As a developer, I want to establish a robust development environment.

**Why we're after it:** To ensure a seamless and reliable development and deployment process to guarantee continuity of the API codebase.

## Tickets
- [ ] fecgov/fec-eregs#451
- [ ] fecgov/openFEC#4395
- [ ] fecgov/openFEC#5681
- [x] fecgov/fec-eregs#819
- [x] fecgov/fec-cms#6058
- [ ] fecgov/openFEC#4448
- [x] fecgov/openFEC#5678
- [ ] fecgov/openFEC#5682
- [ ] fecgov/openFEC#3878
- [x] fecgov/openFEC#5493
- [x] fecgov/fec-cms#6026
- [x] fecgov/fec-cms#4897
- [x] fecgov/openFEC#4223
- [x] fecgov/openFEC#5603
- [x] fecgov/fec-cms#5714
- [x] fecgov/openFEC#3930
- [x] fecgov/openFEC#5043
- [x] fecgov/openFEC#5041
- [x] fecgov/fec-eregs#661
- [x] fecgov/openFEC#4935
- [x] fecgov/openFEC#4357
- [x] fecgov/openFEC#4248
- [x] fecgov/fec-eregs#524
- [x] fecgov/openFEC#4579
- [x] fecgov/openFEC#4507
