### ISSUE TITLE
Sub-epic: Front-end technical debt

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#164]
## Tickets
- [ ] fecgov/fec-cms#3140
- [ ] fecgov/openFEC#4413
- [ ] fecgov/fec-cms#3969
- [x] fecgov/fec-cms#5153
- [ ] fecgov/fec-cms#4859
- [ ] fecgov/fec-cms#4940
- [ ] fecgov/fec-cms#4502
- [ ] fecgov/fec-cms#2613
- [x] fecgov/fec-cms#5572
- [x] fecgov/fec-cms#4763
- [x] fecgov/fec-cms#5014
- [x] fecgov/fec-cms#4010
- [x] fecgov/fec-cms#5035
- [x] fecgov/fec-cms#4811
- [x] fecgov/openFEC#4847
- [x] fecgov/fec-cms#4779
- [x] fecgov/fec-cms#4682
- [x] fecgov/fec-cms#4630
- [x] fecgov/fec-cms#4529
- [x] fecgov/fec-cms#3887
- [x] fecgov/fec-cms#3373
- [x] fecgov/fec-cms#3376
- [x] fecgov/fec-cms#3371
