### ISSUE TITLE
Feature: Schedule H4

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#168]
**What we're after:** Provide disbursements for allocated federal and nonfederal activity, which is schedule H4 Lines 21(a)(i) and (ii). ([Reporting form](https://www.fec.gov/resources/cms-content/documents/fecfrm3x.pdf))

## Tickets
- [x] fecgov/fec-cms#3432
- [x] fecgov/fec-cms#5914
- [x] fecgov/fec-cms#5654
- [x] fecgov/fec-cms#5652
- [x] fecgov/fec-cms#5651
- [x] fecgov/fec-cms#5653
- [x] fecgov/openFEC#5364
- [x] fecgov/fec-cms#5647
- [x] fecgov/openFEC#5361
- [x] fecgov/openFEC#5360
- [x] fecgov/openFEC#4130
- [x] fecgov/openFEC#4112
- [x] fecgov/openFEC#4123
- [x] fecgov/fec-cms#3434

**Comment by patphongs** [comment]
Work has finished and is now [live](https://www.fec.gov/data/allocated-federal-nonfederal-disbursements/?data_type=processed&cycle=2024&min_date=01%2F01%2F2023&max_date=12%2F31%2F2024).
