### ISSUE TITLE
Feature: Administrative fine calculator

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-epics#169]
**User story:** As a user, I need to be able to calculate accurate fine estimates, so that I can better prepare our committee if a fine is assessed.

## Tickets
- [x]  fecgov/fec-cms#3803
- [x]  fecgov/fec-cms#3789
- [x]  fecgov/fec-cms#3783
- [x]  fecgov/fec-cms#3421
- [x]  fecgov/fec-cms#3732
- [x]  fecgov/fec-cms#3743
- [x]  fecgov/fec-cms#3688
- [x]  fecgov/fec-cms#3624
- [x]  fecgov/fec-cms#3687
- [x]  fecgov/fec-cms#3728
- [x]  fecgov/fec-cms#3686
- [x]  fecgov/fec-cms#3461
- [x]  fecgov/fec-cms#3431
- [x]  fecgov/fec-cms#3468
- [x]  fecgov/fec-cms#3414
- [x]  fecgov/fec-testing#128
- [x]  fecgov/fec-cms#3413
- [x]  fecgov/fec-testing#127
