### ISSUE TITLE
Epic: Classic.fec.gov

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-epics#172]
## Tickets
- [x] fecgov/fec-cms#3471
- [x] fecgov/fec-cms#3511
- [x] fecgov/fec-cms#3410
- [x] fecgov/fec-cms#3483
