### ISSUE TITLE
Feature: Policy and guidance documents page and search

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-epics#173]
**What we’re after:** Executive order 13892 requires the FEC to create an independent searchable page that contains the agency's guidance documents.

**Why we’re after it:** To provide a user-friendly way for users to search through all identified guidance documents and remain compliant with Executive Order 13892.

## Tickets
- [ ] fecgov/fec-cms#3804
- [x] fecgov/fec-cms#5883
- [x] fecgov/fec-cms#5897
- [x] fecgov/fec-cms#3793
- [x] fecgov/fec-cms#3744
- [x] fecgov/fec-cms#3598
- [x] fecgov/fec-cms#3719
- [x] fecgov/fec-cms#3745
- [x] fecgov/fec-cms#3705
- [x] fecgov/fec-cms#3685
- [x] fecgov/fec-cms#3671
- [x] fecgov/fec-cms#3684
- [x] fecgov/fec-cms#3704
- [x] fecgov/fec-cms#3670
- [x] fecgov/fec-cms#3672
- [x] fecgov/fec-cms#3637
- [x] fecgov/fec-cms#3658
- [x] fecgov/fec-cms#3599
- [x] fecgov/fec-cms#3614
- [x] fecgov/fec-cms#3491
- [x] fecgov/fec-cms#3662
- [x] fecgov/fec-cms#3601
- [x] fecgov/fec-cms#3490
- [x] fecgov/fec-cms#3645
- [x] fecgov/fec-cms#3654
- [x] fecgov/fec-cms#3638
- [x] fecgov/fec-cms#3635
- [x] fecgov/fec-cms#3644
- [x] fecgov/fec-cms#3596
- [x] fecgov/fec-cms#3590
- [x] fecgov/fec-cms#3580
- [x] fecgov/openFEC#4235
- [x] fecgov/fec-cms#3581
- [x] fecgov/fec-cms#3554
- [x] fecgov/fec-cms#3527
- [x] fecgov/fec-cms#3489
- [x] fecgov/fec-cms#3488
- [x] fecgov/fec-cms#3220

**Comment by dorothyyeager** [comment]
Edited epic title to better reflect what the Executive Order we need to comply with calls it. (The policy page is an existing legal resources page we're going to bring into Wagtail.)

**Comment by jason-upchurch** [comment]
MVPs for policy and guidance search:
- [x] Get final list of policy and guidance docs to search (content team, @dorothyyeager )
- [ ] Design and mock-up search interface and meet with OGC to finalize (content, design (@JonellaCulmer ), and OGC teams)
- [x] Use search.gov to index final policy and guidance list, should include searching PDFs and HTML pages (Backend - @jason-upchurch )
- [ ] ~Create scheduled task to run the search.gov indexer for policy and guidance docs (Back end - @Jason Upchurch)~ _this task is not in the MVP but can be an _improvement_ to the MVP_
- [ ] Integrate search.gov policy and guidance search with FEC’s CMS interface to display search and results. (Front end - @patphongs )
