### ISSUE TITLE
Epic: Presidential map

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#174]
**What we're after:**
Re-create presidential map from the classic site using existing presidential data from classic and updated styles and designs from the new website.

**MoSCoW:** https://docs.google.com/document/d/1CH5-W6QzVF7Zve2P3ttVPK9gdfVNm_x5NBY4gXoV9vQ/edit#heading=h.rb2xlztdppnr 🔒 

### Chart components from classic
Below are the components we discussed are MVPs for the presidential map
![Screen Shot 2020-01-31 at 9 59 51 AM](https://user-images.githubusercontent.com/12799132/73552057-8a173480-4415-11ea-8895-e33df746079d.png)

![Screen Shot 2020-01-31 at 10 07 15 AM](https://user-images.githubusercontent.com/12799132/73551670-d44be600-4414-11ea-9d95-9127a1e0145c.png)

![Screen Shot 2020-01-31 at 10 23 21 AM](https://user-images.githubusercontent.com/12799132/73552302-f85bf700-4415-11ea-9cc4-c098800c6a35.png)

![image.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/931b4128-a331-4855-b158-7ca3c53a4329)

## Tickets
- [x] fecgov/openFEC#5447
- [x] fecgov/openFEC#5480
- [x] fecgov/openFEC#5373
- [x] fecgov/fec-cms#3498
- [x] fecgov/fec-cms#3892
- [x] fecgov/fec-cms#3600
- [x] fecgov/fec-cms#3496
- [x] fecgov/fec-cms#3631
- [x] fecgov/openFEC#4221
- [x] fecgov/fec-cms#3522
- [x] fecgov/fec-cms#3560
- [x] fecgov/fec-cms#3509
- [x] fecgov/fec-cms#3517
- [x] fecgov/fec-cms#3591
- [x] fecgov/fec-cms#3544
- [x] fecgov/fec-cms#3497
- [x] fecgov/fec-cms#3495
- [x] fecgov/openFEC#4172
- [x] fecgov/fec-cms#3516
- [x] fecgov/fec-cms#3515
- [x] fecgov/openFEC#4191
- [x] fecgov/fec-cms#3521
- [x] fecgov/openFEC#4219
- [x] fecgov/fec-cms#3514
- [x] fecgov/fec-cms#3507
- [x] fecgov/fec-cms#3513
- [x] fecgov/fec-cms#3503
- [x] fecgov/openFEC#4186
- [x] fecgov/fec-cms#3500
- [x] fecgov/fec-cms#3502
- [x] fecgov/fec-cms#3506
- [x] fecgov/openFEC#4171
- [x] fecgov/openFEC#4178
- [x] fecgov/openFEC#4169
- [x] fecgov/openFEC#4177
- [x] fecgov/openFEC#4170
- [x] fecgov/openFEC#4168
- [x] fecgov/fec-cms#3494
- [x] fecgov/fec-cms#3501
- [x] fecgov/fec-cms#3508
- [x] fecgov/openFEC#4175
- [x] fecgov/fec-cms#3504
