### ISSUE TITLE
Feature: Active / terminated committees

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#176]
**What we’re after:** When displaying committee information, indicate whether it is active or terminated. 

**Why we’re after it:** Users have expressed the need to quickly determine if a committee is active or terminated. This is critical information for reporting purposes.

## Tickets
- [x] fecgov/fec-cms#3752
- [x] fecgov/fec-cms#3796
- [x] fecgov/fec-cms#3642
- [x] fecgov/openFEC#4270
- [x] fecgov/openFEC#4296
- [x] fecgov/openFEC#4284
- [x] fecgov/openFEC#4283
