### ISSUE TITLE
API signup

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-epics#177]
### Major components
- [ ] research validating api keys during signup
- [ ] define acceptable use policy
- [ ] make api key signup page (https://github.com/fecgov/openFEC/issues/3947 )
