### ISSUE TITLE
Feature: API key signup

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-epics#178]
### Major components
- [ ] research validating api keys during signup (https://github.com/fecgov/openFEC/issues/4306)
- [ ] define acceptable use policy (https://github.com/fecgov/openFEC/issues/4305)
- [ ] make api key signup page (https://github.com/fecgov/openFEC/issues/3947 )

## Tickets
- [ ] fecgov/openFEC#4565
- [ ] fecgov/openFEC#4445
- [x] fecgov/openFEC#4447
- [x] fecgov/openFEC#4562
- [x] fecgov/openFEC#4564
- [x] fecgov/openFEC#4532
- [x] fecgov/openFEC#4511
- [x] fecgov/openFEC#4510
- [x] fecgov/openFEC#3947
- [x] fecgov/openFEC#4363
- [x] fecgov/openFEC#4305
- [x] fecgov/openFEC#4323
- [x] fecgov/openFEC#4349
- [x] fecgov/fec-accounts#251
- [x] fecgov/fec-accounts#254
