### ISSUE TITLE
Sub-epic: eregs strategic work

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-epics#181]
### Summary
- [ ] decide on strategy for eregs, e.g.,
   * eCFR approach
      - [ ] decide how to shut down and replace (and present on the front end) the content from eCFR in the FEC style
   * decouple parsing from front end and maintain what works
      - [ ] create new repo as a back-end to the existing `fec-eregs` repo, e.g., `fec-eregs-parser`, and move existing parsing functionality there for decoupled maintenance
      - [ ] update `fec-eregs-parser` documentation and streamline `fec-eregs` documentation and codebase once `fec-eregs-parser` is in place
- [ ] address formatting issues strategically, e.g., this can be handled in a way that makes use of repository-based xml sections for the CFR per https://eregs-parser.readthedocs.io/en/latest/quick_start.html#quick-start-with-modified-documents

**Comment by PaulClark2** [comment]
Closing for now.
