### ISSUE TITLE
Feature: Office of Inspector General pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-epics#184]
**What we’re after:** Make enhancements to the FEC’s OIG webpages. We want to make their section consistent with other government OIG pages while maintaining uniformity with the rest of FEC.gov.

**Why we’re after it:** OIG needs to be able to communicate their responsibilities and reports to the public in a manner that is easy to interpret.

## Tickets
- [x] fecgov/fec-cms#4055
- [x] fecgov/fec-cms#4318
- [x] fecgov/fec-cms#4099
- [x] fecgov/fec-cms#4037
- [x] fecgov/fec-cms#3993
- [x] fecgov/fec-cms#3946
- [x] fecgov/fec-cms#3787
- [x] fecgov/fec-cms#3930
- [x] fecgov/fec-cms#3902
