### ISSUE TITLE
Epic: Web Analytics / Google Tag Manager (GTM)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-epics#185]
**What we’re after:** Implement Tag Manager to better understand how our users are moving throughout the website and devote time to identifying key metrics that can better analyze how our data and content are being utilized.

**Why we’re after it:** Metrics tracking is a website goal to provide valuable insights for identifying and addressing user needs and pain points. Completion criteria: GTM is in use, all current GA events are being tracked, highest-value ‘new’ events are added to GTM

## Tickets
- [ ] fecgov/fec-cms#3918
- [ ] fecgov/openFEC#4702
- [x] fecgov/fec-cms#4666
- [x] fecgov/fec-cms#3948
- [x] fecgov/fec-cms#4031
- [x] fecgov/fec-cms#3160
- [x] fecgov/fec-cms#4104
- [x] fecgov/fec-cms#3906
- [x] fecgov/fec-cms#3973
- [x] fecgov/fec-cms#3971
- [x] fecgov/fec-cms#3972
- [x] fecgov/fec-cms#3905
