### ISSUE TITLE
Feature: Commissioner page improvements

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-epics#186]
**What we’re after:** Make template adjustments to give current and future Commissioners the option to organize their documents within a feed so that users can find relevant documents more easily.

**Why we’re after it:** We have heard from staff that external users have expressed difficulties with finding information on longer pages.

## Tickets
- [ ] fecgov/fec-cms#3869
- [x] fecgov/fec-cms#3982
- [x] fecgov/fec-cms#4006
- [x] fecgov/fec-cms#3947
