### ISSUE TITLE
Feature: Website status page

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-epics#187]
**What we’re after:** As a FEC product manager and developer, we need a strategy and workflow for a website status page in order to inform users of when there is a website incident. This work involves additional procurement and development.

**Why we’re after it:** To be able to easily communicate to the public and FEC stakeholders when there is an incident and its resolution.

## Tickets
- [ ] fecgov/fec-cms#4003
- [ ] fecgov/fec-cms#4062
- [ ] fecgov/fec-cms#4021
- [x] fecgov/fec-cms#3836
- [x] fecgov/fec-cms#4154
- [x] fecgov/fec-cms#3911
- [x] fecgov/fec-cms#4005
- [x] fecgov/fec-cms#4004
- [x] fecgov/fec-cms#4011
- [x] fecgov/fec-cms#3839
- [x] fecgov/fec-cms#3909
- [x] fecgov/fec-cms#3908
- [x] fecgov/fec-cms#3949
