### ISSUE TITLE
Feature: Leadership PAC sponsorship

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-epics#188]
**What we’re after:** As a concerned citizen, I want to see how officeholders are connected to leadership PACs, so that I can better understand how money is being raised and spent in races relevant to me.

**Why we’re after it:** To allow users to easily look up and find information on connected leadership PAC candidates.

## Tickets
- [x] fecgov/fec-cms#4270
- [x] fecgov/fec-cms#4253
- [x] fecgov/fec-cms#4061
- [x] fecgov/fec-cms#4057
- [x] fecgov/openFEC#4612
- [x] fecgov/openFEC#4675
- [x] fecgov/openFEC#4613
- [x] fecgov/openFEC#4587
- [x] fecgov/openFEC#4466
- [x] fecgov/openFEC#4586
- [x] fecgov/fec-cms#4032
- [x] fecgov/openFEC#4528
- [x] fecgov/openFEC#4475
