### ISSUE TITLE
Sub-epic: Migrate from transition.fec.gov to www.fec.gov

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#189]
**What we're after:**
Migrate all content from transition.fec.gov to the main www.fec.gov website. 

## Tickets
- [ ] fecgov/fec-cms#4110
- [ ] fecgov/fec-cms#3885
- [x] fecgov/fec-cms#5773
- [ ] fecgov/fec-pattern-library#212
- [ ] fecgov/fec-cms#5057
- [ ] fecgov/fec-cms#2753
- [ ] fecgov/fec-cms#2858
- [x] fecgov/fec-cms#3769
- [x] fecgov/fec-cms#4376
- [x] fecgov/fec-cms#6041
- [x] fecgov/fec-cms#6032
- [x] fecgov/fec-cms#5751
- [x] fecgov/fec-cms#5827
- [x] fecgov/fec-cms#5797
- [x] fecgov/fec-cms#5767
- [x] fecgov/fec-cms#5642
- [x] fecgov/fec-cms#5650
- [x] fecgov/fec-cms#5602
- [x] fecgov/fec-proxy#353
- [x] fecgov/fec-cms#5584
- [x] fecgov/fec-cms#5556
- [x] fecgov/fec-cms#5536
- [x] fecgov/fec-cms#5515
- [x] fecgov/fec-cms#5426
- [x] fecgov/fec-proxy#345
- [x] fecgov/fec-cms#5523
- [x] fecgov/fec-cms#5386
- [x] fecgov/fec-cms#5495
- [x] fecgov/fec-cms#5516
- [x] fecgov/fec-cms#5310
- [x] fecgov/fec-cms#5305
- [x] fecgov/fec-cms#3924
- [x] fecgov/fec-cms#4834
- [x] fecgov/fec-cms#5403
- [x] fecgov/fec-cms#5361
- [x] fecgov/fec-cms#5382
- [x] fecgov/fec-cms#5360
- [x] fecgov/fec-cms#5381
- [x] fecgov/fec-cms#5345
- [x] fecgov/fec-cms#5346
- [x] fecgov/fec-cms#4374
- [x] fecgov/fec-cms#5328
- [x] fecgov/fec-cms#5302
- [x] fecgov/fec-cms#5331
- [x] fecgov/fec-cms#5313
- [x] fecgov/fec-cms#5303
- [x] fecgov/fec-cms#5291
- [x] fecgov/fec-cms#5292
- [x] fecgov/fec-cms#5307
- [x] fecgov/fec-cms#5143
