### ISSUE TITLE
Sub-epic: Court case migration from transition.fec.gov to www.fec.gov

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#190]
**What we're after:** We need to migrate the large court case section from transition to www.fec.gov Wagtail CMS.

**Why we're after it:** So content staff can be on a single platform (Wagtail) to edit and add content to this section. 

## Tickets
- [x] fecgov/fec-cms#4191
- [x] fecgov/fec-cms#4334
- [x] fecgov/fec-cms#4204
- [x] fecgov/fec-cms#4245
- [x] fecgov/fec-cms#4287
- [x] fecgov/fec-cms#4236
- [x] fecgov/fec-cms#4212
- [x] fecgov/fec-cms#4210
- [x] fecgov/fec-cms#4214
- [x] fecgov/fec-cms#4201
- [x] fecgov/fec-cms#4205
- [x] fecgov/fec-cms#4207
- [x] fecgov/fec-cms#4206
- [x] fecgov/fec-cms#4098
- [x] fecgov/fec-cms#4070
- [x] fecgov/fec-cms#4202
- [x] fecgov/fec-cms#3937
- [x] fecgov/fec-cms#4121
- [x] fecgov/fec-cms#4120
- [x] fecgov/fec-cms#4118
- [x] fecgov/fec-cms#4165
- [x] fecgov/fec-cms#3938
- [x] fecgov/fec-cms#4164
- [x] fecgov/fec-cms#4133
- [x] fecgov/fec-cms#4119
- [x] fecgov/fec-cms#4063
