### ISSUE TITLE
Feature: Improve CMS/Proxy and eregs/Proxy settings, CI configuration

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-epics#191]
**What we're after and why we're after it:**
Improve CMS/Proxy settings and CI configuration. See https://github.com/fecgov/fec-accounts/issues/289 for better "why"

Big picture:
- Update to cf cli version 7 (CMS, API, eregs, pattern library)
- Implement rolling deployments (CMS, API, eregs, pattern library, fec-proxy (readme))
- Additional issues to be linked from fec-accounts
- Consider implementing Circle for Proxy for easier deployment
- 
## Tickets
- [x] fecgov/fec-eregs#500
- [x] fecgov/fec-proxy#199
- [x] fecgov/fec-proxy#164
- [x] fecgov/fec-proxy#140
- [x] fecgov/fec-proxy#188
- [x] fecgov/openFEC#3950
- [x] fecgov/openFEC#4668
- [x] fecgov/fec-cms#3153
- [x] fecgov/fec-cms#4138
- [x] fecgov/fec-eregs#536
- [x] fecgov/fec-eregs#456
- [x] fecgov/fec-cms#4135
- [x] fecgov/openFEC#4667
- [x] fecgov/fec-eregs#534
- [x] fecgov/openFEC#3597
- [x] fecgov/fec-accounts#289
- [x] fecgov/fec-accounts#313
- [x] fecgov/fec-accounts#315
- [x] fecgov/fec-accounts#316
- [x] fecgov/fec-accounts#317
- [x] fecgov/fec-accounts#318
- [x] fecgov/fec-accounts#322
- [x] fecgov/fec-accounts#323
- [x] fecgov/fec-accounts#325
- [x] fecgov/fec-accounts#326
- [x] fecgov/fec-accounts#327
- [x] fecgov/fec-accounts#328
- [x] fecgov/fec-accounts#329

**Comment by lbeaufort** [comment]
All issues complete and verified in production.
