### ISSUE TITLE
Sub-epic: Annual inflation adjustments to limits

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-epics#193]
## Summary
To better organize tickets relating to annual inflation adjustments, below is a list capturing considerations that need to be made each year:

### Every year
- Coordinated party expenditure limits
- Lobbyist bundling threshold
- Civil penalty inflation adjustments

### Every odd-numbered year
- Contribution limits

### Every four years
- Presidential public funding limits

## Tickets
- [x] fecgov/fec-cms#6054
- [x] fecgov/fec-cms#6068
- [x] fecgov/fec-cms#6053
- [x] fecgov/fec-cms#6055
- [x] fecgov/fec-cms#6056
- [x] fecgov/fec-proxy#391
- [x] fecgov/fec-cms#6043
- [x] fecgov/fec-cms#6044
- [x] fecgov/fec-cms#5549
- [x] fecgov/fec-cms#5543
- [x] fecgov/fec-cms#5547
- [x] fecgov/fec-cms#5548
- [x] fecgov/fec-cms#5542
- [x] fecgov/fec-cms#5049
- [x] fecgov/fec-cms#4881
- [x] fecgov/fec-cms#4999
- [x] fecgov/fec-cms#4357
- [x] fecgov/fec-cms#4224
- [x] fecgov/fec-cms#4225
- [x] fecgov/fec-cms#4228
- [x] fecgov/fec-cms#4229
- [x] fecgov/fec-cms#4279
- [x] fecgov/fec-cms#4278
- [x] fecgov/fec-cms#4284
- [x] fecgov/fec-cms#4277
- [x] fecgov/fec-cms#3420

**Comment by patphongs** [comment]
All issues in this epic completed, closing
