### ISSUE TITLE
Sub-epic: Party page improvements

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-epics#201]
Improvement of party pages is needed because many are too long and not user-friendly, and some are missing content or could be improved to be more like the candidate version.

We are going to do three things

- Add reporting examples
- Update current pages with minor improvements
- Convert the following pages into resource template pages:

-  Types of contributions to party committees: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/contributions-party-committees/ (create a resource template page using page's content first, then compare it to similar page in candidate section (https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/types-contributions/) to see if information should be blended together with candidate page)
-  Who can and can't contribute to a party committee: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/who-can-and-cant-contribute-party-committee/ (create a resource template page using page's content first, then compare it to similar page in candidate section (https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/who-can-and-cant-contribute/) to see if information should be blended together with candidate page)
-  Donations of Levin funds to state and local party committees: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/levin-funds-political-party-committees/
-  Volunteer activity for party committees: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/volunteer-activity-party/
-  Permissible use of corporate/labor resources and facilities by party committees: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/permissible-use-corporatelabor-resources-and-facilities-party-committees/ (determine if we should separate communications and facilities into separate pages. cross check with candidate versions. coordination could use a button to those pages)
-  Exempt party activities: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/exempt-party-activities/
-  Coordinated party expenditures: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/ (decide how much of the coordination section to keep vs. adding a button/link to the coordination page)
-  Making independent expenditures as a political party committee: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/making-independent-expenditures-political-party-committee/ (decide how much of the coordination section to keep vs. adding a button/link to the coordination page)
-  Definition of Federal Election Activity (FEA) | https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/definition-federal-election-activity-fea/

## Tickets
- [x] fecgov/fec-cms#4481
- [x] fecgov/fec-cms#4479
- [x] fecgov/fec-cms#4480
- [x] fecgov/fec-cms#4600
- [x] fecgov/fec-cms#4485
- [x] fecgov/fec-cms#4385
