### ISSUE TITLE
High-level PAC data (snapshot) on committee profile pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-epics#202]
**What we're after:** As a potential contributor to PACs and party committees, I want to better understand how my contributions may be used, so that I can make more informed decisions. 

## Tickets
- [ ] fecgov/fec-cms#4900
- [ ] fecgov/openFEC#4955
- [ ] fecgov/fec-cms#4748
- [ ] fecgov/fec-cms#4819
- [x] fecgov/fec-cms#4804
- [x] fecgov/fec-cms#4827
- [x] fecgov/fec-cms#4841
- [x] fecgov/fec-cms#4829
- [x] fecgov/fec-cms#4826
- [x] fecgov/openFEC#4928
- [x] fecgov/fec-cms#4828
- [x] fecgov/fec-cms#4793
- [x] fecgov/fec-cms#4718
- [x] fecgov/fec-cms#4759
- [x] fecgov/fec-cms#4671
- [x] fecgov/fec-cms#4672
- [x] fecgov/fec-cms#4749
- [x] fecgov/fec-cms#4716
- [x] fecgov/fec-cms#4717
- [x] fecgov/openFEC#4877
- [x] fecgov/openFEC#4876
- [x] fecgov/fec-cms#4670
- [x] fecgov/fec-cms#4673

<img width="915" alt="Screen Shot 2021-07-20 at 11 41 41 AM" src="https://user-images.githubusercontent.com/31663028/126354100-a4a0648c-96b4-43b3-bbc2-50fb334859a4.png">
<img width="160" alt="Screen Shot 2021-07-20 at 11 09 38 AM" src="https://user-images.githubusercontent.com/31663028/126348831-77497711-0d84-4b63-8aa1-c0ea0124e3d1.png">
<img width="340" alt="Screen Shot 2021-07-20 at 11 09 43 AM" src="https://user-images.githubusercontent.com/31663028/126348832-9d291f71-7d77-44a5-b7b6-afcedc850148.png">
![Screen Shot 2021-07-07 at 11 33 01 AM](https://user-images.githubusercontent.com/31663028/124789296-2c472000-df18-11eb-9d3b-9ad76b990cf1.png)

**Comment by patphongs** [comment]
Work has been iceboxed.
