### ISSUE TITLE
House and Senate data

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-epics#203]
**What we're after:** Give users the capability to organically discover House and Senate data.

**Why we're after it:** To seek out new opportunities for users to explore House and Senate data.

## Tickets
- [x] fecgov/fec-cms#4840
- [x] fecgov/fec-cms#4987
- [x] fecgov/fec-cms#4978
- [x] fecgov/fec-cms#4735
- [x] fecgov/fec-cms#4792
- [x] fecgov/fec-cms#4734
- [x] fecgov/fec-cms#4733
- [x] fecgov/fec-cms#4732
- [x] fecgov/fec-cms#4731
- [x] fecgov/fec-cms#4821
- [x] fecgov/fec-cms#4790
- [x] fecgov/fec-cms#4778
- [x] fecgov/fec-cms#4791
- [x] fecgov/fec-cms#4740
- [x] fecgov/fec-cms#4730
- [x] fecgov/fec-cms#4676
- [x] fecgov/fec-cms#4577
- [x] fecgov/fec-cms#4667
- [x] fecgov/fec-cms#4664
- [x] fecgov/fec-cms#4654

**Comment by patphongs** [comment]
Design work is complete, closing this epic
