### ISSUE TITLE
PAC and party raising and spending datatable

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-epics#204]
**What we're after:** As a researcher, I want an easier way to access and search for top-level finances across all PACs and party committees, so that I can gather the most relevant data for my research.

## Tickets
- [x] fecgov/fec-cms#5471
- [x] fecgov/fec-cms#4879
- [x] fecgov/fec-cms#4878
- [x] fecgov/openFEC#4917
- [x] fecgov/fec-cms#4873
- [x] fecgov/fec-cms#4868
- [x] fecgov/openFEC#4947
- [x] fecgov/openFEC#4946
- [x] fecgov/fec-cms#4805
- [x] fecgov/fec-cms#4765
- [x] fecgov/fec-cms#4769
- [x] fecgov/fec-cms#4690
- [x] fecgov/fec-cms#4737
- [x] fecgov/fec-cms#4687
- [x] fecgov/openFEC#4879
- [x] fecgov/openFEC#4878
- [x] fecgov/fec-cms#4686
- [x] fecgov/openFEC#4886
- [x] fecgov/fec-cms#4688
- [x] fecgov/fec-cms#4675
- [x] fecgov/fec-cms#4674
- [x] fecgov/fec-cms#4689
- [x] fecgov/openFEC#4872
- [x] fecgov/fec-cms#4651
- [x] fecgov/openFEC#4873
- [x] fecgov/openFEC#4871

**Current designs**
![Data table](https://user-images.githubusercontent.com/31663028/122299236-b8db6100-cecb-11eb-8cb0-da8a2b23286e.jpg)
![Details panel](https://user-images.githubusercontent.com/31663028/122295704-8891c380-cec7-11eb-9c3f-85406e3fadb9.jpg)

**Comment by patphongs** [comment]
Work is complete
