### ISSUE TITLE
Webpack upgrade (3 → 5)

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-epics#207]
What we’re after: Upgrade our cms builder/bundler, Webpack, from 3 to 5.

Why we’re after it: We're a couple versions behind and the lag is limiting upgrades to other packages.

Related meeting agenda and outcome: Meeting notes: https://docs.google.com/document/d/16kfnqfj-urLl5Gww-RsaYldIKsGRtQc3okuaWka8fyg/edit#

## Tickets
- [x] fecgov/fec-cms#4908
- [ ] fecgov/fec-cms#4906
- [ ] fecgov/fec-cms#4907
- [x] fecgov/fec-cms#2708
