### ISSUE TITLE
Sub-epic: Candidate Guide 2021 Updates

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-epics#208]
This will cover all tickets related to incorporating the updates made in the 2021 Candidate Guide

## Tickets
- [x] fecgov/fec-cms#5379
- [x] fecgov/fec-cms#5380
- [x] fecgov/fec-cms#5170
- [x] fecgov/fec-cms#5202
- [x] fecgov/fec-cms#5201
- [x] fecgov/fec-cms#5169
- [x] fecgov/fec-cms#4924
- [x] fecgov/fec-cms#5160
- [x] fecgov/fec-cms#5120
- [x] fecgov/fec-cms#5101
- [x] fecgov/fec-cms#5083
- [x] fecgov/fec-cms#5074
- [x] fecgov/fec-cms#5013
- [x] fecgov/fec-cms#4955
- [x] fecgov/fec-cms#4917
- [x] fecgov/fec-cms#4945
- [x] fecgov/fec-cms#4886

**Comment by patphongs** [comment]
All issues completed, closing epic
