### ISSUE TITLE
House and Senate data overview pages

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#213]
**What we’re after:** Give users the capability to organically discover house and senate data.

**Why we’re after it:** To seek out new opportunities for users to explore house and senate data.

### Sub Epics
- [ ] fecgov/fec-epics#217
- [ ] fecgov/fec-epics#214
- [x] fecgov/fec-epics#215

## Tickets
- [x] fecgov/fec-cms#5088
- [x] fecgov/fec-cms#5104
- [x] fecgov/fec-cms#5592
- [x] fecgov/fec-cms#5266
- [x] fecgov/fec-cms#5182
- [x] fecgov/openFEC#5026
- [x] fecgov/fec-cms#5087
- [x] fecgov/fec-cms#5022

![House overview page](https://user-images.githubusercontent.com/31663028/151426803-e6a550d1-99d4-4a95-9fbf-1a9d2e8fcccf.jpg)
