### ISSUE TITLE
Contributions across time

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#214]
![Screen Shot 2022-01-11 at 2 45 56 PM](https://user-images.githubusercontent.com/12799132/149151601-c2022b2d-704a-45dd-a97e-17af01364b49.png)

## Tickets
- [ ] fecgov/openFEC#5055
- [x] fecgov/fec-cms#5090
- [x] fecgov/fec-cms#5034
- [x] fecgov/fec-cms#5021
- [x] fecgov/openFEC#5028
- [x] fecgov/fec-cms#5017
- [x] fecgov/fec-cms#5031
