### ISSUE TITLE
All House and Senate totals (by the numbers)

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#215]
![Screen Shot 2022-01-12 at 8 48 21 AM](https://user-images.githubusercontent.com/12799132/149152414-6c7e951b-e70a-4ed1-b77a-abbf0f00869d.png)
![Screen Shot 2022-01-12 at 8 48 14 AM](https://user-images.githubusercontent.com/12799132/149152415-73ca9b84-b1c8-454c-a772-ec154e6c4f6f.png)

## Tickets
- [x] fecgov/fec-cms#5215
- [x] fecgov/fec-cms#5089
- [x] fecgov/openFEC#5039
- [x] fecgov/openFEC#5069
- [x] fecgov/openFEC#5029
- [x] fecgov/fec-cms#5018

**Comment by patphongs** [comment]
All tickets completed, closing epic
