### ISSUE TITLE
All elections totals table

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#216]
![Screen Shot 2022-01-11 at 2 29 48 PM](https://user-images.githubusercontent.com/12799132/149152615-40c17710-ef2a-45ae-86af-b60e8080ac45.png)

## Tickets
- [x] fecgov/fec-cms#5277
- [x] fecgov/fec-cms#5278
- [x] fecgov/fec-cms#5734
- [x] fecgov/openFEC#5139
- [x] fecgov/fec-cms#5785
- [x] fecgov/openFEC#5163
- [x] fecgov/openFEC#5162
- [x] fecgov/openFEC#5161
- [x] fecgov/openFEC#5164
- [x] fecgov/fec-cms#5091
- [x] fecgov/openFEC#5027
- [x] fecgov/fec-cms#5131
