### ISSUE TITLE
Election search page census updates

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-epics#218]
**What we're after:**
This epic covers the work required to update our election search page to accurately list new district election profile pages and new district maps. We expect to do the bulk of our work once we receive toolkits from Census. 

## Tickets
- [x] fecgov/fec-cms#5207
- [x] fecgov/fec-cms#5040
- [x] fecgov/fec-cms#5210
- [x] fecgov/fec-cms#5204
- [x] fecgov/fec-cms#5191
- [x] fecgov/openFEC#5031
- [x] fecgov/fec-cms#5027
