### ISSUE TITLE
Sub-epic: Form 1 Update

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-epics#219]
This epic contains tickets related to the updating of Form 1 approved in 2022 by the Commission. We will plan on timing this work to coincide with the release of the updated form to electronic filers.

## Tickets
- [x] fecgov/fec-cms#5212
- [x] fecgov/openFEC#5133
- [x] fecgov/fec-cms#5217
- [x] fecgov/fec-cms#5135
- [x] fecgov/fec-cms#5133
- [x] fecgov/fec-cms#5172
- [x] fecgov/fec-cms#5134
- [x] fecgov/fec-cms#5213
- [x] fecgov/fec-cms#5121
- [x] fecgov/fec-cms#5173
- [x] fecgov/fec-cms#5177

**Comment by patphongs** [comment]
All work completed, closing epic
