### ISSUE TITLE
Sub-epic: MUR search

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-epics#221]
**What we're after:**
As a developer, I want to be able to upgrade the legal web search application so that I can create useful functionality and confidently build upon our legal web application.

### Completion criteria
- [ ] Conducted research and built prototypes to utilize the elasticsearch DSL. 
- [ ] Made upgrades to the legal web search app

### Redesigned MUR search
![MUR-Document with lines](https://user-images.githubusercontent.com/31663028/176271235-30738800-3928-4619-811d-e03a759028c4.png)

## Tickets
- [ ] fecgov/fec-cms#5257
- [ ] fecgov/fec-cms#5262
- [ ] fecgov/fec-cms#5263
- [x] fecgov/fec-cms#5264
- [ ] fecgov/fec-cms#5265
- [x] fecgov/openFEC#5153
- [x] fecgov/openFEC#5155
- [x] fecgov/openFEC#5156
- [x] fecgov/fec-cms#5261
- [x] fecgov/openFEC#5152
- [x] fecgov/openFEC#5121
- [x] fecgov/fec-cms#5423
- [x] fecgov/fec-cms#5357
- [x] fecgov/fec-cms#5258
- [x] fecgov/fec-cms#5255
- [x] fecgov/fec-cms#5256
- [x] fecgov/openFEC#5119

**Comment by patphongs** [comment]
@JonellaCulmer Can you explain what is expected in the "Disposition" field of the search results? 

This is an example [API call](https://api.open.fec.gov/v1/legal/search?hits_returned=20&type=murs&from_hit=0&q=filings&api_key=DEMO_KEY) based on the search term "filings" and dispositions is a list of multiple dispositions, which we can group together. So if we use the first MUR in the list as an example, 7958, do you expect dispositions to look like this:

`Dispositions: Conciliation-PPC (1 respondent); Dismissed-Other (9 respondents)`

**Comment by JonellaCulmer** [comment]
@patphongs Yes, exactly what I had imagined. If we're able to calculate a count similar to the number of results for the keyword search. If you'd like me to open a separate ticket, I can do that and add it to a future sprint. PI 19?
