### ISSUE TITLE
Website accessibility

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-epics#223]
**What we're after:**
This epic tracks work related to accessibility across FEC.gov. As issues are identified and documented, we will track them here and will be able to evaluate our progress overtime. This can potentially help us to identify gaps in our observations and development work. 

## Tickets
- [x] fecgov/fec-cms#6098
- [x] fecgov/fec-cms#6113
- [ ] fecgov/fec-cms#6114
- [ ] fecgov/fec-cms#6115
- [x] fecgov/fec-cms#6029
- [x] fecgov/fec-cms#6029
- [x] fecgov/fec-cms#6091
- [x] fecgov/fec-cms#2583
- [x] fecgov/fec-cms#6092
