### ISSUE TITLE
Wagtail upgrade

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#225]
**What we’re after:** As a content editor, I need to be able to edit the website content reliably and efficiently so that I can continue to provide useful, relevant, and up-to-date information on our website.

## Tickets
- [x] fecgov/fec-cms#6094
- [x] fecgov/fec-cms#5580
- [x] fecgov/fec-cms#5583
- [x] fecgov/fec-cms#5544
- [x] fecgov/fec-cms#5545
- [x] fecgov/fec-cms#5519
- [x] fecgov/fec-cms#5499
- [x] fecgov/fec-cms#5498
- [x] fecgov/fec-cms#5500

**Comment by patphongs** [comment]
Work is complete, closing
