### ISSUE TITLE
Search.gov indexing

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#226]
**What we’re after:** Migrate to using sitemap based indexing for our website search. This will help to automate the process and eliminate the need to manually index the site.

**Why we’re after it:** We are currently using the i14y drawer to index our content for our global search. However, this API has been deprecated and we have found it can be unreliable when re-indexing.

## Tickets
- [ ] fecgov/fec-cms#5522
- [x] fecgov/fec-cms#5501
- [x] fecgov/fec-cms#5692
- [x] fecgov/fec-cms#5499
