### ISSUE TITLE
Presidential map

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#227]
**What we’re after:** With the upcoming presidential election, we need to re-activate our presidential map with updated data, including 2024. We also should add data for 2012 and 2008.

We may have more presidential data when we receive 2023 Q1 filings closer to April 15.

Notes for future tickets:
- [x]  Create 2024 database tables in Oracle (database)
- [x]   Perform necessary postgres database work
- [x] Perform necessary API work
- [x]  Add 2024 presidential data to the map
- [x]  Remove the bubble option from the map
- [x]  QA and ensure presidential candidates who meet the threshold are there on the map
- [x] Add 2008 and 2012 presidential data to the database and API
- [x] Add 2008 and 2012 presidential data to the map

## Tickets
- [x] fecgov/fec-cms#5780
- [x] fecgov/openFEC#5363
- [x] fecgov/fec-cms#5701
- [x] fecgov/fec-cms#5666
- [x] fecgov/openFEC#5362
- [x] fecgov/fec-cms#5641

**Comment by patphongs** [comment]
Work complete, closing
