### ISSUE TITLE
Data table for debts

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#228]
**What we’re after:** We need to finish up our work to add itemized debts (schedule D) data and data table pages so users could browse, filter and export the data.

## Tickets
- [x] fecgov/fec-cms#5660
- [x] fecgov/fec-cms#4413
- [x] fecgov/fec-cms#5816
- [x] fecgov/fec-cms#5778
- [x] fecgov/fec-cms#5819
- [x] fecgov/openFEC#5513
- [x] fecgov/fec-cms#5766
- [x] fecgov/fec-cms#5658
- [x] fecgov/fec-cms#5659
- [x] fecgov/openFEC#5368
- [x] fecgov/openFEC#4758
- [x] fecgov/fec-cms#4351

**Comment by patphongs** [comment]
This datatable is now [live](https://www.fec.gov/data/debts/), closing.
