### ISSUE TITLE
Updates to election search based on reapportionment

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-epics#229]
**What we are after:**
Searches of our election data return the most current congressional districts in the map and by zip code.

Notes: Take a look at shape files https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html

## Tickets
- [x] fecgov/fec-cms#6080
- [x] fecgov/openfec#5693
- [x] fecgov/fec-cms#4290
- [x] fecgov/openFEC#4727
- [x] fecgov/fec-cms#5663
- [x] fecgov/fec-cms#5656
- [x] fecgov/fec-cms#5655
- [x] fecgov/fec-cms#1942

**Comment by patphongs** [comment]
All issues completed, closing epic
