### ISSUE TITLE
Sub-epic: Citizen and voting pages improvements

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-epics#230]
Sub-epic for improvements to pages linked off of 
https://www.fec.gov/introduction-campaign-finance/election-and-voting-information/ 

Analytics reveal that citizens are looking for this information and finding our citizens’ pages. However, the pages need some improvement. The wording should indicate this is not information the FEC is responsible for and that states certify election results. There’s overlap with the election day information page. This will involve working with public records. Could we work off this page: https://www.fec.gov/introduction-campaign-finance/?

Also, given the analytics show interest in this, do we want to reconsider where these pages live and how they are organized? 

## Tickets
- [ ] fecgov/fec-cms#5904
- [ ] fecgov/fec-cms#5953
- [ ] fecgov/fec-cms#5763
- [ ] fecgov/fec-cms#5762
- [ ] fecgov/fec-cms#5821
- [ ] fecgov/fec-cms#5761
- [ ] fecgov/fec-cms#5760
- [ ] fecgov/fec-cms#5759
- [ ] fecgov/fec-cms#5758
- [ ] fecgov/fec-cms#5728

**Comment by patphongs** [comment]
All issues for this sub-epic are complete, closing
