### ISSUE TITLE
Unverified filer datatable

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-epics#232]
**What we’re after:** Develop a searchable system for unverified filer candidates and committees to meet disclosure requirements and provide easier access to this data.

## Tickets
- [ ] fecgov/fec-cms#5707
- [ ] fecgov/fec-cms#5802
- [ ] fecgov/fec-cms#5801
- [ ] fecgov/fec-cms#5784
