### ISSUE TITLE
eRegs Migration to eCFR

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-epics#235]
**What we’re after:** As a legal professional, I want to migrate from using the FEC’s eRegulations application to using the eCFR (Electronic Code of Federal Regulations) for better features and efficiency in legal updates.

**Why we’re after it:** eRegs is consistently behind eCFR, resulting in out-of-date information. Up-to-date information is sometimes hard to find. 

## Tickets
- [x] fecgov/fec-cms#6167
- [x] fecgov/fec-cms#6095
- [x] fecgov/fec-proxy#393
- [x] fecgov/fec-cms#6127
- [x] fecgov/fec-cms#6089
- [x] fecgov/fec-eregs#826

**Comment by patphongs** [comment]
This has been completed
