### ISSUE TITLE
Create raising breakdown visualization page

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#29]
So that users can get a high-level breakdown of the money raised in an election cycle, build out the data visualizations for raising data. 

---

This epic entails building the Raising Breakdown page [as designed here](https://gsa.invisionapp.com/share/QX85OU039#/screens/178500261).

Broadly, the page has three main components:
## Who's raising the most

A display of the candidates and committees who've raised the most money:
![image](https://cloud.githubusercontent.com/assets/1696495/19176052/0c0c49ac-8bf1-11e6-8097-f63d2873dd75.png)
## Where contributions are coming from

A display of how much money groups have raised via individual contributions from different states:
![image](https://cloud.githubusercontent.com/assets/1696495/19176069/34584e56-8bf1-11e6-9a82-d29cf30f5820.png)
## The size of contributions

A display of the amount raised via different sized contributions:
![image](https://cloud.githubusercontent.com/assets/1696495/19176080/43ba7eb4-8bf1-11e6-84ac-c9d06a98354a.png)

Users should be able to toggle each visualization by the type of entity, and the user should be able to change time period for the entire page:
![image](https://cloud.githubusercontent.com/assets/1696495/19176099/715317d2-8bf1-11e6-8fa6-7a1ce88bae6c.png)

---

The criteria for the filtering for these charts was [fleshed out in this comment](https://github.com/18F/openFEC/issues/1620#issuecomment-218630091)

## Tickets
- [x] fecgov/openFEC#1999
- [x] fecgov/openFEC#1680
- [x] fecgov/openFEC-web-app#1626
- [x] fecgov/openFEC-web-app#1647
- [x] fecgov/openFEC-web-app#1655
- [x] fecgov/openFEC-web-app#1686
- [x] fecgov/openFEC-web-app#1855
- [x] fecgov/openFEC-web-app#1973

**Comment by LindsayYoung** [comment]
Data notes @jontours and @ccostino please tell me if you have better ideas.

chart 1 "Who is raising the most" has an endpoint ✅ 

chart 2 "Where are contributions coming from":
- use ofec_sched_a_aggregate_state_tmp join by committee_id to ofec_committee_detail_tmp, the groupings are going to be the same ad the large_aggragates.sql that I am working on
- make sure dependency is mapped in webservices/flow.py 

chart 3 "The size of contributions"
- use ofec_sched_a_aggregate_size_tmp join by committee_id to ofec_committee_detail_tmp, the groupings are going to be the same ad the large_aggragates.sql that I am working on
- make sure dependency is mapped in webservices/flow.py

**Comment by ccostino** [comment]
I think this looks okay, @LindsayYoung, nothing else is coming to mind for me here.

**Comment by noahmanger** [comment]
Thanks for the notes. My question now is where does that leave us as far as feasibility of developing these endpoints? Is it something we're ready to tackle? Or do these solutions pose the same problems you were concerned about?

**Comment by LindsayYoung** [comment]
I think they are do-able, they aren't broken down by month- so we can build on existing views. That is better than what I feared. How many we get done depends on how many other things we are doing concurrently.
