### ISSUE TITLE
Improve access to report data

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#3]
So that users can get access the data from all reports (both raw efiling and processed data) add more ways for the report data to be viewable, such as HTML views, valid CSVs and .fec files.

## Tickets
- [x] fecgov/openFEC#2390
- [x] fecgov/openFEC#2000
- [x] fecgov/openFEC#1882
- [x] fecgov/openFEC#1954
- [x] fecgov/openFEC-web-app#1450
- [x] fecgov/openFEC-web-app#1551
- [x] fecgov/openFEC-web-app#1552
- [x] fecgov/openFEC-web-app#1553
- [x] fecgov/openFEC-web-app#1554
- [x] fecgov/openFEC-web-app#1610
