### ISSUE TITLE
Create spending breakdown page

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#30]
So that users can get a high-level breakdown of the money _spent_ in an election cycle, build out the data visualizations for spending data. 

---

This epic entails building the Spending Breakdown page [as designed here](https://gsa.invisionapp.com/share/QX85OU039#/screens/178500265).

Broadly, the page has three main components:
## Who's raising the most

A display of the candidates and committees who've spent the most money:
![image](https://cloud.githubusercontent.com/assets/1696495/19176137/df88c0a8-8bf1-11e6-8a81-ff480de16847.png)
## What's spent on day-to-day activities

A display of how much money groups spend on different types of operating expenditures:
![image](https://cloud.githubusercontent.com/assets/1696495/19176149/f3ac205c-8bf1-11e6-9307-df5b147ad3fe.png)
## Where money is spent to support and oppose a candidate

A display of the amount of independent expenditures made per state:
![image](https://cloud.githubusercontent.com/assets/1696495/19176160/08c29f16-8bf2-11e6-9cf3-21f284f44447.png)

Users should be able to toggle each visualization by the type of entity, and the user should be able to change time period for the entire page:
![image](https://cloud.githubusercontent.com/assets/1696495/19176168/1a24fa38-8bf2-11e6-9ee1-86a64985be64.png)

---

The details for the data for all of these charts was fleshed out in this issue here: https://github.com/18F/openFEC-web-app/issues/1188#issuecomment-218631943

## Tickets
- [x] fecgov/openFEC#1997
- [x] fecgov/openFEC#1680
- [x] fecgov/openFEC-web-app#1627
- [x] fecgov/openFEC-web-app#1656
- [x] fecgov/openFEC-web-app#1686
- [x] fecgov/openFEC-web-app#1855

**Comment by LindsayYoung** [comment]
Data notes @jontours and @ccostino please tell me if you have better ideas.

chart 1 "Who is spending the most" has an endpoint ✅

chart 2 - 
ofec_sched_b_aggregate_purpose_tmp, I think this will result in a long list with a very long tail. 
(The dropdown option here has presidential candidates, that is fine we just want to be consistent across)

chart 3 - Want to be clear what we mean by "where money is spent to support or oppose" I think we can we use the state of the candidate for this. We will want to use ofec_sched_e_aggregate_candidate_mv_tmp, join on candidate id to candidate state and then we can only to House and Senate- which is what they [currently have](http://fec.gov/disclosureie/ienational.do;jsessionid=D9D96275BA50510EE990D95B0B8145E4.worker1)

**Comment by ccostino** [comment]
Same here; nothing else is coming to mind for me.  Thanks, @LindsayYoung!
