### ISSUE TITLE
Unexpected Search Results

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#34]
The following have been reported by internal FEC users regarding unexpected search results.
- [x] `109.20` does not show up as a regulation in the search results
- [ ] `2015-01` results in over 1300 results
- [x] `"2015-01"` does not result in a hit 
- [ ] `30101(4`) does not result in section 30101 showing up as a result for statutes

see below comments for resulting outcomes for above.
