### ISSUE TITLE
eRegs bug fixes and enhancements

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#37]
## Tickets
- [x] fecgov/fec-eregs#10
- [x] fecgov/fec-eregs#30
- [x] fecgov/fec-eregs#30
- [x] fecgov/fec-eregs#20
- [x] fecgov/fec-eregs#20
- [x] fecgov/fec-eregs#20
- [x] fecgov/fec-eregs#20
- [x] fecgov/fec-eregs#20
- [x] fecgov/fec-eregs#20
- [x] fecgov/fec-eregs#12
- [x] fecgov/fec-eregs#16
- [x] fecgov/fec-eregs#17
- [x] fecgov/fec-eregs#19
- [x] fecgov/fec-eregs#14
- [x] fecgov/fec-eregs#18
- [x] fecgov/fec-eregs#19
- [x] fecgov/fec-eregs#9
- [x] fecgov/fec-eregs#17
- [x] fecgov/fec-eregs#14
- [x] fecgov/fec-eregs#26
- [x] fecgov/fec-eregs#20
- [x] fecgov/fec-eregs#16
- [x] fecgov/fec-eregs#91
- [x] fecgov/fec-eregs#17
- [x] fecgov/fec-eregs#17
