### ISSUE TITLE
MURs - First Release

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#38]
## Tickets
- [x] fecgov/fec-eregs#309
- [x] fecgov/openFEC#2053
- [x] fecgov/openFEC#2069
- [x] fecgov/fec-eregs#106
- [x] fecgov/fec-eregs#297
- [x] fecgov/fec-eregs#293
- [x] fecgov/fec-eregs#291
- [x] fecgov/fec-eregs#269
- [x] fecgov/fec-eregs#270
- [x] fecgov/fec-eregs#251
- [x] fecgov/fec-eregs#263
- [x] fecgov/fec-eregs#49
- [x] fecgov/fec-eregs#264
- [x] fecgov/fec-eregs#224
- [x] fecgov/fec-eregs#255
- [x] fecgov/fec-eregs#233
- [x] fecgov/fec-eregs#268
- [x] fecgov/fec-eregs#226
- [x] fecgov/fec-eregs#225
- [x] fecgov/fec-eregs#220
- [x] fecgov/fec-eregs#227
- [x] fecgov/fec-eregs#222
- [x] fecgov/fec-eregs#252
- [x] fecgov/fec-eregs#253
- [x] fecgov/fec-eregs#243
- [x] fecgov/fec-eregs#223
- [x] fecgov/openFEC-web-app#1651
- [x] fecgov/openFEC-web-app#1675
- [x] fecgov/openFEC-web-app#1689
- [x] fecgov/openFEC-web-app#1704

**Comment by adrianwebb** [comment]
Needs to be reviewed by FEC legal folks before release
