### ISSUE TITLE
Technical debt

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#39]
## Tickets
- [x] fecgov/openFEC#5217
- [x] fecgov/fec-eregs#26
- [x] fecgov/fec-eregs#292
- [x] fecgov/fec-eregs#166
- [x] fecgov/fec-eregs#169
- [x] fecgov/fec-eregs#96
- [x] fecgov/fec-eregs#278
