### ISSUE TITLE
Short-term improvements to candidate pages

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#4]
## Tickets
- [x] fecgov/openFEC-web-app#1400
- [x] fecgov/openFEC-web-app#1402
- [x] fecgov/openFEC-web-app#1405
- [x] fecgov/openFEC-web-app#1406
- [x] fecgov/openFEC-web-app#1407
- [x] fecgov/openFEC-web-app#1408
- [x] fecgov/openFEC-web-app#1410
- [x] fecgov/openFEC-web-app#1455
- [x] fecgov/openFEC-web-app#1458
- [x] fecgov/openFEC-web-app#1584
