### ISSUE TITLE
Retros

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#40]
Stories that are coming out of our retrospective feedback

## Tickets
- [x] fecgov/fec-eregs#184
- [x] fecgov/fec-eregs#185
- [x] fecgov/fec-eregs#53
- [x] fecgov/fec-eregs#50
- [x] fecgov/fec-eregs#45
- [x] fecgov/fec-eregs#56

**Comment by adrianwebb** [comment]
Is there any reason this should still be open @porta-antiporta ?  Looks like all the underlying issues have been closed but not sure if this was intended for any more retros.

**Comment by noahmanger** [comment]
I'm going to close this since all the issues have been resolved and it doesn't seem to be used anymore.
