### ISSUE TITLE
Onboard and train FEC content management team

### ISSUE THREAD

**Issue by emileighoutlaw** [fecgov/fec-epics#44]
## Tickets
- [x] fecgov/fec-cms#558
- [x] fecgov/fec-cms#559
- [x] fecgov/fec-cms#560
