### ISSUE TITLE
Compliance content

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#46]
**What we’re after:** The main architecture of a streamlined compliance section that reorganizes the existing compliance content in a way that better meets user needs and reduces duplication. We want to include as much of the actual content as possible, but recognize that since it’s such a big task we need for begin by getting the architecture in place so that if content does need to live on the legacy site, we have a way to get to it. This should also address the needs currently served by the compliance map, and integrate them into a cohesive experience. 

**Why we’re after it:** The regulated community has the highest stakes when it comes to using the FEC’s website. These pages are among the most important help candidates and committees who are conducting day-to-day activities. Understanding requirements and being able to answer specific questions about compliance can be the difference between a campaign operating within the law and a campaign unintentionally violating the law.

## Tickets
- [x] fecgov/fec-cms#110
- [x] fecgov/fec-cms#767
- [x] fecgov/fec-cms#109
- [x] fecgov/fec-cms#104
- [x] fecgov/fec-cms#112
- [x] fecgov/fec-cms#114
- [x] fecgov/fec-cms#103
- [x] fecgov/fec-cms#782
- [x] fecgov/fec-cms#744
- [x] fecgov/fec-cms#101
- [x] fecgov/fec-cms#956
- [x] fecgov/fec-cms#763
- [x] fecgov/fec-cms#884
- [x] fecgov/fec-cms#776
- [x] fecgov/fec-cms#869
- [x] fecgov/fec-cms#612
- [x] fecgov/fec-cms#783
- [x] fecgov/fec-cms#727
- [x] fecgov/fec-cms#766
- [x] fecgov/fec-cms#745
- [x] fecgov/fec-cms#780
- [x] fecgov/fec-cms#768
- [x] fecgov/fec-cms#741
- [x] fecgov/fec-cms#671
- [x] fecgov/fec-cms#630
- [x] fecgov/fec-cms#670
- [x] fecgov/fec-cms#699
- [x] fecgov/fec-cms#698
- [x] fecgov/fec-cms#682
- [x] fecgov/fec-cms#568
- [x] fecgov/fec-cms#631
- [x] fecgov/fec-cms#632
- [x] fecgov/fec-cms#599
- [x] fecgov/fec-cms#566
- [x] fecgov/fec-cms#559
