### ISSUE TITLE
Onboard and empower content management team

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#47]
This is an epic for capturing the work we're doing to onboard the content management team and get them rolling. This includes things like getting them set up with systems, training them to use the tools, as well as building out principles and guides to shape the work ahead.

## Tickets
- [x] fecgov/fec-cms#558
- [x] fecgov/fec-cms#555
- [x] fecgov/fec-cms#559
- [x] fecgov/fec-cms#560

**Comment by noahmanger** [comment]
Aaaand just realized @emileighoutlaw already made an epic for this https://github.com/18F/fec-epics/issues/44

**Comment by emileighoutlaw** [comment]
I appreciate that we both thought to create and almost identically name this epic, though 😁
