### ISSUE TITLE
MUR Refinements

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#48]
## Tickets
- [x] fecgov/fec-eregs#296
- [x] fecgov/fec-eregs#300
- [x] fecgov/fec-eregs#295
- [x] fecgov/openFEC#2055
- [x] fecgov/openFEC#1996
- [x] fecgov/fec-eregs#294
- [x] fecgov/openFEC-web-app#1654
