### ISSUE TITLE
Improve UI consistency throughout

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#49]
As we build out new features, we will have various patterns and stylistic decisions diverge. This epic is for capturing the work that we need to do to keep things polished and consistent.

## Tickets
- [x] fecgov/fec-cms#625
- [x] fecgov/fec-cms#570
- [x] fecgov/fec-cms#588
- [x] fecgov/fec-cms#531
- [x] fecgov/fec-cms#544
- [x] fecgov/fec-cms#586
- [x] fecgov/fec-cms#585
- [x] fecgov/fec-cms#587
- [x] fecgov/fec-cms#563
- [x] fecgov/openFEC-web-app#1555
- [x] fecgov/openFEC-web-app#1648
- [x] fecgov/openFEC-web-app#1795
