### ISSUE TITLE
Short-term improvements to committee pages

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#5]
## Tickets
- [x] fecgov/openFEC#1835
- [x] fecgov/openFEC#1834
- [x] fecgov/openFEC-web-app#1448
- [x] fecgov/openFEC-web-app#1465
- [x] fecgov/openFEC-web-app#1466
- [x] fecgov/openFEC-web-app#1472
- [x] fecgov/openFEC-web-app#1473
