### ISSUE TITLE
Migrate code and data to the new Cloud.gov

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#51]
This is a placeholder epic for the tasks that will be involved in migrating our code and data to the new cloud.gov infrastructure.

Known issues:
- [ ] Move OpenFEC API
- [ ] Move openFEC-web-app 
- [ ] Move FEC-CMS
- [ ] Move CMS database
- [ ] Move legal data

Eventually we will need to move our RDS boxes, but that needs to wait until we have a way for FEC to connect to them.

cc @LindsayYoung @adrianwebb

**Comment by noahmanger** [comment]
Here's @LindsayYoung 's initial brain dump of everything that we need to do to move to the new cloud.gov infrastructure:

Moving to gov cloud
- create FEC org with dev staging and prod spaces (we have not used feature too much lately)
- create cf service for secrets
- move s3 buckets (data downloads, legal and content)
  - give pat creds to the new content bucket
- cms
  - move db and upgrade to postgres (James Scott said he might help with this)
  - use built-in routing feature instead of the proxy app
  - make sure new relic is going
  - make sure deployment works with the invoke task
  - make sure deployment works by travis
- API
  - move and upgrade elastic search
  - move celery
  - move celery beat
  - use built-in routing feature instead of the proxy app
  - make sure we can maintain our integration with data.api.gov 
  - make sure we have access to our RDS boxes 
  - make sure new relic is going
  - make sure there is access to mandril for error emails
  - make sure deployment works with the invoke task
  - make sure deployment works by travis
- webapp
  - use built-in routing feature instead of the proxy app
  - make sure new relic is going
  - make sure github is reachable by the app for feedback
  - make sure ethnio is reachable by the app for feedback
  - make sure deployment works with the invoke task
  - make sure deployment works by travis
- fec eregs
  - move and upgrade elastic search
  - make sure new relic is going
  - make sure deployment works
- fec style
  - not sure for this

ATO tasks:
- upgrade Django on the cms and eregs
- set X-Frame-Options Header (from concorse, possible false positive)
- add gemnysium to cms
