### ISSUE TITLE
Improve candidate and committee pages

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#56]
## Pre-flip:
**What we’re after:** We should make continued improvements to the candidate pages based on the new designs in order to address the most pressing UX issues on those pages. We should get as much of this easy work done before the site flip as possible, saving the more complex changes for after. 

**Why we’re after it:** Users have expressed confusion around how to find financial information from candidate pages and the new designs address this confusion. Additionally, making candidate pages more usable is crucial for addressing outstanding concerns about the new site.

## Post-flip:
**What we’re after:** Building out the remaining data and visualizations on the candidate and committee pages to finish implementing the new designs.

**Why we’re after it**: People need to be able to get to more detailed information on candidate pages, need to see more subtotals and totals, and need easier access to itemized data from these pages. 

---
## PI 1 description:

**What we’re after:** We want improved candidate pages that address several issues that have been surfaced via usability testing and site feedback. This will involve surfacing more data on candidate pages and potentially redesigning aspects of the interface to make the information easier to parse. We also want to improve the committee pages in order to address several issues that have surfaced in usability testing and site feedback, including improving the way that financial summaries are displayed, improving the filings table and ensuring that the aggregate totals we generate are accurate and stable.

**Why we’re after it:** Users expect to find detailed financial totals for raising and spending data for all of a candidate’s authorized committees on the candidate’s page. Users have also expressed confusion over the time periods included on a page. Last, users want more high-level totals (such as the total amount of IEs for or against a candidate, in addition to the per-committee aggregates).

For committee pages, some of the issues we’ve uncovered include: Users need to view financial summary totals in a more useful presentation that shows nested subtotals; users need to see filings displayed in a more logical order and with a better selection of columns; and we need to add additional data like party expenditure aggregates.

---

## Tickets
- [x] fecgov/openFEC#1833
- [x] fecgov/fec-cms#839
- [x] fecgov/openFEC#2223
- [x] fecgov/openFEC#2212
- [x] fecgov/openFEC#2063
- [x] fecgov/openFEC-web-app#1755
- [x] fecgov/openFEC-web-app#1765
- [x] fecgov/openFEC-web-app#1783
- [x] fecgov/openFEC-web-app#1784
- [x] fecgov/openFEC-web-app#1785
- [x] fecgov/openFEC-web-app#1786
- [x] fecgov/openFEC-web-app#1819
- [x] fecgov/openFEC-web-app#1820
- [x] fecgov/openFEC-web-app#1821
- [x] fecgov/openFEC-web-app#1831
- [x] fecgov/openFEC-web-app#1832
- [x] fecgov/openFEC-web-app#1833
- [x] fecgov/openFEC-web-app#1834
- [x] fecgov/openFEC-web-app#1858
- [x] fecgov/openFEC-web-app#1859
- [x] fecgov/openFEC-web-app#1860
- [x] fecgov/openFEC-web-app#1862
- [x] fecgov/openFEC-web-app#1869
- [x] fecgov/openFEC-web-app#1884
- [x] fecgov/openFEC-web-app#1903
- [x] fecgov/openFEC-web-app#1969
- [x] fecgov/openFEC-web-app#2019
- [x] fecgov/openFEC-web-app#2087
