### ISSUE TITLE
Data table pages for loans, debts and coordinated expenditures

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#57]
**What we’re after:** We now have three new datasets: itemized loans (schedule C), debts (schedule D) and party expenditures (schedule F). We have this data in the API but not in any front-end feature. This would involve creating data table pages for each of these data sets so users could browse, filter and export the data.

**Why we’re after it:** While these data sets are a little more esoteric, they are still important. In order for all data to be fully accessible on the site, these need to have data pages available.

## Tickets
- [x] fecgov/openFEC-web-app#1148
- [x] fecgov/openFEC-web-app#1613
- [x] fecgov/openFEC-web-app#1615
