### ISSUE TITLE
Add administrative fine and ADR cases to enforcement matter search

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#59]
**What we’re after:** The other two types of enforcement actions in addition to Matters Under Review are administrative fine cases and Alternative Dispute Resolution cases. Currently, once these cases are closed, they are an additional type of data available in the Enforcement Query System (EQS). These cases have very similar data structures to MURs. Users will need to be able to search for these cases by various fields, view a list of results, and view an individual case. These should be part of universal search and users should also be able to search just one of these types. 

This will require getting the data into our systems and building the front-end search and individual case pages. Because these are so similar to MURs, we should be able to extend the same templates we’re using for MURs here and not require design effort. At the same time that we’re adding this data, we will need to add the accompanying content explaining how the programs work. 

**Why we’re after it:** If users are looking through one set of enforcement documents (like MURs), they most likely need to review the other types as well. Until these are available on the new site, users doing this sort of legal research will have to use the legacy Enforcement Query System.

## Tickets
- [x] fecgov/fec-eregs#328
- [x] fecgov/openFEC#2070
- [x] fecgov/openFEC#2084
- [x] fecgov/openFEC#2085
- [x] fecgov/openFEC-web-app#1703
- [x] fecgov/openFEC-web-app#1717
- [x] fecgov/openFEC-web-app#1737
