### ISSUE TITLE
Add remaining data

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#6]
## Tickets
- [x] fecgov/openFEC#1949
- [x] fecgov/openFEC#1788
- [x] fecgov/fec-epics#57
- [x] fecgov/openFEC-web-app#1148
- [x] fecgov/openFEC-web-app#1613
- [x] fecgov/openFEC-web-app#1615
- [x] fecgov/fec-epics#61
- [x] fecgov/openFEC#2135
- [x] fecgov/openFEC#2157
- [x] fecgov/openFEC#2101
- [x] fecgov/openFEC#2100
- [x] fecgov/openFEC#2067
- [x] fecgov/openFEC#2065
- [x] fecgov/openFEC#2066
- [x] fecgov/openFEC#2064
- [x] fecgov/openFEC-web-app#1716
- [x] fecgov/openFEC-web-app#1734
- [x] fecgov/openFEC-web-app#1739
- [x] fecgov/openFEC-web-app#1740
- [x] fecgov/openFEC-web-app#1741
- [x] fecgov/openFEC-web-app#1751
- [x] fecgov/openFEC#1865
- [x] fecgov/openFEC#1880
- [x] fecgov/openFEC#1824
- [x] fecgov/openFEC#1924
- [x] fecgov/openFEC#1927
- [x] fecgov/openFEC#1811
- [x] fecgov/openFEC#1909
- [x] fecgov/openFEC#1910
- [x] fecgov/openFEC#1700
- [x] fecgov/openFEC#1950
- [x] fecgov/openFEC#1913
- [x] fecgov/openFEC#1912
- [x] fecgov/openFEC#1911
- [x] fecgov/openFEC#1789
- [x] fecgov/openFEC#1907
- [x] fecgov/openFEC#1908
- [x] fecgov/openFEC-web-app#1371
- [x] fecgov/openFEC-web-app#1436
- [x] fecgov/openFEC-web-app#1463
- [x] fecgov/openFEC-web-app#1591
- [x] fecgov/openFEC-web-app#1616
