### ISSUE TITLE
Port content

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#60]
**What we’re after:** Move all content that’s not changing at all over to a home in the new site. This includes the “About the FEC” section,  FEC Record articles, and any other form of content that will be included in Latest Updates.

**Why we’re after it:** This is a low-cost way to fill out the new site with the content that needs to be there no matter what and which will not need to be redesigned or rewritten in any way. 

For latest updates in particular, the best way to learn about new policy, opinions, and other agency actions is through agency publications— by comparison, static content takes time to develop and get approved. The FEC’s regulated community needs this information as soon as possible so that they can follow the law. 

---

## Q1 Objectives:
- Move over all remaining items for "Latest updates":
  - FEC record articles
  - Tips for Treasurers
  - Sunshine notices (notices that a meeting is going to happen and generally what will be discussed at that meeting)
  - Meeting agendas (published after Sunshine notices and including more detail 
- Move over all documents and pages for "About FEC":
  - Department and office pages _(~30 HTML pages)_
  - Legislative recommendations, history, and reports _(~50 mix of PDF/HTML pages)_
  - Strategic plans _(~8 mix of PDF/HTML pages)_
  - Budget plans and reports _(~100 mix of PDF/HTML pages)_
  - FEC policies and directives _(~50 mix of PDF/HTML pages)_
  - Annual reports; anniversary reports _(~35 PDF pages)_
  - Procurement reports _(~10 PDF pages)_
  - IG reports _(~150 mix of PDF/HTML pages)_
  - Commissioner pages _(~690 mix of PDF/HTML pages)_
  - FOIA  _(~30 mix of PDF/XML pages)_

## Epics
- [x] fecgov/fec-epics#15
- [x] fecgov/fec-epics#53
- [x] fecgov/fec-epics#2

## Tickets

- [x] fecgov/fec-cms#790
- [x] fecgov/fec-cms#574
- [x] fecgov/fec-cms#486
- [x] fecgov/fec-cms#553
- [x] fecgov/fec-cms#789
- [x] fecgov/fec-cms#549
- [x] fecgov/fec-cms#550
- [x] fecgov/fec-cms#791
- [x] fecgov/fec-cms#788
- [x] fecgov/fec-cms#598
- [x] fecgov/fec-cms#524
- [x] fecgov/fec-cms#488
- [x] fecgov/fec-cms#496
- [x] fecgov/fec-cms#650
- [x] fecgov/fec-cms#674
- [x] fecgov/fec-cms#676
- [x] fecgov/fec-cms#574
- [x] fecgov/fec-cms#567
- [x] fecgov/fec-cms#486
- [x] fecgov/fec-cms#567
- [x] fecgov/fec-cms#569
- [x] fecgov/fec-cms#573
- [x] fecgov/fec-cms#514
- [x] fecgov/fec-cms#515
- [x] fecgov/fec-cms#393
- [x] fecgov/fec-cms#565
- [x] fecgov/fec-cms#575
- [x] fecgov/fec-cms#577
- [x] fecgov/fec-cms#589
- [x] fecgov/fec-cms#580
- [x] fecgov/fec-cms#412
- [x] fecgov/fec-cms#508
- [x] fecgov/fec-cms#487
- [x] fecgov/fec-cms#465
- [x] fecgov/fec-cms#467
- [x] fecgov/fec-cms#458
- [x] fecgov/fec-cms#411
- [x] fecgov/fec-cms#459
- [x] fecgov/fec-cms#446
- [x] fecgov/fec-cms#454
- [x] fecgov/fec-cms#440
- [x] fecgov/fec-cms#461
- [x] fecgov/fec-cms#455
- [x] fecgov/fec-cms#443
- [x] fecgov/fec-cms#441
- [x] fecgov/fec-cms#404
- [x] fecgov/fec-cms#628
- [x] fecgov/fec-cms#781
- [x] fecgov/fec-cms#773
- [x] fecgov/fec-cms#660
- [x] fecgov/fec-cms#769
- [x] fecgov/fec-cms#712
- [x] fecgov/fec-cms#740
- [x] fecgov/fec-cms#775
- [x] fecgov/fec-cms#678
- [x] fecgov/fec-cms#703
- [x] fecgov/fec-cms#705
- [x] fecgov/fec-cms#649
- [x] fecgov/fec-cms#677
- [x] fecgov/fec-cms#672
- [x] fecgov/fec-cms#629
- [x] fecgov/fec-cms#673
- [x] fecgov/fec-cms#675
- [x] fecgov/fec-cms#701
- [x] fecgov/fec-cms#641
- [x] fecgov/fec-cms#700
- [x] fecgov/fec-cms#669
- [x] fecgov/fec-cms#702
- [x] fecgov/fec-cms#642
- [x] fecgov/fec-cms#651
- [x] fecgov/fec-cms#667
- [x] fecgov/fec-cms#668
- [x] fecgov/fec-cms#466
- [x] fecgov/fec-cms#457
- [x] fecgov/fec-cms#627
- [x] fecgov/fec-cms#626
- [x] fecgov/fec-cms#640
- [x] fecgov/fec-cms#601
- [x] fecgov/fec-cms#633
- [x] fecgov/fec-cms#616
- [x] fecgov/fec-cms#565
- [x] fecgov/fec-cms#575
- [x] fecgov/fec-cms#569
- [x] fecgov/fec-eregs#272
- [x] fecgov/fec-cms#600
