### ISSUE TITLE
Add raw efiling data for itemized transactions

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#61]
**What we’re after:** When committees file reports electronically, we include those reports in our data tables and users can access the .pdf, .fec (and soon .csv) version of the files as soon as they’re available. We want to also make the itemized data within these reports accessible via the itemized receipts, disbursements and independent expenditures pages. Users should be able to toggle between viewing the raw efiling data and processed data, with the efiling data only going back a few months in order to keep the data set small.

**Why we’re after it:** Itemized data inside efiling reports is super important, and it is the kind of up-to-the-minute data that journalists crave. Allowing users to browse, filter and download this data the same way they do other data would make the efiling report viewing experience significantly better.

## Tickets

- [x] fecgov/openFEC#2135
- [x] fecgov/openFEC#2157
- [x] fecgov/openFEC#2101
- [x] fecgov/openFEC#2100
- [x] fecgov/openFEC#2067
- [x] fecgov/openFEC#2065
- [x] fecgov/openFEC#2066
- [x] fecgov/openFEC#2064
- [x] fecgov/openFEC-web-app#1716
- [x] fecgov/openFEC-web-app#1734
- [x] fecgov/openFEC-web-app#1739
- [x] fecgov/openFEC-web-app#1740
- [x] fecgov/openFEC-web-app#1741
- [x] fecgov/openFEC-web-app#1751

**Comment by noahmanger** [comment]
Hey guess what, we did this. Closing.
