### ISSUE TITLE
Completely replace data warehouse data

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#63]
**What we're after:** Completely replace all references to data warehouse data sources so that we're not dependent on the data warehouse for any of our data. This will require replacing tables and verifying that everything still works as expected.

**Why we're after it:** This is necessary to allow us to ultimately turn off data infrastructure for the FEC. 

## Sub-epic (_epicette_?): Improve filing data
**What we’re after:** We still have the filings table on the old data warehouse data source. By replacing this data source with a better source, we not only make the data more reliable but we also add the ability to do things like track the trail of which filings amended each other. This will also give us the ability to order the filings on the committee pages in a way that meets the needs of internal FEC power users better.

**Why we’re after it:** Being able to see which filings amended which makes it easier for users to get a better understanding of how filings change with amendments. It also allows us to order the results on the committee pages in a logical way, which gives users a clearer view of a committee’s filing history that is harder to get when they’re just sorted by filing date or coverage date.

## Tickets

- [x] fecgov/openFEC#2147
- [x] fecgov/fec-cms#777
- [x] fecgov/openFEC#2158
- [x] fecgov/openFEC#2094
- [x] fecgov/openFEC#2097
- [x] fecgov/openFEC#2102
- [x] fecgov/openFEC#2042
- [x] fecgov/openFEC#2073
- [x] fecgov/openFEC#2080
- [x] fecgov/openFEC#2051
- [x] fecgov/openFEC#2049
- [x] fecgov/openFEC#2050
- [x] fecgov/openFEC-web-app#1371
- [x] fecgov/openFEC-web-app#1715
- [x] fecgov/openFEC-web-app#1738
- [x] fecgov/openFEC-web-app#1806
