### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#64]
**What we’re after:** Ensure that the FEC staff are knowledgeable about everything they need to know to design, develop, and maintain 18F FEC projects through training in general areas like Python, Agile product management, and user centered design, and in FEC project specific areas, like FEC application architecture, how to work with our open source projects, cloud strategy, and our internal devops practices.

**Why we’re after it:** Sometimes documentation just doesn’t cut it.  Training gives us the potential for hands on practice, and can allow for more interactive discourse between student and teacher.

## Epics
- [x] fecgov/fec-epics#94
- [x] fecgov/fec-epics#95
- [x] fecgov/fec-epics#96
- [x] fecgov/fec-epics#97
- [x] fecgov/fec-epics#85
- [x] fecgov/fec-epics#89
- [x] fecgov/fec-epics#86
- [x] fecgov/fec-epics#88
- [x] fecgov/fec-epics#87
- [x] fecgov/fec-epics#103
- [x] fecgov/fec-epics#90
- [x] fecgov/fec-epics#92
- [x] fecgov/fec-epics#93
- [x] fecgov/fec-epics#91
- [x] fecgov/fec-epics#98
- [x] fecgov/fec-epics#101
- [x] fecgov/fec-epics#102
- [x] fecgov/fec-epics#99
- [x] fecgov/fec-epics#100

## Tickets

- [x] fecgov/fec-transition#20
- [x] fecgov/fec-transition#31
- [x] fecgov/fec-transition#36
- [x] fecgov/fec-transition#28
- [x] fecgov/fec-transition#30
- [x] fecgov/fec-transition#48
- [x] fecgov/fec-transition#49
- [x] fecgov/fec-cms#631
- [x] fecgov/fec-transition#35
- [x] fecgov/fec-transition#37
- [x] fecgov/fec-transition#38
- [x] fecgov/fec-transition#33
- [x] fecgov/fec-cms#5949
- [x] fecgov/fec-cms#5142
- [x] fecgov/fec-transition#17
- [x] fecgov/openFEC#2084
- [x] fecgov/openFEC#2085
- [x] fecgov/fec-cms#762
- [x] fecgov/fec-transition#12
- [x] fecgov/fec-transition#13
- [x] fecgov/fec-transition#19
- [x] fecgov/fec-transition#24
- [x] fecgov/fec-transition#32
