### ISSUE TITLE
FEC Integration Team

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#68]
**What we’re after:** Select and onboard a cross-functional technology and product team composed of FEC staff that shadow our internal 18F team and help guide and groom our transition backlog in future sprints.

**Why we’re after it:** In order for FEC to start designing, developing, and maintaining the software systems that 18F has built, it is important that they understand our technology, motivations, and practices, and we are able to form very effective communication channels between 18F team members and FEC staff before, during, and after the handoff.

## Tickets
- [x] fecgov/fec-transition#34
- [x] fecgov/fec-transition#40
- [x] fecgov/fec-transition#43
