### ISSUE TITLE
Digital Services Team

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#69]
**What we’re after:** Help determine the team structure, organizational integration strategy, position descriptions, and team policies to launch a Digital Services Team within the FEC composed of newly hired or assigned FEC staff or potential contractor supported positions.

**Why we’re after it:** For FEC to efficiently deliver and maintain product features, there must be a highly effective cross functional team that operates within the boundaries of the larger IT organization, potentially built from IT division representatives.  We need a targeted way to safely experiment with new team practices to foster a culture of innovation. 

## Tickets
- [x] fecgov/fec-transition#11
- [x] fecgov/fec-transition#18
- [x] fecgov/fec-transition#23
- [x] fecgov/fec-transition#25
