### ISSUE TITLE
Make improvements to downloaded files

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#7]
## Tickets
- [x] fecgov/openFEC#1416
- [x] fecgov/openFEC#1940
- [x] fecgov/openFEC#1894
- [x] fecgov/openFEC-web-app#1418
- [x] fecgov/openFEC-web-app#1419
- [x] fecgov/openFEC-web-app#1420
- [x] fecgov/openFEC-web-app#1421
- [x] fecgov/openFEC-web-app#1422
- [x] fecgov/openFEC-web-app#1438
- [x] fecgov/openFEC-web-app#1490
