### ISSUE TITLE
IT Research and Recommendations

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#70]
**What we’re after:** Perform FEC directed research in areas like IT policy, cloud strategy, and efiling modernization, and deliver prototypes and recommendations that the FEC management can use to drive change throughout the organization.

**Why we’re after it:** FEC has questions.  18F has researchers that can help find answers or alternatives.  In some cases this research aligns with existing projects which helps us with the transition in different ways.

## Epics
- [x] fecgov/fec-epics#22
- [x] fecgov/fec-epics#23
- [x] fecgov/fec-epics#24
- [x] fecgov/fec-epics#25

## Tickets
- [x] fecgov/fec-transition#15
- [x] fecgov/fec-transition#26
