### ISSUE TITLE
Documentation / Guides

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#71]
**What we’re after:** Build a clear, concise repository of documentation and guides covering topics such as team building, product management processes, design and user testing, technology architecture, development and deployment processes, and content management and migration processes.

**Why we’re after it:** FEC staff do not know what we know about the projects we have built.  To take over 18F projects, FEC staff will have to understand fully what we do and what we have built.  The most efficient means of scalably transferring our knowledge is through various mediums of documentation and guides.

## Epics
- [x] fecgov/fec-epics#79
- [x] fecgov/fec-epics#84
- [x] fecgov/fec-epics#80
- [x] fecgov/fec-epics#81
- [x] fecgov/fec-epics#82
- [x] fecgov/fec-epics#83
- [x] fecgov/fec-epics#76
- [x] fecgov/fec-epics#77
- [x] fecgov/fec-epics#78

## Tickets
- [x] fecgov/fec-cms#759
- [x] fecgov/fec-cms#623
- [x] fecgov/fec-cms#403
- [x] fecgov/fec-transition#44
- [x] fecgov/fec-transition#45
- [x] fecgov/fec-transition#46
- [x] fecgov/fec-transition#50
- [x] fecgov/fec-transition#51
- [x] fecgov/openFEC#2112
- [x] fecgov/fec-transition#17
- [x] fecgov/fec-transition#39
- [x] fecgov/fec-transition#47
- [x] fecgov/fec-transition#41
- [x] fecgov/fec-transition#42
