### ISSUE TITLE
Technology Transfer

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#73]
**What we’re after:** Hand off all software systems and service accounts to FEC management for design, development, and maintenance by internal FEC staff and contractors following 18F principles and practices.  Work with the FEC to ensure that FEC is comfortable post handoff.

**Why we’re after it:** The FEC IT organization must ultimately switch betaFEC to the live fec.gov site, which involves quite a few different software systems.  It is very important that there is effective coordination and careful planning in order to avoid production outages that affect the ability for FEC to serve its mission.

## Tickets
- [x] fecgov/openFEC#2194
- [x] fecgov/fec-cms#1109
- [x] fecgov/openFEC#2301
- [x] fecgov/openFEC#2264
- [x] fecgov/openFEC#2294
- [x] fecgov/openFEC#2308
- [x] fecgov/openFEC#2291
- [x] fecgov/openFEC#2259
- [x] fecgov/fec-cms#805
- [x] fecgov/openFEC#2032
- [x] fecgov/openFEC#2230
- [x] fecgov/openFEC#2253
- [x] fecgov/fec-eregs#337
- [x] fecgov/openFEC#2266
- [x] fecgov/fec-eregs#305
- [x] fecgov/fec-cms#820
- [x] fecgov/openFEC#2196
- [x] fecgov/fec-cms#838
- [x] fecgov/fec-eregs#331
- [x] fecgov/fec-eregs#312
- [x] fecgov/fec-cms#582
- [x] fecgov/fec-cms#583
- [x] fecgov/openFEC#2033
- [x] fecgov/fec-transition#16
- [x] fecgov/openFEC-web-app#1684
- [x] fecgov/openFEC-web-app#1701
- [x] fecgov/openFEC-web-app#1840
- [x] fecgov/openFEC-web-app#1898
- [x] fecgov/fec-epics#51
- [x] fecgov/fec-cms#581
- [x] fecgov/fec-eregs#305
- [x] fecgov/openFEC#2031
- [x] fecgov/openFEC#2030
- [x] fecgov/openFEC#2047
- [x] fecgov/fec-transition#29
