### ISSUE TITLE
Technology Architecture documentation

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#78]
Documentation on the technologies, systems, and patterns necessary to operate the 18F developed FEC.gov site.

## Tickets
- [x] fecgov/openFEC#2112
- [x] fecgov/fec-transition#17
- [x] fecgov/fec-transition#39
- [x] fecgov/fec-transition#47
