### ISSUE TITLE
Improve data table interactions

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#8]
## Tickets
- [x] fecgov/openFEC#1851
- [x] fecgov/openFEC#1925
- [x] fecgov/openFEC-web-app#1349
- [x] fecgov/openFEC-web-app#1364
- [x] fecgov/openFEC-web-app#1415
- [x] fecgov/openFEC-web-app#1416
- [x] fecgov/openFEC-web-app#1417
- [x] fecgov/openFEC-web-app#1423
- [x] fecgov/openFEC-web-app#1429
- [x] fecgov/openFEC-web-app#1430
- [x] fecgov/openFEC-web-app#1432
- [x] fecgov/openFEC-web-app#1440
- [x] fecgov/openFEC-web-app#1476
- [x] fecgov/openFEC-web-app#1477
- [x] fecgov/openFEC-web-app#1480
- [x] fecgov/openFEC-web-app#1484
- [x] fecgov/openFEC-web-app#1486
- [x] fecgov/openFEC-web-app#1488
- [x] fecgov/openFEC-web-app#1492
- [x] fecgov/openFEC-web-app#1493
- [x] fecgov/openFEC-web-app#1496
- [x] fecgov/openFEC-web-app#1499
- [x] fecgov/openFEC-web-app#1502
- [x] fecgov/openFEC-web-app#1541
- [x] fecgov/openFEC-web-app#1542
- [x] fecgov/openFEC-web-app#1566
- [x] fecgov/openFEC-web-app#1612
- [x] fecgov/openFEC-web-app#1669
- [x] fecgov/openFEC-web-app#1815
