### ISSUE TITLE
Design / Research practices documentation

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#80]
Documentation on the principles and practices driving the user centered design of the 18F developed FEC.gov site.

## Tickets
- [x] fecgov/fec-transition#44
- [x] fecgov/fec-transition#45
- [x] fecgov/fec-transition#46
- [x] fecgov/fec-transition#50
