### ISSUE TITLE
Content Governance documentation

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#84]
## Update for PI 2:

**What we’re after**: Help the FEC establish a governance process that will guide the publication of content on the new site. This includes developing policies, standards and processes to ensure the FEC can continue to maintain and grow its new website consistent with the goals and principles of user-centered design and plain language content. 

**Why we’re after it**: FEC needs the ability to create, edit and publish content that meets the needs of users. 

- [x] fecgov/fec-cms#759 
- [x] fecgov/fec-cms#623
- [x] fecgov/fec-cms#403
