### ISSUE TITLE
Workshops

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#85]
Various workshops facilitated by 18F staff provided to FEC on a one off basis.

## Epics
- [x] fecgov/fec-epics#89
- [x] fecgov/fec-epics#86
- [x] fecgov/fec-epics#87
- [x] fecgov/fec-epics#103

## Tickets
- [x] fecgov/fec-transition#20
- [x] fecgov/fec-transition#31
- [x] fecgov/fec-transition#36
- [x] fecgov/fec-transition#28
- [x] fecgov/fec-transition#30
- [x] fecgov/fec-transition#48
- [x] fecgov/fec-transition#49
- [x] fecgov/fec-epics#88
- [x] fecgov/fec-cms#631
- [x] fecgov/fec-transition#35
- [x] fecgov/fec-transition#37
- [x] fecgov/fec-transition#38
