### ISSUE TITLE
Cloud.gov workshops

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#86]
Workshops that the 18F FEC team or the cloud.gov team give to FEC pertaining to cloud.gov.

## Tickets
- [x] fecgov/fec-transition#20
- [x] fecgov/fec-transition#31
- [x] fecgov/fec-transition#36
