### ISSUE TITLE
Culture and practices workshops

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#87]
Workshops about different facets of culture and community when developing software.

## Tickets
- [x] fecgov/fec-transition#28
- [x] fecgov/fec-transition#30
- [x] fecgov/fec-transition#48
- [x] fecgov/fec-transition#49
