### ISSUE TITLE
Improve calendar page

### ISSUE THREAD

**Issue by noahmanger** [fecgov/fec-epics#9]
## Tickets
- [x] fecgov/fec-cms#338
- [x] fecgov/fec-cms#444
- [x] fecgov/fec-cms#445
