### ISSUE TITLE
Curriculum driven courses

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#90]
Structured courses lasting a period of time designed for active participation by FEC staff (and/or contractors)

## Epics
- [x] fecgov/fec-epics#92
- [x] fecgov/fec-epics#93
- [x] fecgov/fec-epics#91

## Tickets
- [x] fecgov/fec-transition#33
