### ISSUE TITLE
External training / courses

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#94]
All externally provided training recommended to FEC staff by 18F.

## Epics
- [x] fecgov/fec-epics#95
- [x] fecgov/fec-epics#96
- [x] fecgov/fec-epics#97
