### ISSUE TITLE
Integrated project work

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#98]
Projects that are meant to provide a learn by doing framework, where the team members participate in the product delivery process and deliver features or improvements to the software systems.

## Epics
- [x] fecgov/fec-epics#101
- [x] fecgov/fec-epics#102
- [x] fecgov/fec-epics#99
- [x] fecgov/fec-epics#100

## Tickets
- [ ] fecgov/fec-cms#5949
- [ ] fecgov/fec-cms#5142
- [x] fecgov/fec-transition#17
- [x] fecgov/openFEC#2084
- [x] fecgov/openFEC#2085
