### ISSUE TITLE
Frontend development projects

### ISSUE THREAD

**Issue by adrianwebb** [fecgov/fec-epics#99]
Projects that involve simpler programming of interfaces and user centric features.

## Tickets
- [x] fecgov/fec-cms#5949
- [x] fecgov/fec-cms#5142
- [x] fecgov/fec-transition#17
